Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2021-08, with the labels that each got.

#1541 RD-2156 Upgrade Cypress to v8
  package-lock.json
  package.json
  test/cypress/integration/login_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/integration/widgets/plugins_spec.ts
  test/cypress/integration/widgets/sites_map_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/index.ts
  test/cypress/support/resource_commons.ts
Labels: dependencies, internal

#1546 RD-2981 Add PR template
  .github/pull_request_template.md
Labels: internal

#1547 RD-2982 Improve CI pipeline by running Audit stage for all branches
  jenkins/Jenkinsfile
Labels: internal

#1549 RD-2808 Add system tests for "Number of Deployments" widget
  test/cypress/integration/widgets/deployment_num_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/sites_map_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/commands.ts
Labels: internal

#1550 RD-2970 Use only production dependencies when building Stage RPM
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  packaging/cloudify-stage.spec
  test/jest/.eslintrc.json
  webpack.config.js
Labels: internal

#1554 RD-2934 Extract blueprint marketplace related code into `Stage.Common.BlueprintMarketplace`
  app/components/shared/DynamicTable.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/blueprintMarketplace/types.ts
Labels: internal

#1552 RD-1277 Refactored manager proxy API
  app/utils/Manager.ts
  backend/routes/ServerProxy.js
  backend/test/routes/ServerProxy.test.js
  package-lock.json
  package.json
  test/cypress/integration/cluster_status_spec.ts
  test/cypress/integration/widgets/agents_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/deployment_actions_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployment_num_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/events_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  test/cypress/integration/widgets/plugins_catalog_spec.ts
  test/cypress/support/commands.ts
  test/jest/components/LicensePage.test.tsx
  test/jest/utils/Manager.test.ts
Labels: internal

#1556 RD-2999 Improve UserAppDataAutoSaver and fix Edit Mode test
  app/reducers/widgetsReducer.ts
  app/utils/UserAppDataAutoSaver.ts
  test/cypress/integration/edit_mode_spec.ts
  test/cypress/integration/page_spec.ts
  test/cypress/support/commands.ts
  test/jest/reducers/pagesReducer.test.ts
Labels: bug-fix, internal

#1557 RD-2801 Added support for `display_label` input property
  test/cypress/fixtures/blueprints/simple.zip
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/InputsUtils.tsx
  widgets/deploymentWizardButtons/src/steps/InputsStep.tsx
Labels: feature

#1561 RD-3014 Changed upload button styling and refactored `PluginsTable` component
  app/translations/en.json
  widgets/common/src/hooks/useRefreshEvent.ts
  widgets/plugins/src/PluginsTable.tsx
Labels: bug-fix

#1562 RD-3024 Change build result to UNSTABLE when audit stage fails
  jenkins/Jenkinsfile
Labels: internal

#1551 RD-2930 Add basic implementation for new widget "Number of clouds"
  app/translations/en.json
  backend/test/handlers/WidgetHandler.test.js
  scripts/readmesConfig.json
  test/cypress/integration/widgets/cloud_num_spec.ts
  widgets/cloudNum/README.md
  widgets/cloudNum/src/widget.tsx
  widgets/cloudNum/widget.png
Labels: feature

#1555 RD-2934 Add "Service Button" widget
  app/translations/en.json
  app/utils/StageAPI.ts
  backend/test/handlers/WidgetHandler.test.js
  scripts/readmesConfig.json
  test/cypress/integration/widgets/deployment_num_spec.ts
  widgets/common/src/SemanticColorDropdown.tsx
  widgets/common/src/SemanticIconDropdown.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/serviceButton/README.md
  widgets/serviceButton/src/ServiceButton.tsx
  widgets/serviceButton/src/widget.tsx
  widgets/serviceButton/widget.png
Labels: feature

#1564 RD-2826 & RD-2479 Update widget help description for "Number of Deployments", "Plugins" and "Plugins Catalog" widgets
  widgets/deploymentNum/README.md
  widgets/plugins/README.md
  widgets/pluginsCatalog/README.md
Labels: feature

#1565 RD-2936 Enhance "Button Link" widget and improve Getting Started modal to allow opening it on URL change
  app/app.tsx
  app/components/GettingStartedModal/useModalOpenState.ts
  app/styles/style.scss
  app/translations/en.json
  app/typings/stage-api.d.ts
  app/utils/hooks/index.ts
  app/utils/hooks/useSearchParam.ts
  widgets/buttonLink/src/ButtonLink.tsx
  widgets/buttonLink/src/widget.tsx
  widgets/common/src/deploymentsView/header/common.ts
  widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
  widgets/common/src/deploymentsView/header/index.tsx
Labels: feature

#1563 RD-2964 Prevented 0 width grid render
  app/components/layout/Grid.tsx
  test/cypress/integration/edit_mode_spec.ts
  test/jest/components/Grid.test.tsx
Labels: bug-fix

#1570 RD-2977 Upgrade `passport-saml` to fix security audit issues
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
Labels: dependencies, internal

#1572 RD-2936 Fix useModalOpenState to allow closing Getting Started modal in all cases
  app/components/GettingStartedModal/useModalOpenState.ts
Labels: bug-fix

#1568 RD-2932 Remove confirmation button from blueprint catalog.
  app/utils/StageAPI.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryList.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/UploadModal.tsx
  widgets/blueprintCatalog/src/actions.ts
  widgets/blueprintCatalog/src/props/ActionsPropType.ts
  widgets/blueprintCatalog/src/props/DataPropType.ts
  widgets/blueprintCatalog/src/props/RepositoryViewDefaultProps.ts
  widgets/blueprintCatalog/src/props/RepositoryViewPropTypes.ts
  widgets/blueprintCatalog/src/types.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/common/src/FeedbackMessages.tsx
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
Labels: feature

#1573 RD-2977 Upgrade `passport-saml` to fix security audit issues [6.2]
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
Labels: dependencies, internal
