Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2021-12, with the labels that each got.

#1688 RD-3477 Renamed isLdap parameter so that it is consistent across the application
  app/components/sidebar/UserMenu.tsx
  app/reducers/managerReducer.ts
Labels: bug-fix

#1685 RD-3425 Use `latest_execution` field from deployments API in widgets
  app/translations/en.json
  backend/handler/RequestHandler.ts
  backend/handler/services/ManagerService.ts
  backend/handler/services/RequestService.ts
  backend/handler/services/common.ts
  backend/package-lock.json
  backend/package.json
  backend/test/handlers/ManagerHandler.test.ts
  backend/test/handlers/RequestHandler.test.ts
  backend/test/handlers/services/ManagerService.test.ts
  backend/types.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/executions.ts
  test/cypress/support/resource_commons.ts
  test/jest/widgets/common/DeploymentActions.test.ts
  widgets/common/src/DeploymentActions.ts
  widgets/common/src/ExecutionActions.ts
  widgets/deployments/src/widget.tsx
  widgets/executions/src/widget.tsx
  widgets/managers/src/backend.js
Labels: bug-fix

#1692 RD-3691 System test fix
  test/cypress/integration/widgets/user_defined_widgets_spec.ts
Labels: bug-fix

#1686 RD-3460 Select only one environment on GettingStartedModal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalActions.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/formValidation.ts
  app/components/GettingStartedModal/steps/EnvironmentsStep/EnvironmentsStep.tsx
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#1694 RD-3463 Redirect user to blueprint page upon closing the modal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#1695 RD-3207 Add backend endpoint for generating Terraform blueprint
  backend/app.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Terraform.ts
  backend/templates/terraform/blueprint.ejs
  backend/templates/terraform/inputs.ejs
  backend/templates/terraform/outputs.ejs
  backend/templates/terraform/variables.ejs
  backend/test/routes/Terraform.test.ts
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  backend/test/routes/fixtures/terraform/2_inputs.json
  doc/diagrams/architecture-backend.png
  doc/diagrams/architecture-backend.txt
  doc/diagrams/architecture-frontend.png
  doc/diagrams/architecture-general.png
Labels: feature

#1696 RD-3495 Allow user to not provide secrets values in GettingStartedModal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/formValidation.ts
  app/components/GettingStartedModal/steps/SecretsStep.tsx
  app/components/GettingStartedModal/steps/SummaryStep/BlueprintsInstallationTasks.tsx
  app/components/GettingStartedModal/steps/SummaryStep/PluginTaskItems.tsx
  app/components/GettingStartedModal/steps/SummaryStep/SecretsInstallationTasks.tsx
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
  app/components/GettingStartedModal/steps/SummaryStep/descriptionGetters.tsx
  app/translations/en.json
  package-lock.json
  test/cypress/integration/getting_started_spec.ts
  widgets/secrets/src/SecretsTable.tsx
Labels: feature

#1699 RD-3587 Display number of executions on executionsStatus widget
  app/components/shared/graphs/Graph.tsx
  app/translations/en.json
  package-lock.json
  package.json
  test/cypress/integration/widgets/executions_status_spec.ts
  widgets/executionsStatus/src/types.ts
  widgets/executionsStatus/src/widget.tsx
Labels: bug-fix

#1698 RD-3207 Added Terraform blueprint generation to blueprint upload options
  app/components/shared/DynamicTable.tsx
  app/translations/en.json
  app/utils/External.ts
  backend/routes/Terraform.ts
  backend/routes/Terraform.types.ts
  devServer.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/jest/widgets/common/BlueprintActions.test.ts
  widgets/blueprintCatalog/src/RepositoryList.tsx
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/TerraformActions.ts
  widgets/blueprints/src/TerraformModal.tsx
  widgets/blueprints/src/TerraformModalAccordion.tsx
  widgets/blueprints/src/TerraformModalTableAccordion.tsx
  widgets/blueprints/src/TerraformVariableValueInput.tsx
  widgets/blueprints/src/terraformVersions.ts
  widgets/common/src/BlueprintActions.ts
  widgets/common/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/Consts.ts
  widgets/common/src/UploadBlueprintForm.tsx
  widgets/common/src/UploadBlueprintModal.tsx
  widgets/deploymentWizardButtons/src/steps/ConfirmationStep.tsx
  widgets/tsconfig.json
Labels: feature

#1700 RD-3730 Modified execution of disabling the popup
  app/components/shared/ExecutionStatus.tsx
Labels: bug-fix

#1703 RD-3760 Improve Maintenance Mode Button widget test to be more robust
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
Labels: bug-fix

#1701 RD-3482 Add styling to sidebar
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SideBarHeader.tsx
  app/components/sidebar/SideBarItem.tsx
  app/components/sidebar/SideBarItemIcon.tsx
  app/components/sidebar/UserInitialsIcon.tsx
  conf/userConfig.json
  test/cypress/integration/flows/admin_spec.ts
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/page_spec.ts
  test/cypress/integration/widgets/sites_map_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/plugins.ts
Labels: feature

#1704 RD-3207 Updated blueprint template
  backend/templates/terraform/blueprint.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
Labels: feature

#1693 RD-1607 Change missing secrets error in Deploy Blueprints
  .size-limit
  app/translations/en.json
  test/cypress/fixtures/blueprints/required_secrets.zip
  test/cypress/integration/widgets/deployment_button_spec.ts
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/MissingSecretsError.tsx
  widgets/common/src/SecretActions.ts
  widgets/common/src/SecretsModal.tsx
Labels: feature

#1705 RD-1607 Follow-up PR: Refactor and fix system test for missing secrets error message
  test/cypress/integration/widgets/deployment_button_spec.ts
Labels: feature

#1702 RD-3733: Fix not closing information about the form errors
  package.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/UploadBlueprintForm.tsx
  widgets/common/src/UploadBlueprintModal.tsx
Labels: bug-fix

#1708 RD-3734 - Transforming links which are pointing out to the local MD file
  .size-limit
  scripts/updateReadmes.js
  widgets/deploymentsView/README.md
  widgets/filters/README.md
Labels: bug-fix

#1709 RD-3806 Adjust height of Deployments View widget in Services and Environments pages
  templates/pages/environments.json
  templates/pages/services.json
  widgets/common/src/deploymentsView/DeploymentsView.tsx
  widgets/common/src/deploymentsView/layout.ts
Labels: bug-fix

#1706 RD-3659 Added field validations
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: feature

#1712 RD-3806 Increase height of Deployments View widget in Services and Environments pages
  templates/pages/environments.json
  templates/pages/services.json
Labels: bug-fix

#1713 RD-3482 Update README.md for configuration files
  conf/README.md
Labels: internal

#1711 RD-2455 Transform markdown links inside the styled message blocks into the anchor elements
  app/utils/widgetDefinitionsLoader.ts
  scripts/updateReadmes.js
  widgets/deploymentsView/README.md
  widgets/filter/README.md
Labels: bug-fix

#1710 RD-3660 Added more validations to Terraform modal
  app/translations/en.json
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: feature

#1715 RD-2457: Styled tables inside the widgets documentations
  scripts/updateReadmes.js
  widgets/filters/README.md
Labels: bug-fix

#1717 RD-3660 Terraform modal improvements
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  test/cypress/fixtures/terraform/local.zip
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformModal.tsx
  widgets/blueprints/src/TerraformVariableValueInput.tsx
Labels: feature

#1719 RD-3850 Minor updates around Terraform wrapper modal
  .size-limit
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/images/terraform-icon.png
  widgets/blueprints/src/TerraformModal.tsx
  widgets/blueprints/src/terraformVersions.ts
Labels: feature

#1697 RD-3622 Add accordion in Create Deployment modal
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprints/src/TerraformModal.tsx
  widgets/blueprints/src/TerraformModalAccordion.tsx
  widgets/blueprints/src/TerraformModalTableAccordion.tsx
  widgets/common/src/AccordionSection.tsx
  widgets/common/src/AccordionSectionWithDivider.tsx
  widgets/common/src/DataTypesButton.tsx
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/InputsHeader.tsx
  widgets/common/src/InputsUtils.tsx
  widgets/common/src/ParameterValue.tsx
  widgets/common/src/YamlFileButton.tsx
Labels: feature

#1724 RD-3816 Fix topology_spec
  test/cypress/fixtures/blueprints/topology.zip
Labels: bug-fix

#1725 RD-3809 Change the color of missing secrets button
  widgets/common/src/MissingSecretsError.tsx
Labels: feature

#1723 RD-3623 Combine Deploy and Install buttons in Deploy Blueprint Modal
  app/translations/en.json
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprint_actions_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  widgets/common/src/GenericDeployModal.tsx
Labels: feature

#1726 RD-3208 Added Terraform module path dropdown in place of text input
  app/translations/en.json
  backend/package-lock.json
  backend/package.json
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  backend/test/routes/fixtures/terraform/template.zip
  test/cypress/fixtures/terraform/multiple.zip
  test/cypress/fixtures/terraform/single.zip
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformActions.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: feature

#1727 RD-3624 (part 1) refactor before implementation
  widgets/common/src/BlueprintActions.ts
  widgets/common/src/DataTypesButton.tsx
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/InputsHeader.tsx
  widgets/common/src/YamlFileButton.tsx
  widgets/common/src/deployModal/DeploymentInputsSection.tsx
Labels: internal
