Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2021-10, with the labels that each got.

#1627 RD-2993 Reused common setup and configuration for component testing
  package-lock.json
  package.json
  test/cypress/plugins/index.ts
Labels: internal

#1623 RD-381 Update DB related code to be compatible with Sequelize v6
  backend/db/Connection.ts
  backend/db/models/ApplicationsModel.js
  backend/db/models/BlueprintAdditionsModel.js
  backend/db/models/ClientConfigsModel.js
  backend/db/models/UserAppsModel.js
  backend/db/models/WidgetBackendsModel.js
  backend/handler/BackendHandler.ts
  backend/handler/FilterHandler.ts
  backend/handler/WidgetHandler.ts
  backend/migrations/20201030110539-5_1_1-MigratePageLayouts.js
  backend/migrations/20201230113319-5_1_1-UpdateManagerIp.js
  backend/package-lock.json
  backend/package.json
  backend/routes/Applications.ts
  backend/routes/BlueprintAdditions.ts
  backend/routes/BlueprintUserData.ts
  backend/routes/ClientConfig.ts
  backend/routes/UserApp.ts
  backend/test/routes/Applications.test.ts
  backend/test/routes/ClientConfig.test.ts
  backend/test/routes/Filters.test.ts
  backend/test/routes/UserApp.test.ts
Labels: internal

#1625 RD-3214 Remove Subenvironments and Subservices columns in Services page
  templates/pages/services.json
Labels: feature

#1628 RD-3241 Added backend support for reading list of built-in page groups
  backend/__mocks__/passport.ts
  backend/handler/AuthHandler.ts
  backend/handler/WidgetsHandler.ts
  backend/handler/templates/PageGroupsHandler.ts
  backend/handler/templates/PagesHandler.ts
  backend/handler/templates/TemplatesHandler.ts
  backend/handler/templates/index.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Templates.ts
  backend/routes/Widgets.ts
  backend/routes/index.d.ts
  backend/server.ts
  backend/test/handlers/AuthHandler.test.ts
  backend/test/handlers/WidgetHandler.test.ts
  backend/test/handlers/templates/PageGroupsHandler.test.ts
  backend/test/handlers/templates/TemplatesHandler.test.ts
  backend/test/routes/Widgets.test.ts
  backend/tsconfig.json
  backend/types.ts
Labels: feature

#1631 RD-3322 Make snapshot widget test less prone to timeout errors
  test/cypress/integration/widgets/snapshots_spec.ts
Labels: internal

#1641 RD-3370 Dependency update
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#1642 RD-2029 Upgrade cloudify-blueprint-topology to 2.5.3
  package-lock.json
  package.json
Labels: dependencies, bug-fix

#1639 RD-3241 Added support for adding/removing page groups to/from templates
  app/components/layout/Layout.tsx
  app/components/templateManagement/TemplateManagement.tsx
  app/components/templateManagement/pages/CreatePageModal.tsx
  app/components/templateManagement/pages/PageManagement.tsx
  app/components/templateManagement/pages/Pages.tsx
  app/components/templateManagement/pages/TemplateList.tsx
  app/components/templateManagement/templates/CreateTemplateModal.tsx
  app/components/templateManagement/templates/PageMenuItemsList.tsx
  app/components/templateManagement/templates/RoleList.tsx
  app/components/templateManagement/templates/Templates.tsx
  app/components/templateManagement/templates/TenantList.tsx
  app/components/templateManagement/templates/types.ts
  app/components/templates/CreateTemplateModal.tsx
  app/components/templates/PageList.tsx
  app/translations/en.json
  app/utils/hooks/index.ts
  app/utils/hooks/useInput.ts
  app/utils/hooks/useOpen.ts
  test/cypress/integration/templates/template_management_spec.ts
Labels: feature
