Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2021-09, with the labels that each got.

#1574 RD-2936 Fix useModalOpenState to allow closing Getting Started modal in all cases [6.2]
  app/components/GettingStartedModal/useModalOpenState.ts
Labels: bug-fix

#1569 RD-3016 Add hiding `Generate in the Composer` button feature.
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/BlueprintUploadActionsMenu.tsx
Labels: feature

#1578 RD-2932 Remove confirmation button from blueprint catalog. (#1568)
  app/utils/StageAPI.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryList.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/UploadModal.tsx
  widgets/blueprintCatalog/src/actions.ts
  widgets/blueprintCatalog/src/props/ActionsPropType.ts
  widgets/blueprintCatalog/src/props/DataPropType.ts
  widgets/blueprintCatalog/src/props/RepositoryViewDefaultProps.ts
  widgets/blueprintCatalog/src/props/RepositoryViewPropTypes.ts
  widgets/blueprintCatalog/src/types.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/common/src/FeedbackMessages.tsx
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
Labels: feature, cherry-pick

#1583 RD-3016 Add additional test cases for check item in blueprint upload menu
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: internal

#1579 RD-3016 Add hiding Generate in the Composer button feature. (#1569)
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/BlueprintUploadActionsMenu.tsx
Labels: bug-fix, feature, cherry-pick

#1580 RD-3048 Added welcome step to 'getting started' modal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalActions.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/ModalHeader.tsx
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/steps/WelcomeStep.tsx
  app/components/LoginPage.tsx
  app/components/banner/LargeLogo.tsx
  app/components/banner/LogoLabel.tsx
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#1584 RD-3113 Fix for bug introduced during refactoring
  app/components/GettingStartedModal/ModalHeader.tsx
Labels: bug-fix

#1587 RD-1291 Updated coverage reference commit
  backend/jest.config.js
  backend/utils.ts
Labels: internal

#1582 RD-1132 Remove Marketplace page.
  templates/community.json
  templates/main-default.json
  templates/main-sys_admin.json
  templates/pages/marketplace.json
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/tenants_spec.ts
Labels: feature

#1586 RD-3010 Further 'getting started' modal improvements
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/ModalHeader.tsx
  app/components/GettingStartedModal/createEnvironmentsGroups.tsx
  app/components/GettingStartedModal/steps/SecretsStep.tsx
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: enhancement

#1576 RD- 2933 Update Dashboard page
  .size-limit
  app/images/k8s_logo.png
  app/translations/en.json
  templates/pages/adminDash.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  webpack.config.js
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/serviceButton/src/ServiceButton.tsx
Labels: feature

#1590 RD- 2933 Update Dashboard page [6.2]
  .size-limit
  app/images/k8s_logo.png
  app/translations/en.json
  templates/pages/adminDash.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  webpack.config.js
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/serviceButton/src/ServiceButton.tsx
Labels: feature

#1591 RD-3123 Refactor waiting in login_spec.ts
  test/cypress/integration/login_spec.ts
Labels: internal

#1581 RD-3017 Add support for switching between Catalog and Table view in Blueprints Marketplace modal.
  app/translations/en.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/types.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/blueprintMarketplace/types.ts
Labels: feature

#1593 RD-3017 Add support for switching between Catalog and Table view in Blueprints Marketplace modal. (#1581)
  app/translations/en.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/types.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/blueprintMarketplace/types.ts
Labels: cherry-pick

#1596 RD-3154 Clarify the difference between dev and optional dependencies in `package.json`
  package.json
Labels: internal

#1600 RD-3110 Enhance Deploy On modal to allow providing a suffix for new deployments
  app/translations/en.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/common/src/DeployBlueprintModal.tsx
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/deploymentsView/header/DeployOnModal.tsx
  widgets/deploymentsView/README.md
Labels: feature

#1598 RD-3140 Update Blueprint Marketplace modal to use Table view by default
  .size-limit
  app/translations/en.json
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
Labels: feature

#1603 RD-3099 Fix uploading blueprint that contains directories recognized as files by `decompress` library
  backend/handler/ArchiveHelper.ts
  backend/test/handlers/ArchiveHelper.test.ts
  backend/test/handlers/fixtures/ArchiveHelper.test.zip
Labels: bug-fix

#1606 RD-3099 Fix uploading blueprint that contains directories recognized as files by `decompress` library [6.2]
  backend/handler/ArchiveHelper.js
Labels: bug-fix

#1604 RD-3100 Replaced error message popup with a modal
  app/translations/en.json
  test/cypress/fixtures/events/events.json
  test/cypress/integration/widgets/events_spec.ts
  widgets/events/README.md
  widgets/events/src/DetailsIcon.tsx
  widgets/events/src/DetailsModal.tsx
  widgets/events/src/ErrorCausesIcon.tsx
  widgets/events/src/ErrorCausesModal.tsx
  widgets/events/src/EventsTable.tsx
Labels: enhancement, bug-fix

#1609 RD-3174 Reset state of Getting Started modal on open
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/utils/hooks/index.ts
  app/utils/hooks/useOpenProp.ts
Labels: bug-fix

#1610 RD-3174 Reset state of Getting Started modal on open [6.2]
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/utils/hooks/index.ts
  app/utils/hooks/useOpenProp.ts
Labels: bug-fix

#1612 RD-3175 Added modal close confirmation dialog
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: enhancement

#1615 RD-3181 Clear step errors when going to previous step
  app/components/GettingStartedModal/GettingStartedModal.tsx
Labels: bug-fix

#1614 RD-3069 Update documentation for Blueprint flow changes (#1613)
  widgets/blueprintCatalog/README.md
  widgets/blueprints/README.md
Labels: internal

#1616 RD-3179 Update tabs in Blueprint Marketplace modal
  app/translations/en.json
  widgets/blueprints/src/widget.tsx
  widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
Labels: feature

#1608 RD-3173 Convert custom Cypress commands to always return value
  test/cypress/support/blueprints.ts
  test/cypress/support/commands.ts
  test/cypress/support/deployments.ts
  test/cypress/support/editMode.ts
  test/cypress/support/executions.ts
  test/cypress/support/filters.ts
  test/cypress/support/plugins.ts
  test/cypress/support/secrets.ts
  test/cypress/support/sites.ts
  test/cypress/support/snapshots.ts
  test/cypress/support/templates.ts
  test/cypress/support/users.ts
  test/cypress/support/widgets.ts
Labels: internal

#1618 RD-3179 Update tabs in Blueprint Marketplace modal [6.2]
  app/translations/en.json
  widgets/blueprints/src/widget.tsx
  widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
Labels: feature

#1620 RD-2061 Disable no-namespace ESLint rule in widgets
  widgets/.eslintrc.json
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/deploymentsView/index.ts
  widgets/common/src/filters/index.ts
  widgets/common/src/labels/index.ts
Labels: internal

#1621 RD-3106 Update documentation links after 6.2 release
  app/translations/en.json
  templates/pages/adminDash.json
Labels: internal

#1626 RD-2993 Added sample test for widgets component
  app/app.tsx
  test/cypress/.babelrc.json
  test/cypress/components/app/GettingStartedModal_spec.tsx
  test/cypress/components/initAppContext.ts
  test/cypress/components/widgets/filters/RulesForm_spec.tsx
  test/cypress/plugins/index.ts
Labels: internal
