Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2021-11, with the labels that each got.

#1656 RD-3242 Added read-only support for menu icons
  app/actions/page.ts
  app/actions/pageMenu.ts
  app/components/sidebar/PagesList.tsx
  app/reducers/pageReducer.ts
Labels: feature

#1657 RD-3419 Added icons for pages and page groups used by built-in templates
  templates/page-groups/deployments.json
  templates/page-groups/resources.json
  templates/page-groups/systemSetup.json
  templates/pages/adminDash.json
  templates/pages/agents.json
  templates/pages/blueprints.json
  templates/pages/environments.json
  templates/pages/executions.json
  templates/pages/filters.json
  templates/pages/groups.json
  templates/pages/health.json
  templates/pages/logs.json
  templates/pages/plugins.json
  templates/pages/secrets.json
  templates/pages/services.json
  templates/pages/sites.json
  templates/pages/snapshots.json
  templates/pages/tenants.json
  templates/pages/users.json
Labels: feature

#1655 RD-1229 Update project to use Node v14
  .nvmrc
  README.md
  backend/package-lock.json
  backend/package.json
  backend/patches/pg+7.18.2.patch
  backend/patches/pg+8.7.1.patch
  jenkins/Jenkinsfile
  jenkins/build-pod.yaml
  packaging/cloudify-stage.spec
Labels: internal

#1659 RD-3419 Fixed system test
  test/cypress/integration/flows/user_spec.ts
Labels: bug-fix

#1658 RD-3242 Added edit mode support for page menu items icons
  .size-limit
  app/actions/pageMenu.ts
  app/actions/types.ts
  app/components/shared/SemanticIconDropdown.tsx
  app/components/shared/index.ts
  app/components/sidebar/IconSelection.tsx
  app/components/sidebar/PagesList.tsx
  app/reducers/pageReducer.ts
  test/cypress/components/app/PagesList_spec.tsx
  test/cypress/fixtures/pages/pages_with_groups.json
  widgets/buttonLink/src/widget.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/serviceButton/src/widget.tsx
Labels: feature

#1662 RD-3190 Moved tenant selection from top to side bar
  app/components/IconSelection.tsx
  app/components/Tenants.tsx
  app/components/layout/Header.tsx
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SideBarItem.tsx
  app/components/sidebar/SortableMenuItem.tsx
  app/components/sidebar/SystemMenu.tsx
  app/components/sidebar/TenantSelection.tsx
  app/containers/Tenants.ts
  app/translations/en.json
  test/cypress/components/app/sidebar/PagesList_spec.tsx
  test/cypress/components/app/sidebar/TenantSelection_spec.tsx
  test/cypress/components/utils.tsx
  test/cypress/integration/edit_mode_spec.ts
  test/cypress/integration/templateManagement/page_groups_spec.ts
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/support/commands.ts
  test/jest/components/Tenants.test.tsx
Labels: feature

#1654 RD-2807 Tests for number of blueprints widget
  test/cypress/integration/widgets/agents_spec.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprint_num_spec.ts
  test/cypress/integration/widgets/deployment_num_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprintNum/src/widget.tsx
Labels: internal

#1648 RD-3389 Fix hidden names of widgets
  app/components/AddWidgetModal.tsx
  app/styles/style.scss
Labels: bug-fix

#1663 RD-3330 Fix negative number in an input
  widgets/common/src/InputsUtils.tsx
Labels: bug-fix

#1672 RD-3589 Change node-sass to sass (Fix cloudify-stage installation fail on M1 computer)
  package-lock.json
  package.json
  widgets/common/src/deploymentsView/styles.scss
Labels: internal

#1667 RD-3442 Moved help menu from top bar to side bar
  app/components/AboutModal.tsx
  app/components/Help.tsx
  app/components/banner/Banner.tsx
  app/components/layout/Header.tsx
  app/components/license/CurrentLicense.tsx
  app/components/sidebar/HelpMenu.tsx
  app/components/sidebar/IconSelection.tsx
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SideBarItem.tsx
  app/components/sidebar/SideBarItemIcon.tsx
  app/components/sidebar/SortableMenuItem.tsx
  app/components/sidebar/SystemMenu.tsx
  app/components/sidebar/TenantSelection.tsx
  app/components/templateManagement/pages/PageManagement.tsx
  app/containers/AboutModal.ts
  app/containers/Help.ts
  app/translations/en.json
  package-lock.json
  test/cypress/components/app/sidebar/Help_spec.tsx
  test/cypress/components/utils.tsx
  test/cypress/integration/community_spec.ts
  test/cypress/integration/license_spec.ts
  test/jest/components/Help.test.tsx
Labels: feature

#1665 RD-3216 Hide DrilldownButtons instead of disabling them
  .size-limit
  package-lock.json
  package.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/SubdeploymentDrilldownButton.tsx
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/common.ts
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/index.tsx
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/subdeployments-result.ts
  widgets/common/src/deploymentsView/detailsPane/header.scss
  widgets/common/src/deploymentsView/detailsPane/header.tsx
  widgets/common/src/deploymentsView/detailsPane/widgets.tsx
Labels: feature

#1668 RD-3496 Update version of cloudify-components to 2.9.2
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  widgets/deploymentsView/README.md
Labels: internal

#1677 RD-3442 Moved health indicator from top to side bar
  app/components/Manager.tsx
  app/components/layout/Header.tsx
  app/components/shared/cluster/ClusterServicesOverview.tsx
  app/components/sidebar/HealthIndicator.tsx
  app/components/sidebar/HelpMenu.tsx
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBarDropdownItem.tsx
  app/components/sidebar/SideBarItem.tsx
  app/components/sidebar/SideBarItemIcon.tsx
  app/components/sidebar/SystemMenu.tsx
  app/components/sidebar/TenantSelection.tsx
  app/containers/Manager.ts
  app/containers/status/SystemStatusHeader.ts
  app/translations/en.json
  test/cypress/integration/cluster_status_spec.ts
  test/cypress/integration/widgets/button_link_spec.ts
  test/cypress/integration/widgets/events_spec.ts
  test/cypress/integration/widgets/executions_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/integration/widgets/nodes_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#1679 RD-3442 Moved user menu from top to side bar
  app/actions/managers.ts
  app/components/Users.tsx
  app/components/layout/Header.tsx
  app/components/shared/PasswordModal.tsx
  app/components/sidebar/HealthIndicator.tsx
  app/components/sidebar/HelpMenu.tsx
  app/components/sidebar/IconSelection.tsx
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SideBarDropdownItem.tsx
  app/components/sidebar/SideBarItem.tsx
  app/components/sidebar/SideBarItemIcon.tsx
  app/components/sidebar/SortableMenuItem.tsx
  app/components/sidebar/SystemMenu.tsx
  app/components/sidebar/TenantSelection.tsx
  app/components/sidebar/UserInitialsIcon.tsx
  app/components/sidebar/UserMenu.tsx
  app/containers/Users.ts
  app/reducers/managerReducer.ts
  test/cypress/components/app/GettingStartedModal_spec.tsx
  test/cypress/components/app/sidebar/TenantSelection_spec.tsx
  test/cypress/components/app/sidebar/UserMenu_spec.tsx
  test/cypress/components/utils.tsx
  test/cypress/integration/change_password_spec.ts
  test/cypress/integration/cluster_status_spec.ts
  test/cypress/integration/community_spec.ts
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/license_spec.ts
  test/cypress/integration/templateManagement/page_groups_spec.ts
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/templateManagement/pages_preview_spec.ts
  test/cypress/integration/templateManagement/pages_spec.ts
  test/cypress/integration/templateManagement/template_management_spec.ts
  test/cypress/integration/templateManagement/templates_spec.ts
  test/cypress/integration/user_menu_spec.ts
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/deployment_info_spec.ts
  test/cypress/integration/widgets/nodes_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/editMode.ts
  test/cypress/support/templates.ts
  test/jest/components/Users.test.tsx
Labels: feature

#1683 RD-3442 Added automatic sidebar groups collapsing
  app/components/sidebar/HelpMenu.tsx
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SystemMenu.tsx
  app/components/sidebar/UserMenu.tsx
  test/cypress/components/app/sidebar/Help_spec.tsx
  test/cypress/components/app/sidebar/PagesList_spec.tsx
  test/cypress/components/app/sidebar/SideBar_spec.tsx
  test/cypress/components/app/sidebar/UserMenu_spec.tsx
  test/cypress/support/editMode.ts
Labels: feature

#1676 RD-3554, RD-3549, RD-3492 - Modified dashboard layout
  package-lock.json
  templates/pages/adminDash.json
  test/cypress/integration/widgets/sites_map_spec.ts
Labels: feature

#1684 RD-3584 Modified the layout of the dashboard
  templates/pages/adminDash.json
Labels: feature

#1682 RD-3477 Disabled LDAP functionality in the UserGroups widget, when LDAP is not being enabled
  app/actions/managers.ts
  app/actions/types.ts
  app/reducers/managerReducer.ts
  app/translations/en.json
  test/cypress/integration/widgets/user_groups_spec.ts
  widgets/userGroups/README.md
  widgets/userGroups/src/CreateModal.tsx
  widgets/userGroups/src/GroupDetails.tsx
  widgets/userGroups/src/MenuAction.tsx
  widgets/userGroups/src/TenantsModal.tsx
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userGroups/src/UsersModal.tsx
  widgets/userGroups/src/actions.ts
  widgets/userGroups/src/consts.ts
  widgets/userGroups/src/widget.tsx
Labels: feature, internal
