Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-10, with the labels that each got.

#2180 RD-5603 Add port type
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#2196 RD-5947 Back to `getVersion` & `getPreRealease` functions
  jenkins/Jenkinsfile
Labels: bug-fix

#2198 RD-6005: Adjustments for using multipart form data
  app/utils/External.ts
  backend/package-lock.json
  test/cypress/support/blueprints.ts
  widgets/common/src/blueprints/BlueprintActions.ts
Labels: internal

#2199 RD-6069 Audit fails on recharts
  .size-limit
  jest.config.js
  package-lock.json
  package.json
Labels: bug-fix, internal

#2197 RD-5450 new design of Blueprint marketplace
  app/translations/en.json
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/widget.css
Labels: feature

#2203 RD-5772 Migrate highAvailability (Cluster Status) widget to TypeScript
  widgets/highAvailability/src/widget.tsx
Labels: internal

#2205 RD-5918 RD-6070 RD-6071 Improve waiting for execution to be finished and skip failing tests
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/executions.ts
Labels: internal

#2204 RD-6016 Refactor GET /templates/select endpoint
  app/actions/pageMenu.ts
  backend/handler/templates/TemplatesHandler.ts
  backend/routes/Templates.ts
  backend/routes/Templates.types.ts
  backend/test/handlers/templates/TemplatesHandler.test.ts
  test/cypress/integration/login_spec.ts
Labels: internal

#2207 RD-5266 Add check for Deploy blueprint modal existence after successful blueprint upload in blueprint_terraform_spec
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: internal

#2210 RD-6090 Bump `chokidar` package to latest v3 to fix security issue
  package-lock.json
  package.json
Labels: dependencies, internal

#2209 RD-6089 Bump `elkjs` package version
  backend/package-lock.json
  backend/package.json
  backend/test/widgets/executions/references/root-level-task_elk-graph.json
Labels: dependencies, internal

#2208 RD-5715: Updated cloudify-ui-components library
  app/components/templateManagement/pages/Pages.tsx
  package-lock.json
  package.json
  test/cypress/support/blueprints.ts
  widgets/blueprints/src/types.ts
  widgets/common/src/Consts.ts
  widgets/common/src/blueprints/UploadBlueprintModal.tsx
  widgets/common/src/types.ts
  widgets/plugins/src/PluginsTable.tsx
Labels: internal

#2211 RD-6092 Fix package-lock.json
  package-lock.json
Labels: bug-fix, internal

#2206 RD-6088 Fix timeout placement in user_spec
  test/cypress/integration/flows/user_spec.ts
Labels: bug-fix, internal

#2141 RD-5595 Show message for binary files in blueprint sources
  app/translations/en.json
  app/utils/External.ts
  backend/handler/SourceHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/BlueprintUserData.ts
  backend/routes/SourceBrowser.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
Labels: bug-fix

#2201 RD-5956 Use new `cloudify-ui-common-*` packages
  .eslintrc.json
  .prettierrc.js
  app/app.tsx
  app/components/AddWidgetModal.tsx
  app/components/fonts.ts
  app/components/shared/ProductLogo.tsx
  app/styles/style.scss
  app/utils/shared/JsonUtils.ts
  backend/db/Connection.ts
  backend/db/models/BlueprintAdditionsModel.ts
  backend/db/models/BlueprintUserDataModel.ts
  backend/db/models/ResourcesModel.ts
  backend/db/models/UserAppsModel.ts
  backend/db/models/WidgetBackendsModel.ts
  backend/handler/LoggerHandler.ts
  backend/middleware/checkIfFileUploadedMiddleware.ts
  backend/migration.ts
  backend/migrations/common/types.ts
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  package-lock.json
  package.json
  scripts/uploadPackage.sh
  test/cypress/plugins/index.ts
  test/cypress/support/asserts.ts
  test/cypress/support/blueprints.ts
  test/cypress/support/commands.ts
  test/cypress/support/deployments.ts
  test/cypress/support/editMode.ts
  test/cypress/support/executions.ts
  test/cypress/support/filters.ts
  test/cypress/support/getting_started.ts
  test/cypress/support/labels.ts
  test/cypress/support/plugins.ts
  test/cypress/support/resource_commons.ts
  test/cypress/support/secrets.ts
  test/cypress/support/sites.ts
  test/cypress/support/snapshots.ts
  test/cypress/support/templates.ts
  test/cypress/support/users.ts
  test/cypress/support/widgets.ts
  test/jest/widgets/topology/NodeStatusService.test.ts
  tsconfig.base.json
  webpack.config.js
  widgets/common/src/components/parameter/ParameterValue.tsx
  widgets/common/src/deploymentsView/styles.scss
  widgets/common/src/utils/EventUtils.ts
  widgets/nodes/src/NodesTable.tsx
  widgets/topology/src/DataProcessor.ts
  widgets/topology/src/NodeStatusService.ts
Labels: internal

#2214 RD-6108 Fix backend dependencies
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
  package.json
Labels: bug-fix

#2191 RD-5604 Add boolean type
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/components/GettingStartedModal/steps/SecretsStep.tsx
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#2218 RD-5607 Add an option to customize the first screen messaging
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/createEnvironmentsGroups.tsx
  app/components/GettingStartedModal/installation/tasks.ts
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/components/GettingStartedModal/schema/gettingStarted.schema.json
  app/components/GettingStartedModal/steps/EnvironmentsStep/EnvironmentsStep.tsx
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
  app/components/GettingStartedModal/steps/WelcomeStep.tsx
  app/translations/en.json
Labels: feature

#2220 RD-5607 Part 2
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/steps/WelcomeStep.tsx
Labels: feature

#2192 RD-4946 Add User Invite modal to User Management widget
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  app/components/ContactDetailsModal/ContactDetailsModalContent/validationRegexpPatterns.ts
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/translations/en.json
  app/utils/consts.ts
  devServer.ts
  test/cypress/integration/flows/admin_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
  widgets/common/src/Consts.ts
  widgets/userManagement/src/InviteModal.tsx
  widgets/userManagement/src/UsersTable.tsx
  widgets/userManagement/src/authServiceActions.ts
Labels: feature

#2219 RD-3002 Replace `scanjs`
  .eslintrc.json
  app/actions/managers.ts
  app/actions/pageMenu.ts
  app/components/ExternalRedirect.tsx
  app/components/LoginPage.tsx
  app/utils/stageUtils.ts
  backend/routes/Auth.ts
  backend/serverSettings.ts
  package-lock.json
  package.json
  test/cypress/support/commands.ts
  test/cypress/support/sites.ts
Labels: internal

#2217 RD-5777 Migrate Node Statistics widget
  app/translations/en.json
  widgets/common/src/nodes/NodeInstancesConsts.ts
  widgets/nodesStats/src/widget.tsx
Labels: internal

#2212 RD-2254 Disable secrets and show notification if secrets already exist in Getting Started Modal
  app/components/GettingStartedModal/steps/SecretsStep.tsx
  app/components/GettingStartedModal/steps/SecretsStep/SecretsExistMessage.tsx
  app/components/GettingStartedModal/steps/SecretsStep/SecretsStep.tsx
  app/components/GettingStartedModal/steps/SecretsStep/index.ts
  app/components/GettingStartedModal/steps/SecretsStep/useAllSecretsExist.ts
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#2224 RD-6130: Updated cloudify-ui-components library
  app/components/WidgetDynamicContent/WidgetDynamicContent.tsx
  app/components/basic/index.ts
  app/components/license/UploadLicense.tsx
  package-lock.json
  package.json
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/blueprintCatalog/src/UploadingMessage/UploadingMessage.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/index.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/executeWorkflow/types.ts
  widgets/common/src/types.ts
Labels: internal

#2229 RD-5755 Part 1: convert clusterServiceStatusEnum to ClusterServiceStatus
  app/components/shared/cluster/ClusterServicesOverview.tsx
  app/components/shared/cluster/ClusterStatusIcon.tsx
  app/components/shared/cluster/consts.ts
  app/components/shared/cluster/types.ts
  app/components/sidebar/HealthIndicator.tsx
  app/components/status/SystemServicesStatus.tsx
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
Labels: internal

#2231 RD-3132 RD-3133 Reuse common backend tsc and eslint configs
  .eslintrc.json
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  package-lock.json
  package.json
Labels: internal

#2227 RD-3486: Styled input component
  .size-limit
  semantic-ui/site/collections/form.variables.less
  semantic-ui/site/elements/button.overrides.less
  semantic-ui/site/elements/input.overrides.less
  semantic-ui/site/elements/input.variables.less
  semantic-ui/site/elements/label.variables.less
  semantic-ui/site/globals/site.variables.less
Labels: feature

#2228 RD-3488 Styled search input component
  semantic-ui/site/elements/button.overrides.less
  semantic-ui/site/elements/button.variables.less
  semantic-ui/site/elements/input.overrides.less
  semantic-ui/site/elements/input.variables.less
  semantic-ui/site/modules/checkbox.overrides.less
Labels: feature

#2232 RD-6095 adjustment number of columns in marketplace
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
Labels: feature

#2236 RD-6100 Remove Creation and Update dates from marketplace widget
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  widgets/blueprintCatalog/src/widget.tsx
Labels: internal

#2233 RD-5591 Migrate Redux store to TypeScript - part 2 (app, contexts, formErrors, plugins, userApp)
  app/actions/app.ts
  app/actions/appState.ts
  app/actions/context.ts
  app/actions/drilldownContext.ts
  app/actions/formErrors.ts
  app/actions/initialPageLoad.ts
  app/actions/manager/auth.ts
  app/actions/manager/clusterStatus.ts
  app/actions/manager/maintenance.ts
  app/actions/manager/tenants.ts
  app/actions/plugins.ts
  app/actions/types.ts
  app/actions/userApp.ts
  app/actions/userAppCommon.ts
  app/components/Home.tsx
  app/components/sidebar/TenantSelection.tsx
  app/components/sidebar/UserMenu.tsx
  app/components/templateManagement/templates/CreateTemplateModal.tsx
  app/containers/layout/Layout.ts
  app/reducers/appReducer.ts
  app/reducers/contextReducer.ts
  app/reducers/drilldownContextReducer.ts
  app/reducers/formErrorsReducer.ts
  app/reducers/index.ts
  app/reducers/managerReducer/tenantsReducer.ts
  app/reducers/pageReducer.ts
  app/reducers/pluginsReducer.ts
  app/utils/Interceptor.ts
  app/utils/UserAppDataAutoSaver.ts
  test/cypress/components/app/sidebar/TenantSelection_spec.tsx
  test/jest/reducers/managerReducer/tenantsReducer.test.ts
  test/jest/reducers/pagesReducer.test.ts
  test/jest/utils/Manager.test.ts
Labels: bug-fix, internal
