Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-04, with the labels that each got.

#1903 RD-3672 Edit Mode spec adjustments
  test/cypress/integration/edit_mode_spec.ts
Labels: internal

#1898 RD-1104 Refactor `manager` reducer
  app/components/license/CurrentLicense.tsx
  app/components/sidebar/HealthIndicator.tsx
  app/components/sidebar/SideBarHeader.tsx
  app/components/sidebar/UserMenu.tsx
  app/reducers/licenseReducer.ts
  app/reducers/managerReducer/clusterStatusReducer.ts
  app/reducers/managerReducer/index.ts
  app/reducers/managerReducer/licenseReducer.ts
  app/reducers/managerReducer/managerReducer.ts
  app/reducers/managerReducer/tenantsReducer.ts
  app/utils/StageAPI.ts
  app/utils/auth.ts
  app/utils/consts.ts
  app/utils/stageUtils.ts
  backend/handler/AuthHandler.ts
  backend/routes/Auth.types.ts
  backend/types.ts
  test/jest/reducers/licenseReducer.test.ts
  test/jest/reducers/managerReducer.test.ts
  test/jest/reducers/tenantsReducer.test.ts
  test/jest/utils/ManagerStatePersister.test.ts
Labels: internal

#1905 RD-4666 Fix error 500 in Topology widget & make Topology widget spec more robust
  backend/routes/Plugins.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/commands.ts
Labels: bug-fix, internal

#1904 RD-1104 Migrate `managerReducer` tests to TypeScript
  app/actions/managers.ts
  app/actions/tenants.ts
  package-lock.json
  package.json
  test/jest/reducers/managerReducer/licenseReducer.test.ts
  test/jest/reducers/managerReducer/managerReducer.test.ts
  test/jest/reducers/managerReducer/tenantsReducer.test.ts
Labels: internal

#1908 RD 273 Adding upload RPM build artifact to s3 bucket
  jenkins/Jenkinsfile
  jenkins/build-pod.yaml
Labels: feature

#1895 RD-4141, RD-4138, RD-4141, RD-4146: secret_key and capabilities_value as an input for workflow parameters
  .gitignore
  app/translations/en.json
  test/cypress/fixtures/blueprints/capabilities.zip
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployment_inputs_spec.ts
  widgets/common/src/inputs/utils/getInputField.tsx
Labels: feature

#1911 RD-4248 Cypress tests optimisation - using .mockLogin() instead of .login() wherever it's possible
  test/cypress/fixtures/community/login.json
  test/cypress/integration/community_spec.ts
  test/cypress/integration/widgets/blueprint_num_spec.ts
  test/cypress/integration/widgets/sites_map_spec.ts
Labels: internal

#1912 Providing the bug fix for the RD-273
  jenkins/Jenkinsfile
Labels: bug-fix

#1906 RD-3918 Turn on HttpOnly flag on token cookie
  app/actions/managers.ts
  app/app.tsx
  app/components/AuthRoutes.tsx
  app/components/Routes.tsx
  app/components/SamlLogin.tsx
  app/components/shared/PasswordModal.tsx
  app/components/sidebar/UserInitialsIcon.tsx
  app/components/sidebar/UserMenu.tsx
  app/containers/LoginPage.ts
  app/containers/Routes.ts
  app/reducers/managerReducer/authReducer.ts
  app/reducers/managerReducer/emptyState.ts
  app/reducers/managerReducer/index.ts
  app/reducers/managerReducer/managerReducer.ts
  app/reducers/managerReducer/tenantsReducer.ts
  app/utils/Manager.ts
  app/utils/ManagerStatePersister.ts
  app/utils/UserAppDataAutoSaver.ts
  app/utils/auth.ts
  backend/routes/Auth.ts
  backend/test/routes/Auth.test.ts
  package-lock.json
  package.json
  test/cypress/components/app/sidebar/SideBar_spec.tsx
  test/cypress/components/app/sidebar/UserMenu_spec.tsx
  test/cypress/integration/auth_spec.ts
  test/cypress/integration/change_password_spec.ts
  test/cypress/integration/community_spec.ts
  test/cypress/integration/getting_started_spec.ts
  test/cypress/integration/login_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/integration/user_menu_spec.ts
  test/cypress/integration/widgets/user_groups_spec.ts
  test/cypress/support/commands.ts
  test/cypress/tsconfig.json
  test/jest/components/GridItem.test.tsx
  test/jest/reducers/managerReducer/managerReducer.test.ts
  test/jest/utils/Auth.test.ts
  test/jest/utils/Manager.test.ts
Labels: bug-fix

#1913 RD-1609 Refactor exposing items from `Stage.Common`
  app/utils/StageAPI.ts
  app/utils/widgetDefinitionsLoader.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/support/filters.ts
  widgets/blueprints/src/types.ts
  widgets/common/src/Consts.ts
  widgets/common/src/actions/index.ts
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/blueprints/BlueprintActions.ts
  widgets/common/src/blueprints/UploadBlueprintModal.tsx
  widgets/common/src/blueprints/index.ts
  widgets/common/src/components/index.ts
  widgets/common/src/deployModal/DeployBlueprintModal.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/deployments/DeploymentActions.ts
  widgets/common/src/deployments/DeploymentActionsModals.tsx
  widgets/common/src/deployments/index.ts
  widgets/common/src/deploymentsView/DeploymentsView.tsx
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/SubdeploymentDrilldownButton.tsx
  widgets/common/src/deploymentsView/index.ts
  widgets/common/src/deploymentsView/map/DeploymentsMap.tsx
  widgets/common/src/deploymentsView/map/common.ts
  widgets/common/src/deploymentsView/map/container.tsx
  widgets/common/src/deploymentsView/map/marker/single-deployment-site.tsx
  widgets/common/src/executeWorkflow/index.ts
  widgets/common/src/executions/index.ts
  widgets/common/src/filters/index.ts
  widgets/common/src/index.ts
  widgets/common/src/inputs/index.ts
  widgets/common/src/labels/index.ts
  widgets/common/src/map/DefaultTileLayer.tsx
  widgets/common/src/map/MapsActions.ts
  widgets/common/src/map/index.ts
  widgets/common/src/map/options.ts
  widgets/common/src/nodes/NodeInstancesConsts.ts
  widgets/common/src/plugins/UploadPluginModal.tsx
  widgets/common/src/plugins/index.ts
  widgets/common/src/roles/index.ts
  widgets/common/src/roles/utils.ts
  widgets/common/src/secrets/SecretActions.ts
  widgets/common/src/secrets/SecretsModal.tsx
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformModalTableAccordion.tsx
  widgets/common/src/terraformModal/TerraformVariableValueInput.tsx
  widgets/common/src/utils/EventUtils.ts
  widgets/deploymentsView/src/widget.tsx
  widgets/deploymentsViewDrilledDown/src/widget.tsx
  widgets/labels/src/DeleteConfirmModal.tsx
  widgets/serviceButton/src/ServiceButton.tsx
  widgets/sitesMap/src/SitesMap.tsx
  widgets/sitesMap/src/types.ts
  widgets/sitesMap/src/widget.tsx
Labels: internal

#1917 RD-1609 Revert import type
  widgets/common/src/deploymentsView/index.ts
  widgets/common/src/filters/index.ts
Labels: bug-fix

#1907 RD-3917: Added support for using terraform module from git files
  app/translations/en.json
  backend/package-lock.json
  backend/package.json
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/README.md
  widgets/common/src/terraformModal/TerraformActions.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#1915 RD-4402: Inputs with default values in terraform blueprint upload
  app/components/shared/DynamicTable.tsx
  app/translations/en.json
  backend/routes/Terraform.types.ts
  backend/templates/terraform/inputs.ejs
  backend/templates/terraform/variables.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformVariableValueInput.tsx
Labels: feature

#1923 RD-4114: fixed displaying 'undefined' (deployment_id)
  test/README.md
  widgets/common/src/inputs/utils/getInputField.tsx
Labels: bug-fix

#1925 RD-4731: Resolve archiver and ejs vulnerabilities
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#1924 RD-4720 Refactor input component factory functions
  widgets/common/src/components/DynamicDropdown.tsx
  widgets/common/src/deployModal/DeploymentInputs.tsx
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/InputFields.tsx
  widgets/common/src/inputs/InputHelp.tsx
  widgets/common/src/inputs/consts.ts
  widgets/common/src/inputs/fields/BlueprintIdInputField.tsx
  widgets/common/src/inputs/fields/BooleanInputField.tsx
  widgets/common/src/inputs/fields/CapabilityValueInputField.tsx
  widgets/common/src/inputs/fields/DeploymentIdInputField.tsx
  widgets/common/src/inputs/fields/GenericInputField.tsx
  widgets/common/src/inputs/fields/NumberInputField.tsx
  widgets/common/src/inputs/fields/RevertToDefaultIcon.tsx
  widgets/common/src/inputs/fields/SecretKeyInputField.tsx
  widgets/common/src/inputs/fields/StringInputField.tsx
  widgets/common/src/inputs/fields/TextareaInputField.tsx
  widgets/common/src/inputs/fields/ValueListInputField.tsx
  widgets/common/src/inputs/fields/types.ts
  widgets/common/src/inputs/index.ts
  widgets/common/src/inputs/types.ts
  widgets/common/src/inputs/utils/getInputField.tsx
  widgets/common/src/inputs/utils/getInputFieldInitialValue.ts
  widgets/common/src/inputs/utils/getInputFields.tsx
  widgets/common/src/inputs/utils/getInputsMap.ts
  widgets/common/src/inputs/utils/getTemplateForDataType.ts
  widgets/common/src/inputs/utils/index.ts
  widgets/deploymentWizardButtons/src/steps/InputsStep.tsx
Labels: internal

#1930 RD-3981: Terraform Module - authentication, auto focus when required
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#1916 RD-3735 Show deployment name in Blueprint Deployments
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/deployments/src/DeploymentsSegment.tsx
  widgets/deployments/src/DeploymentsTable.tsx
Labels: bug-fix

#1929 RD-4288: Change the way the coverage is calculated
  jest.config.js
  package.json
  test/README.md
Labels: internal

#1897 RD-2810 Show deployment name in translations
  app/translations/en.json
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/labels/LabelsModal.tsx
Labels: bug-fix

#1928 RD-4423: Introduced Tokens widget
  .size-limit
  app/translations/en.json
  backend/test/handlers/WidgetHandler.test.ts
  package-lock.json
  package.json
  scripts/readmesConfig.json
  test/cypress/fixtures/community/manager.json
  test/cypress/integration/widgets/tokens_spec.ts
  widgets/tokens/README.md
  widgets/tokens/src/RemoveTokenButton.tsx
  widgets/tokens/src/TextEllipsis.tsx
  widgets/tokens/src/TokensTable.consts.ts
  widgets/tokens/src/TokensTable.tsx
  widgets/tokens/src/TokensTableHeader/CreateTokenModal.tsx
  widgets/tokens/src/TokensTableHeader/CreateTokenModal.types.ts
  widgets/tokens/src/TokensTableHeader/CreatedToken.tsx
  widgets/tokens/src/TokensTableHeader/TokensTableHeader.tsx
  widgets/tokens/src/TokensTableHeader/index.ts
  widgets/tokens/src/types.ts
  widgets/tokens/src/widget.consts.ts
  widgets/tokens/src/widget.tsx
  widgets/tokens/src/widget.types.ts
  widgets/tokens/widget.png
Labels: feature

#1931 RD-3879 Change Deployment Button to Environment/Service Button
  app/translations/en.json
  templates/pages/environments.json
  templates/pages/services.json
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/deploymentButton/README.md
  widgets/deploymentButton/src/DeploymentButton.tsx
  widgets/deploymentButton/src/widget.tsx
Labels: bug-fix

#1936 RD-4155: Workflow parameter - node id
  app/translations/en.json
  package-lock.json
  package.json
  widgets/common/src/filters/resourceTypeContext.ts
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/NodeIdInputField.tsx
Labels: feature

#1939 RD-4172, RD-4180, RD-4165: Workflow parameters - node_type, node_instance, scaling_group
  app/translations/en.json
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/NodeInstanceInputField.tsx
  widgets/common/src/inputs/fields/NodeTypeInputField.tsx
  widgets/common/src/inputs/fields/ScalingGroupInputField.tsx
Labels: feature

#1937 RD-4581: Display Tenant name in breadcrumbs
  app/components/Breadcrumbs.tsx
  app/components/Page.tsx
  app/components/templateManagement/TemplateManagement.tsx
  app/components/templateManagement/pages/PageManagement.tsx
  test/cypress/integration/page_spec.ts
Labels: feature

#1938 RD-4527: Modify GettingStartedModal redirections
  app/actions/auth.ts
  app/actions/managers.ts
  app/actions/userApp.ts
  app/components/AboutModal.tsx
  app/components/AuthRoutes.tsx
  app/components/ErrorPage.tsx
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/Home.tsx
  app/components/LicenseLabel.tsx
  app/components/LinkToLogin.tsx
  app/components/LogoPage.tsx
  app/components/NotFound.tsx
  app/components/Routes.tsx
  app/components/banner/Banner.tsx
  app/components/layout/Layout.tsx
  app/components/sidebar/SideBarHeader.tsx
  app/components/sidebar/UserMenu.tsx
  app/containers/LicensePage.ts
  app/containers/maintenance/MaintenanceModePageMessage.ts
  app/utils/Interceptor.ts
  app/utils/consts.ts
  app/utils/shared/UrlUtils.ts
  test/cypress/integration/getting_started_spec.ts
  test/jest/components/Banner.test.tsx
Labels: feature, internal

#1944 RD-4423: Added ability to always copy the token value
  widgets/tokens/src/TokensTableHeader/CreatedToken.tsx
Labels: feature

#1941 RD-4651: Simplified condition for displaying the ShowFirstUserJourneyButtons component
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/deployments/src/widget.tsx
Labels: feature

#1945 RD-4651: Synchronized deployments widget documentation
  widgets/deployments/README.md
Labels: feature

#1942 RD-4172, RD-4180, RD-4165, RD-4155: Workflow parameters - node_type, node_instance, scaling_group - tests
  .gitignore
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: internal

#1949 RD-1982: Remove unnecessary page list reversing
  app/components/Breadcrumbs.tsx
  app/components/Page.tsx
Labels: internal

#1951 RD-4223, RD-4240, RD-4230, RD-4216: Input parameters, workflow parameters, list type
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/NodeIdInputField.tsx
  widgets/common/src/inputs/fields/ValueListInputField.tsx
  widgets/common/src/inputs/fields/types.ts
  widgets/common/src/inputs/types.ts
Labels: feature

#1952 RD-4824: Provided password type attribute to the url authentication field
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: bug-fix

#1953 RD-4825: Show token description as a part of DeleteModal content
  .size-limit
  app/translations/en.json
  widgets/tokens/src/RemoveTokenButton.tsx
  widgets/tokens/src/TokensTable.tsx
Labels: feature
