Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-01, with the labels that each got.

#1729 RD-3661 Added support for Terraform template URL authentication
  app/translations/en.json
  app/utils/External.ts
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformActions.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: feature

#1731 RD-3916 Fixed cy test
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: bug-fix

#1730 RD-3731: Hidded help popup when none of the help informations should …
  widgets/common/src/InputsUtils.tsx
Labels: bug-fix

#1732 RD-3341 Updated internal README file
  README.md
  doc/screenshot.png
Labels: internal

#1716 RD-3592 Refecting show_getting_started value inside the GettingStartedModal checkbox
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/useModalOpenState.ts
  test/cypress/integration/getting_started_spec.ts
  test/cypress/support/getting_started.ts
Labels: bug-fix

#1733 RD-3566 Add terraform button to the dashboard
  app/images/terraform_logo.png
  templates/pages/adminDash.json
Labels: feature

#1734 RD-3871: Added dashboard buttons to the blueprints page
  templates/pages/blueprints.json
Labels: feature

#1737 RD-3953 Synchronized documentation
  widgets/blueprints/README.md
Labels: bug-fix

#1736 RD-2866 Optimizing tenants fetching
  app/components/shared/widgets/Widget.tsx
  app/components/sidebar/TenantSelection.tsx
  app/translations/en.json
  test/cypress/integration/change_password_spec.ts
  test/cypress/integration/login_spec.ts
  test/cypress/integration/page_spec.ts
  test/cypress/integration/templateManagement/template_management_spec.ts
  test/cypress/integration/templateManagement/templates_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/integration/user_menu_spec.ts
  test/cypress/integration/widgets/agents_spec.ts
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/integration/widgets/user_groups_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
  test/cypress/support/app_commons.ts
  test/cypress/support/commands.ts
  test/cypress/support/users.ts
  widgets/snapshots/src/RestoreSnapshotModal.tsx
  widgets/tenants/src/CreateModal.tsx
  widgets/tenants/src/TenantsTable.tsx
  widgets/tenants/src/widget.tsx
Labels: feature

#1735 RD-3623 Change the DropDown Button value to Deploy on selecting Deploy
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/support/deployments.ts
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/deployModal/DeployModalActions.tsx
Labels: feature

#1740 RD-3974: Added delay to the response of the request
  test/cypress/integration/user_menu_spec.ts
Labels: bug-fix

#1744 RD-3828 Updated `secure` flag setting for auth token cookie
  backend/routes/Auth.ts
  backend/test/routes/Auth.test.ts
Labels: internal

#1742 RD-3825: Updated @cypress/code-coverage package to version 3.9.12
  package-lock.json
  package.json
Labels: dependencies

#1747 RD-3945 Fixed terraform form validation
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: bug-fix

#1745 RD-3944 Updated Terraform wrapper blueprint
  backend/routes/Terraform.ts
  backend/routes/Terraform.types.ts
  backend/templates/terraform/blueprint.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  widgets/blueprints/src/TerraformModal.tsx
  widgets/common/src/Consts.ts
  widgets/common/src/SecretActions.ts
Labels: feature

#1757 RD-3914 Change workflow ID used during deployment updates
  app/utils/shared/ExecutionUtils.ts
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix

#1755 RD-3974: Fix the intercepted request for tenants tests
  package-lock.json
  test/cypress/integration/user_menu_spec.ts
Labels: bug-fix

#1758 RD-3828 Change rules for setting Secure flag on token cookie
  backend/consts.ts
  backend/handler/AuthHandler.ts
  backend/routes/Auth.ts
  backend/routes/ServerProxy.ts
  backend/test/routes/Auth.test.ts
Labels: bug-fix

#1760 RD-2866: Fixed tests related to the TenantSelection component
  test/cypress/components/app/sidebar/TenantSelection_spec.tsx
Labels: bug-fix

#1759 RD-3978: Terraform Modal modifications
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: feature

#1764 RD-4040: Delayed tenants request response
  test/cypress/components/app/sidebar/TenantSelection_spec.tsx
Labels: bug-fix

#1763 RD-3737: Display task list on starting installation page appropriately
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
Labels: bug-fix

#1769 RD-4047 Fix deploy drop-down selection
  widgets/common/src/deployModal/DeployModalActions.tsx
Labels: bug-fix

#1762 RD-2809: Integration tests provided for the "pluginsNum" widget
  test/cypress/integration/widgets/blueprint_num_spec.ts
  test/cypress/integration/widgets/deployment_num_spec.ts
  test/cypress/integration/widgets/plugins_num_spec.ts
  test/cypress/support/asserts.ts
  test/cypress/support/commands.ts
  widgets/pluginsNum/src/widget.tsx
Labels: internal

#1761 RD-4032 Add token authentication to backend API routes
  backend/app.ts
  backend/auth/AuthMiddlewares.ts
  backend/routes/Applications.ts
  backend/routes/Auth.ts
  backend/routes/BlueprintAdditions.ts
  backend/routes/BlueprintUserData.ts
  backend/routes/ClientConfig.ts
  backend/routes/File.ts
  backend/routes/Filters.ts
  backend/routes/GitHub.ts
  backend/routes/Maps.ts
  backend/routes/Plugins.ts
  backend/routes/SourceBrowser.ts
  backend/routes/Templates.ts
  backend/routes/Terraform.ts
  backend/routes/UserApp.ts
  backend/routes/WidgetBackend.ts
  backend/routes/Widgets.ts
  backend/test/routes/File.test.ts
  backend/test/routes/WidgetBackend.test.ts
  backend/test/routes/fixtures/example.txt
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/executions.ts
Labels: bug-fix

#1767 RD-3979: Modified resourceLocation regexp
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/support/executions.ts
  test/cypress/support/resource_commons.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: bug-fix

#1772 RD-3972 Switch documentation and blueprint examples to 6.3
  app/translations/en.json
  scripts/readmesConfig.json
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: internal

#1775 RD-392 Switch blueprint examples to 6.3
  app/translations/en.json
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: internal

#1773 RD-4086 Fix displaying Blueprints and Plugins logos
  backend/app.ts
  backend/routes/Auth.ts
  backend/routes/BlueprintAdditions.ts
Labels: bug-fix

#1774 RD-4029: Updated blueprint imports
  backend/templates/terraform/blueprint.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
Labels: feature

#1776 RD-4086 Fix displaying Blueprints and Plugins logos [6.3]
  backend/app.ts
  backend/routes/Auth.ts
  backend/routes/BlueprintAdditions.ts
Labels: bug-fix

#1779 RD-3969: Synchronised documentation
  widgets/blueprints/README.md
Labels: internal

#1781 RD-4090 Update plugins catalog link to the latest version
  app/translations/en.json
  test/cypress/fixtures/widgets/splitViewWidget.tsx
  test/cypress/integration/getting_started_spec.ts
  test/cypress/integration/widgets/plugins_catalog_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#1784 RD-4090 Update plugins catalog link to the latest version [6.3]
  app/translations/en.json
  test/cypress/fixtures/widgets/splitViewWidget.tsx
  test/cypress/integration/getting_started_spec.ts
  test/cypress/integration/widgets/plugins_catalog_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#1771 RD-3944 Follow up to PR #1745
  backend/routes/Terraform.ts
  test/cypress/integration/templateManagement/page_groups_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/secrets.ts
Labels: internal

#1778 RD-3902 Use different 'getting started' modal configuration for initial screen and cloud setup button
  .size-limit
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/components/GettingStartedModal/schema/gettingStarted.schema.json
  app/components/GettingStartedModal/useCloudSetupUrlParam.ts
  app/components/GettingStartedModal/useModalOpenState.ts
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#1785 RD-3902 Use different 'getting started' modal configuration for initial screen and cloud setup button - #1778 merge to 6.3
  .size-limit
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/components/GettingStartedModal/schema/gettingStarted.schema.json
  app/components/GettingStartedModal/useCloudSetupUrlParam.ts
  app/components/GettingStartedModal/useModalOpenState.ts
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#1788 RD-4095 Fixed terraform topology rendering when dependency node is missing
  widgets/topology/src/Topology.tsx
Labels: bug-fix

#1790 RD-2504 Update widgets help description
  .size-limit
  widgets/blueprintActionButtons/README.md
  widgets/blueprintNum/README.md
  widgets/blueprints/README.md
  widgets/buttonLink/README.md
  widgets/deploymentNum/README.md
  widgets/deploymentsView/README.md
  widgets/executionNum/README.md
  widgets/executions/README.md
  widgets/nodes/README.md
  widgets/pluginsNum/README.md
  widgets/sitesMap/README.md
Labels: internal

#1787 RD-4097 Use `update` workflow ID for deployment updates
  app/utils/shared/ExecutionUtils.ts
Labels: internal

#1792 RD-2504 Update widgets help description [6.3]
  .size-limit
  widgets/blueprintActionButtons/README.md
  widgets/blueprintNum/README.md
  widgets/blueprints/README.md
  widgets/buttonLink/README.md
  widgets/deploymentNum/README.md
  widgets/deploymentsView/README.md
  widgets/executionNum/README.md
  widgets/executions/README.md
  widgets/nodes/README.md
  widgets/pluginsNum/README.md
  widgets/sitesMap/README.md
Labels: internal

#1793 RD-4097 Use update workflow ID for deployment updates [6.3]
  app/utils/shared/ExecutionUtils.ts
Labels: internal

#1791 RD-4095 Fixed terraform topology rendering when dependency node is missing - #1788 merge to 6.3
  widgets/topology/src/Topology.tsx
Labels: bug-fix

#1789 RD-4098: Removed unnecessary plugin upload
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: bug-fix
