Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-05, with the labels that each got.

#1957 RD-4223, RD-4240, RD-4230, RD-4216: Input parameters, workflow parame…
  app/utils/stageUtils.ts
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/BlueprintIdInputField.tsx
  widgets/common/src/inputs/fields/DeploymentIdInputField.tsx
Labels: feature, internal

#1946 RD-4650: Allow _ as a starting character for variables
  app/translations/en.json
  backend/routes/Terraform.types.ts
  backend/templates/terraform/blueprint.ejs
  backend/templates/terraform/inputs.ejs
  backend/templates/terraform/outputs.ejs
  backend/templates/terraform/variables.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformVariableValueInput.tsx
Labels: bug-fix, internal

#1962 RD-4906 Skip two test cases in Plugins Catalog spec
  test/cypress/integration/widgets/plugins_catalog_spec.ts
Labels: internal

#1965 RD-4913: Updated DSL version in blueprints used for input and workflo…
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/fixtures/blueprints/workflow_parameters.zip
Labels: bug-fix

#1963 RD-4149 Remove individual requests for templates/page groups/pages content on application bootstrap
  app/utils/templatesLoader.ts
  backend/handler/templates/PagesHandler.ts
  backend/handler/templates/TemplatesHandler.ts
  backend/handler/templates/consts.ts
  test/cypress/integration/templateManagement/page_groups_spec.ts
  test/cypress/integration/templateManagement/pages_preview_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/support/commands.ts
Labels: internal

#1967 RD-4149 Use `widget.css` import instead of `hasStyle` flag
  .size-limit
  widgets/blueprintCatalog/src/widget.css
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprintSources/src/widget.css
  widgets/blueprintSources/src/widget.tsx
  widgets/blueprints/src/widget.css
  widgets/blueprints/src/widget.tsx
  widgets/deploymentWizardButtons/src/widget.css
  widgets/deploymentWizardButtons/src/widget.tsx
  widgets/deployments/src/widget.css
  widgets/deployments/src/widget.tsx
  widgets/events/src/widget.css
  widgets/events/src/widget.tsx
  widgets/executions/src/widget.css
  widgets/executions/src/widget.tsx
  widgets/labels/src/widget.css
  widgets/labels/src/widget.tsx
  widgets/sites/src/widget.css
  widgets/sites/src/widget.tsx
  widgets/sitesMap/src/widget.css
  widgets/sitesMap/src/widget.tsx
  widgets/topology/src/widget.css
  widgets/topology/src/widget.tsx
Labels: internal

#1966 RD-4149 Enable widgets' README.md files lazy loading
  app/components/shared/widgets/Widget.tsx
  app/translations/en.json
  app/utils/widgetDefinitionsLoader.ts
Labels: internal

#1969 RD-1107 Allow user with `sys_admin` role and without tenant assigned to log in
  app/components/AuthRoutes.tsx
  app/utils/consts.ts
  test/cypress/integration/login_spec.ts
Labels: bug-fix

#1961 RD-4857: Blueprint optional description field in TerraformModal
  app/translations/en.json
  backend/routes/Terraform.ts
  backend/routes/Terraform.types.ts
  backend/templates/terraform/blueprint.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/support/blueprints.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#1970 RD-4403: Creating secrets on terraform modal submission
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#1954 RD-4556: Allow auto opening of the deployment modal and one blueprint upload from the marketplace
  .size-limit
  app/translations/en.json
  test/cypress/integration/flows/user_spec.ts
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/blueprintCatalog/src/AuthenticationWarning.tsx
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryList.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/UploadingMessage/UploadingMessage.styles.tsx
  widgets/blueprintCatalog/src/UploadingMessage/UploadingMessage.tsx
  widgets/blueprintCatalog/src/UploadingMessage/index.ts
  widgets/blueprintCatalog/src/actions.ts
  widgets/blueprintCatalog/src/consts.ts
  widgets/blueprintCatalog/src/types.ts
  widgets/blueprintCatalog/src/utils.ts
  widgets/blueprintCatalog/src/widget.tsx
Labels: feature, internal

#1974 RD-4685: Fixed issue with manipulating widgets in edit mode
  .size-limit
  app/actions/userAppCommon.ts
  devServer.ts
  package-lock.json
  package.json
Labels: bug-fix

#1971 RD-1051 Update restrictions on password changing
  .size-limit
  app/actions/app.ts
  app/actions/managers.ts
  app/actions/types.ts
  app/components/sidebar/UserMenu.tsx
  app/reducers/managerReducer/authReducer.ts
  app/reducers/managerReducer/emptyState.ts
  app/reducers/managerReducer/managerReducer.ts
  app/utils/consts.ts
  app/utils/shared/IdpUtils.ts
  app/utils/stageUtils.ts
  backend/handler/AuthHandler.ts
  backend/routes/External.ts
  test/cypress/components/app/sidebar/SideBar_spec.tsx
  test/cypress/integration/change_password_spec.ts
  test/cypress/integration/widgets/user_groups_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
  test/jest/reducers/managerReducer/managerReducer.test.ts
  test/jest/utils/Manager.test.ts
  widgets/userGroups/src/CreateModal.tsx
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userManagement/src/MenuAction.tsx
Labels: feature

#1935 RD-4493 Add Label filter rules to create deployment button widget
  app/translations/en.json
  templates/pages/environments.json
  templates/pages/services.json
  test/cypress/fixtures/blueprints/labels.zip
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/blueprints/LabelFilter.tsx
  widgets/common/src/blueprints/index.ts
  widgets/common/src/components/DynamicDropdown.tsx
  widgets/common/src/deployModal/DeployBlueprintModal.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/deploymentButton/README.md
  widgets/deploymentButton/src/DeploymentButton.tsx
  widgets/deploymentButton/src/widget.tsx
Labels: feature

#1972 RD-4149 Add widgets lazy loading
  .size-limit
  app/actions/drilldownPage.ts
  app/actions/page.ts
  app/actions/widgets.ts
  app/components/AddWidgetModal.tsx
  app/components/WidgetDynamicContent.tsx
  app/components/shared/widgets/Widget.tsx
  app/components/useWidgetsFilter.ts
  app/containers/AddWidget.ts
  app/reducers/widgetDefinitionsReducer.ts
  app/utils/External.ts
  app/utils/StageAPI.ts
  app/utils/normalizeWidgetDefinition.ts
  app/utils/scriptLoader.ts
  app/utils/widgetDefinitionsLoader.ts
  test/cypress/integration/change_password_spec.ts
  test/cypress/integration/cluster_status_spec.ts
  test/cypress/integration/community_spec.ts
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/getting_started_spec.ts
  test/cypress/integration/license_spec.ts
  test/cypress/integration/login_spec.ts
  test/cypress/integration/templateManagement/template_management_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/integration/user_menu_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/integration/widgets/user_defined_widgets_spec.ts
  test/cypress/support/commands.ts
  test/jest/reducers/pagesReducer.test.ts
  test/jest/utils/widgetDefinitionsLoader.test.ts
  widgets/common/src/index.ts
Labels: internal

#1964 RD-4580: Open deployment modal after submitting terraform module
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/blueprintActionButtons/src/consts.ts
  widgets/blueprintActionButtons/src/utils.ts
  widgets/blueprintActionButtons/src/widget.tsx
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButtons.tsx
Labels: feature

#1976 RD-3817 Simplify Okta (SAML) login procedure
  .size-limit
  app/components/AuthRoutes.tsx
  app/components/Routes.tsx
  app/components/SamlLogin.tsx
  app/utils/ErrorCodes.ts
  app/utils/auth.ts
  app/utils/consts.ts
  backend/consts.ts
  backend/routes/Auth.ts
  backend/routes/Auth.types.ts
  backend/test/routes/Auth.test.ts
  package-lock.json
  package.json
  test/cypress/integration/auth_spec.ts
  test/cypress/integration/login_spec.ts
Labels: internal

#1979 RD-1461 Remove `ClientConfigs` and `Applications` tables from Stage DB
  app/actions/app.ts
  app/actions/clientConfig.ts
  app/actions/config.ts
  app/actions/types.ts
  app/reducers/configReducer.ts
  backend/app.ts
  backend/db/Connection.ts
  backend/db/models/ApplicationsModel.ts
  backend/db/models/ClientConfigsModel.ts
  backend/migrations/20170425132017-4_0-init.ts
  backend/migrations/20220523115533-6_4-RemoveClientConfigsTable.ts
  backend/migrations/20220523121125-6_4-RemoveApplicationsTable.ts
  backend/routes/Applications.ts
  backend/routes/ClientConfig.ts
  backend/test/migration.test.ts
  backend/test/routes/Applications.test.ts
  backend/test/routes/ClientConfig.test.ts
  doc/diagrams/architecture-backend.txt
Labels: internal

#1980 RD-5014: Increased widgets height
  templates/pages/blueprintMarketplace.json
Labels: feature

#1982 RD-4997, RD-4904 BlueprintCatalog buttons UI improvements
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/widget.css
Labels: bug-fix

#1984 RD-5032 Improve robustness of Getting Started spec
  test/cypress/integration/getting_started_spec.ts
Labels: internal

#1975 RD-4403: Creating secrets on terraform modal submission - hiding secr…
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformVariableNameInput.tsx
Labels: feature

#1986 RD-1247 Update cloudify-ui-components; Move info button after required indicator in form inputs
  package-lock.json
  package.json
Labels: bug-fix
