Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-08, with the labels that each got.

#2092 RD-5399: Fixed variables & outputs detection on zip files
  backend/routes/Terraform.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: bug-fix

#2109 RD-5399: Fixed variables & outputs detection on zip files (#2092)
  backend/routes/Terraform.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: bug-fix

#2080 RD-5288 cypress commands
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
  test/cypress/integration/widgets/deployment_actions_spec.ts
  test/cypress/integration/widgets/labels_spec.ts
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  test/cypress/integration/widgets/snapshots_spec.ts
  test/cypress/support/blueprints.ts
  test/cypress/support/commands.ts
  test/cypress/support/deployments.ts
  test/cypress/support/executions.ts
  test/cypress/support/filters.ts
  test/cypress/support/labels.ts
  test/cypress/support/resource_commons.ts
Labels: internal

#2090 RD-2430 Add secrets to OpenStackV3 in GettingStartedModal
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
Labels: bug-fix

#2116 RD-5510 Corrections after #2113
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  test/cypress/integration/getting_started_spec.ts
Labels: bug-fix

#2118 RD-5510 #2116 merge to 6.4
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  test/cypress/integration/getting_started_spec.ts
Labels: internal

#2106 RD-5368: Revalidating variables and outputs after their import
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: bug-fix

#2115 RD-1103 Deduplicate some consts
  .size-limit
  app/README.md
  app/tsconfig.json
  app/utils/consts.ts
  app/utils/stageUtils.ts
  backend/handler/SourceHandler.ts
  backend/sharedUtils.ts
  backend/test/sharedUtils.test.ts
  backend/utils.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/common/src/Consts.ts
  widgets/common/src/blueprints/BlueprintActions.ts
  widgets/tsconfig.json
Labels: internal

#2114 RD-5500 Fix fetch URLs in deployment-related input types
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/NodeIdInputField.tsx
  widgets/common/src/inputs/fields/NodeInstanceInputField.tsx
  widgets/common/src/inputs/fields/NodeTypeInputField.tsx
  widgets/common/src/inputs/fields/ScalingGroupInputField.tsx
  widgets/common/src/inputs/fields/types.ts
  widgets/common/src/inputs/fields/useFetchUrlWithDeploymentId.ts
  widgets/common/src/inputs/utils/deploymentIdContext.ts
  widgets/common/src/inputs/utils/getConstraintValueFunction.ts
Labels: bug-fix

#2122 [6.4] RD-5500 Fix fetch URLs in deployment-related input types
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/inputs/InputField.tsx
  widgets/common/src/inputs/fields/NodeIdInputField.tsx
  widgets/common/src/inputs/fields/NodeInstanceInputField.tsx
  widgets/common/src/inputs/fields/NodeTypeInputField.tsx
  widgets/common/src/inputs/fields/ScalingGroupInputField.tsx
  widgets/common/src/inputs/fields/types.ts
  widgets/common/src/inputs/fields/useFetchUrlWithDeploymentId.ts
  widgets/common/src/inputs/utils/deploymentIdContext.ts
  widgets/common/src/inputs/utils/getConstraintValueFunction.ts
Labels: bug-fix

#2117 RD-5437 Redirect to the blueprint page after blueprint upload
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/blueprints/UploadBlueprintModal.tsx
Labels: feature

#2121 RD-3250 Update node to v16
  .nvmrc
  .size-limit
  README.md
  backend/package-lock.json
  backend/package.json
  jenkins/Jenkinsfile
  jenkins/build-pod.yaml
  package-lock.json
  package.json
  packaging/cloudify-stage.spec
  webpack.config.js
Labels: internal

#2125 RD-5575 Fix user_spec
  test/cypress/integration/flows/user_spec.ts
Labels: bug-fix

#2128 RD-5329 bump pg version and change patch file to match current version
  backend/package-lock.json
  backend/package.json
  backend/patches/pg+8.7.3.patch
Labels: bug-fix

#2022 RD-3438 Show images in blueprint
  .size-limit
  backend/handler/SourceHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/SourceBrowser.ts
  backend/test/routes/SourceBrowser.test.ts
  test/cypress/fixtures/blueprints/blueprint_with_image.zip
  test/cypress/integration/widgets/blueprint_sources_spec.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/blueprintSources/src/widget.css
Labels: bug-fix

#2127 RD-1237 Remove duplicated query string code
  app/utils/External.ts
  app/utils/Manager.ts
  app/utils/shared/UrlUtils.ts
  backend/handler/services/ManagerService.ts
  backend/handler/services/RequestService.ts
  backend/handler/services/common.ts
  backend/sharedUtils.ts
  backend/types.ts
  test/cypress/support/resource_commons.ts
  widgets/common/src/inputs/fields/useFetchUrlWithDeploymentId.ts
  widgets/filter/src/Filter.tsx
Labels: internal

#2131 RD-5597: Removed triggering System Tests on dependabot branches
  jenkins/Jenkinsfile
Labels: internal

#2136 RD-5597: Removed dependabot naming residue
  jenkins/Jenkinsfile
Labels: bug-fix, internal

#2135 RD-4851 Reuse LabelsList from cloudify-ui-components
  app/components/basic/index.ts
  package-lock.json
  package.json
  widgets/common/src/labels/LabelsInput.tsx
  widgets/common/src/labels/LabelsList.tsx
Labels: internal

#2137 RD-5617: Adjusted branch regexp
  jenkins/Jenkinsfile
Labels: bug-fix, internal

#2133 RD-5453: Enabled no-floating-promises eslint rule
  .eslintrc.json
Labels: internal

#2130 RD-5041 Deny modification of parent_id and consumer_id labels
  app/translations/en.json
  test/cypress/integration/widgets/deployment_actions_spec.ts
  widgets/common/src/labels/LabelsInput.tsx
  widgets/common/src/labels/common.ts
  widgets/common/src/labels/index.ts
  widgets/labels/src/LabelsTable.tsx
Labels: bug-fix

#2139 RD-5624: Adjust location values
  test/cypress/integration/widgets/sites_spec.ts
Labels: bug-fix, internal

#2140 RD-5631 Fix labels_spec
  widgets/labels/src/LabelsTable.tsx
Labels: bug-fix

#2142 RD-5625 Topology spec fix
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployment_info_spec.ts
  test/cypress/integration/widgets/executions_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/blueprints.ts
  test/cypress/support/commands.ts
  widgets/common/src/secrets/SecretActions.ts
  widgets/common/src/secrets/SecretsModal.tsx
  widgets/common/src/types.ts
  widgets/deployments/src/DeploymentsList.tsx
Labels: bug-fix, internal

#2134 RD-5247 automatically advance next in Getting Started Modal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#2144 RD-5663 Add handler for relative blueprint image URL in DB migration
  backend/migrations/20220527182401-6_4-RemoveBlueprintAdditionsTable.ts
  backend/test/migration.test.ts
  backend/test/snapshots/6.3.sql
Labels: bug-fix

#2146 [6.4.1] RD-5663 Add handler for relative blueprint image URL in DB migration
  backend/migrations/20220527182401-6_4-RemoveBlueprintAdditionsTable.ts
  backend/test/migration.test.ts
  backend/test/snapshots/6.3.sql
Labels: bug-fix

#2132 RD-5389 Disable Bulk action button when there's no deployment
  widgets/common/src/deploymentsView/DeploymentsView.tsx
  widgets/common/src/deploymentsView/header/index.tsx
Labels: bug-fix

#2126 RD-5286 update secrets modal
  app/translations/en.json
  test/cypress/fixtures/blueprints/required_secrets.zip
  test/cypress/integration/widgets/deployment_button_spec.ts
  widgets/common/src/secrets/MultilineInput.tsx
  widgets/common/src/secrets/SecretsModal.tsx
  widgets/common/src/secrets/SinglelineInput.tsx
  widgets/common/src/secrets/TogglableSecretsInput.tsx
Labels: feature

#2143 RD-3480: Introducing icon font
  .gitignore
  .size-limit
  app/styles/fonts.scss
  package-lock.json
  package.json
  semantic-ui/README.md
  semantic-ui/fontello.config.json
  semantic-ui/fonts/cloudify-icons/cloudify-icons.ttf
  semantic-ui/site/elements/icon.overrides
Labels: internal

#2147 RD-5613 Adjust height of Blueprint Marketplace tabs
  templates/pages/blueprintMarketplace.json
Labels: feature

#2145 RD-261 Remove usages of deprecated React APIs
  .size-limit
  app/components/Home.tsx
  app/components/Page.tsx
  app/components/useDefaultTabIndex.ts
  package-lock.json
  package.json
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/blueprintActionButtons/src/widget.tsx
Labels: internal

#2150 RD-3481: Updated sidebar icons
  app/components/sidebar/TenantSelection.tsx
  app/components/sidebar/UserMenu.tsx
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  templates/pages/environments.json
  templates/pages/logs.json
  templates/pages/tenants.json
Labels: feature

#2152 [6.4.1] RD-5613 Adjust height of Blueprint Marketplace tabs
  templates/pages/blueprintMarketplace.json
Labels: feature

#2151 RD-5594 Change route name from `/console/saml-login` to `/console/external-login`
  app/components/ExternalLogin.tsx
  app/components/Routes.tsx
  app/utils/consts.ts
  backend/consts.ts
  backend/routes/Auth.ts
  backend/test/routes/Auth.test.ts
  test/cypress/integration/auth_spec.ts
Labels: feature
