Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-07, with the labels that each got.

#2035 RD-5295 - Stage multibranch build won't start tests due to `apt update` failure
  jenkins/Jenkinsfile
Labels: bug-fix

#2032 RD-5224 Change dropdown styling to remove scrollbar from multivalue dropdowns in Chrome browser
  app/styles/style.scss
Labels: bug-fix

#2033 RD-4254 Set minimal width for the main layout
  app/components/layout/Grid.tsx
  app/styles/style.scss
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/plugins/src/MarketplaceModal.tsx
Labels: bug-fix, feature

#2036 RD-5178 Avoid two scrollbars in blueprints catalog
  templates/pages/blueprintMarketplace.json
Labels: bug-fix

#2034 RD-3694: remove color attribute from ApproveButtons
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/ResetPagesModal.tsx
  app/components/shared/MaintenanceModeModal.tsx
  app/components/shared/PasswordModal.tsx
  app/components/templateManagement/pageGroups/PageGroupModal.tsx
  app/components/templateManagement/pages/CreatePageModal.tsx
  app/components/templateManagement/templates/CreateTemplateModal.tsx
  package-lock.json
  package.json
  widgets/agents/src/InstallAgentsModal.tsx
  widgets/agents/src/ValidateAgentsModal.tsx
  widgets/common/src/blueprints/UploadBlueprintModal.tsx
  widgets/common/src/deployments/SetSiteModal.tsx
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
  widgets/common/src/deployments/UpdateDetailsModal.tsx
  widgets/common/src/deploymentsView/header/GoToExecutionsPageButton.tsx
  widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
  widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/labels/LabelsModal.tsx
  widgets/common/src/plugins/UploadPluginModal.tsx
  widgets/common/src/secrets/SecretsModal.tsx
  widgets/filters/src/FilterModal.tsx
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/UpdateModal.tsx
  widgets/sites/src/CreateModal.tsx
  widgets/sites/src/UpdateModal.tsx
  widgets/snapshots/src/CreateSnapshotModal.tsx
  widgets/snapshots/src/RestoreSnapshotModal.tsx
  widgets/snapshots/src/UploadSnapshotModal.tsx
  widgets/tenants/src/CreateModal.tsx
  widgets/tenants/src/GroupsModal.tsx
  widgets/tenants/src/UsersModal.tsx
  widgets/tokens/src/TokensTableHeader/CreateTokenModal.tsx
  widgets/userGroups/src/CreateModal.tsx
  widgets/userGroups/src/TenantsModal.tsx
  widgets/userGroups/src/UsersModal.tsx
  widgets/userManagement/src/CreateModal.tsx
  widgets/userManagement/src/GroupModal.tsx
  widgets/userManagement/src/TenantModal.tsx
Labels: internal

#2038 RD-5153 Terraform wrapper adjustments
  app/components/GettingStartedModal/steps/WelcomeStep.tsx
  app/translations/en.json
  app/utils/shared/renderMultilineText.tsx
  app/utils/stageUtils.ts
  backend/templates/terraform/blueprint.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/README.md
  widgets/common/src/deployments/RemoveDeploymentModal.tsx
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/terraformVersions.ts
  widgets/userManagement/src/UsersTable.tsx
Labels: feature

#2039 RD-3964 fix failing system tests
  app/components/InstallWidgetModal.tsx
  test/cypress/integration/edit_mode_spec.ts
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/secrets_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/integration/widgets/snapshots_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/integration/widgets/tenants_spec.ts
  test/cypress/integration/widgets/user_groups_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
Labels: bug-fix

#2037 RD-5107: Indicate installation failure on GettingStartedModal
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
  app/components/GettingStartedModal/steps/SummaryStep/TaskList.tsx
  app/translations/en.json
  test/cypress/integration/getting_started_spec.ts
Labels: bug-fix

#2041 RD-5104 fix fetching error in UserGroupsTable
  widgets/userGroups/src/UserGroupsTable.tsx
Labels: bug-fix

#2043 RD-5153 Improve 'Getting started' column header styling in Users Management widget
  app/translations/en.json
  widgets/userManagement/src/UsersTable.tsx
Labels: bug-fix

#2019 RD-4917 Add Id-Popup to deployments list
  app/components/shared/IdPopup.tsx
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/deployments/src/DeploymentsSegment.tsx
Labels: feature

#2040 RD-5115: Provided ability to open blueprint marketplace page with a specified active tab
  app/components/Tabs.tsx
  app/components/useDefaultTabIndex.ts
  app/translations/en.json
  templates/pages/adminDash.json
  templates/pages/blueprintMarketplace.json
  templates/pages/blueprints.json
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/service_button_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprints/README.md
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/common/src/Consts.ts
  widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
  widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
  widgets/common/src/blueprintMarketplace/index.ts
  widgets/common/src/blueprintMarketplace/types.ts
  widgets/common/src/index.ts
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButtons.tsx
  widgets/deployments/src/widget.tsx
  widgets/serviceButton/README.md
  widgets/serviceButton/src/ServiceButton.tsx
  widgets/serviceButton/src/widget.tsx
Labels: feature

#2046 RD-5199 mark only one blueprint as main
  package-lock.json
  package.json
  test/cypress/integration/widgets/blueprint_sources_spec.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
Labels: internal

#2052 RD-5245 Fix sorting by Deployment in Executions widget
  widgets/executions/src/ExecutionsTable.tsx
Labels: bug-fix

#2044 RD-5330 Finalize TS migration of Cypress system tests
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/executions_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  test/cypress/integration/widgets/outputs_capabilities_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/integration/widgets/tenants_spec.ts
  test/cypress/support/blueprints.ts
Labels: bug-fix, internal

#2045 RD-5330 Migrate Cluster Status components to TypeScript
  app/components/shared/cluster/ClusterService.tsx
  app/components/shared/cluster/ClusterServicesList.tsx
  app/components/shared/cluster/ClusterServicesOverview.tsx
  app/components/shared/cluster/ClusterStatusIcon.tsx
  app/components/shared/cluster/NodeServices.tsx
  app/components/shared/cluster/NodeStatus.tsx
  app/components/shared/cluster/consts.ts
  app/components/shared/cluster/types.ts
  app/reducers/managerReducer/clusterStatusReducer.ts
  test/cypress/fixtures/cluster_status/fail_with_services.json
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/support/cluster_status_commons.ts
Labels: bug-fix, internal

#2051 RD-4926 fix autofill bug in Firefox and migrate LoginPage to TS
  app/components/LoginPage.tsx
  app/components/Routes.tsx
  app/containers/LoginPage.ts
Labels: bug-fix, internal

#2049 RD-5340: Resolved moment and password vulnerabilities
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: dependencies

#2057 RD-5361 Add support for pagination in Tokens widget
  app/utils/GenericConfig.ts
  test/cypress/integration/widgets/tokens_spec.ts
  widgets/blueprints/src/types.ts
  widgets/deploymentInfo/src/widget.types.ts
  widgets/executionsStatus/src/types.ts
  widgets/sitesMap/src/widget.tsx
  widgets/tokens/src/TokensTable.tsx
  widgets/tokens/src/widget.tsx
  widgets/tokens/src/widget.types.ts
Labels: feature

#2059 RD-4469 Add support for setting expiration date when creating a new token
  app/translations/en.json
  app/utils/hooks/useErrors.ts
  test/cypress/integration/widgets/tokens_spec.ts
  widgets/tokens/src/TokensTableHeader/CreateTokenModal.tsx
  widgets/tokens/src/TokensTableHeader/CreateTokenModal.types.ts
Labels: feature

#2065 RD-4469 Update Tokens widget documentation
  widgets/tokens/README.md
Labels: internal

#2061 RD-5205 part 1: make headers consistent in events widget
  app/translations/en.json
  test/cypress/integration/widgets/events_spec.ts
  widgets/events/src/EventsTable.tsx
  widgets/events/src/widget.tsx
Labels: bug-fix

#2058 RD-2855: common ESLint config for Jest
  .eslintrc.json
  package-lock.json
  package.json
Labels: internal

#2066 RD-4954: Fixed parsing stringified numeric values
  widgets/common/src/inputs/fields/ValueListInputField.tsx
Labels: bug-fix

#2067 RD-5338: Rendering ExecutionProgress only when a required data is accessible
  widgets/deployments/src/DeploymentsSegment.tsx
Labels: bug-fix

#2062 RD-5205 part 2: make headers consistent in agents widget
  app/translations/en.json
  test/cypress/integration/widgets/agents_spec.ts
  widgets/agents/src/AgentsTable.tsx
  widgets/agents/src/types.tsx
  widgets/agents/src/widget.tsx
Labels: bug-fix

#2063 RD-5205 part 3: make headers consistent in Secrets widget
  app/translations/en.json
  widgets/secrets/src/SecretsTable.tsx
  widgets/secrets/src/types.ts
Labels: bug-fix

#2064 RD-5205 part 4: make headers consistent in other tables
  app/components/shared/cluster/ClusterServicesList.tsx
  app/translations/en.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/common/src/deploymentsView/detailsPane/pageLayout.json
Labels: bug-fix

#2068 RD-5365 Fix Topology widget data loading
  widgets/topology/src/Topology.tsx
Labels: bug-fix

#2071 RD-5371 Fix support for `placeHolder` widget configuration parameter
  app/components/EditWidget.tsx
  app/components/EditWidgetIcon.tsx
  app/components/EditWidgetModal.tsx
  app/components/shared/DynamicTable.tsx
  app/utils/Toolbox.ts
Labels: bug-fix

#2069 RD-5301: Synchronized mechanism for scanning zip and git files
  backend/routes/Terraform.ts
Labels: bug-fix

#2070 RD-5325 Fix support for `showVersionDetails` configuration parameter
  app/components/sidebar/SideBarHeader.tsx
  conf/README.md
  test/cypress/components/app/sidebar/SideBar_spec.tsx
  test/cypress/fixtures/community/config.json
  test/cypress/fixtures/configuration/userConfig.json
  test/cypress/integration/user_configuration_spec.ts
Labels: bug-fix, internal

#2075 RD-5393 Fix default value of `installMethods` configuration parameter in Agents widget
  widgets/agents/src/widget.tsx
Labels: bug-fix

#2076 RD-5382 Part 5: update docs
  widgets/agents/README.md
  widgets/events/README.md
Labels: bug-fix

#2073 RD-5186 Change dashboard icons for Services, K8S and Terraform
  app/images/clouds.png
  app/images/k8s_logo.png
  app/images/k8s_logo_dark.png
  app/images/services.png
  app/images/terraform.png
  app/translations/en.json
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  test/cypress/integration/widgets/cloud_num_spec.ts
  widgets/cloudNum/src/widget.tsx
Labels: feature

#2077 RD-5402 Fix drilldown functionality for pages defined in page groups
  app/reducers/pageReducer.ts
  templates/pages/drilldownDeployments.json
  test/jest/reducers/pagesReducer.test.ts
Labels: bug-fix

#2081 RD-5406 Fix refreshing deployment action buttons in Deployments View widget
  widgets/common/src/deploymentsView/detailsPane/header.tsx
Labels: bug-fix

#2082 RD-5191 Fix `selectParentPage` action and add "Parent" button to Deployments View widget header
  app/actions/drilldownContext.ts
  app/actions/pageMenu.ts
  app/reducers/appReducer.ts
  app/translations/en.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/ParentButton.tsx
  widgets/common/src/deploymentsView/detailsPane/drilldownButtons/index.tsx
Labels: bug-fix, feature

#2086 RD-5191 Update Deployments View widget documentation
  widgets/deploymentsView/README.md
Labels: internal

#2085 RD-5382 Remove setting blueprint ID in `className` prop
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/filter_spec.ts
  widgets/blueprints/src/BlueprintsCatalog.tsx
Labels: bug-fix

#2087 RD-5250 Add subservices to the list in services page
  templates/pages/services.json
Labels: feature

#2088 RD-5435 Bump `cloudify-ui-common` package to v7.3.1
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: dependencies, bug-fix

#2078 RD-3910: Blocked passing unnecessary data upon navigating to deployment page
  app/translations/en.json
  widgets/events/src/widget.tsx
  widgets/topology/src/Topology.tsx
Labels: bug-fix

#2089 RD-5440 Bump `sharp` package to v0.30.7
  backend/package-lock.json
  backend/package.json
Labels: dependencies, bug-fix

#2079 RD-5299: search by deployment name in Deployments Widget
  app/translations/en.json
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/common/src/actions/SearchActions.ts
  widgets/deployments/src/DeploymentsList.tsx
  widgets/deployments/src/widget.tsx
Labels: bug-fix

#2091 RD-5206 The unsaved filter in Service page cannot be reused if removed
  widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
  widgets/common/src/deploymentsView/header/index.tsx
Labels: bug-fix

#2096 RD-5452: Referenced existing variable
  widgets/events/src/widget.tsx
Labels: bug-fix

#2100 RD-5452: Referenced existing variable
  widgets/events/src/widget.tsx
Labels: bug-fix

#2098 RD-5206 The unsaved filter in Service page cannot be reused if removed (#2091)
  widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
  widgets/common/src/deploymentsView/header/index.tsx
Labels: bug-fix

#2097 RD-5352 Add new action switches to the Deployment Update modal
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/common/src/deployments/DeploymentActions.ts
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
Labels: feature

#2095 RD-4999 Update blueprint examples links and documentation links for v6.4
  app/components/GettingStartedModal/schema/gettingStarted.schema.json
  app/translations/en.json
  scripts/checkDocs.sh
  scripts/readmesConfig.json
Labels: feature

#2101 RD-4999 Update blueprint links
  app/components/GettingStartedModal/schema/gettingStarted.schema.json
  app/translations/en.json
Labels: feature

#2102 [6.4] RD-5352 Add new action switches to the Deployment Update modal
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/common/src/deployments/DeploymentActions.ts
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
Labels: feature

#2094 RD-571 Solve unhandled promise rejections
  backend/handler/ArchiveHelper.ts
  backend/handler/SourceHandler.ts
  backend/handler/WidgetsHandler.ts
  backend/migrations/20201030110539-5_1_1-MigratePageLayouts.ts
  backend/migrations/20210929110911-6_3-UserAppsPageGroups.ts
  backend/routes/BlueprintUserData.ts
  backend/routes/Plugins.ts
  backend/routes/Terraform.ts
Labels: internal

#2099 RD-5020 Split `blueprints_spec` into 2 files
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: internal

#2104 [6.4] RD-5020 Split `blueprints_spec` into 2 files
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: internal

#2093 RD-4936 Add first login credentials hint to the Login page
  app/components/LoginPage.tsx
  app/configureStore.ts
  app/reducers/configReducer.ts
  app/translations/en.json
  app/tsconfig.json
  app/utils/ConfigLoader.ts
  backend/app.ts
  backend/config.ts
  backend/db/Connection.ts
  backend/handler/ManagerHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Auth.ts
  backend/routes/Config.ts
  backend/routes/Config.types.ts
  conf/README.md
  conf/userConfig.json
  test/cypress/fixtures/configuration/userConfig.json
  test/cypress/integration/login_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#2105 [6.4] RD-4936 Add first login credentials hint to the Login page
  app/components/LoginPage.tsx
  app/configureStore.ts
  app/reducers/configReducer.ts
  app/translations/en.json
  app/tsconfig.json
  app/utils/ConfigLoader.ts
  backend/app.ts
  backend/config.ts
  backend/db/Connection.ts
  backend/handler/ManagerHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Auth.ts
  backend/routes/Config.ts
  backend/routes/Config.types.ts
  conf/README.md
  conf/userConfig.json
  test/cypress/fixtures/configuration/userConfig.json
  test/cypress/integration/login_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#2103 RD-5390 Upgrade topology to v4
  .size-limit
  package-lock.json
  package.json
  test/cypress/integration/widgets/topology_spec.ts
  webpack.config.js
Labels: internal

#2108 RD-5390 Upgrade topology to v4 (#2103)
  .size-limit
  package-lock.json
  package.json
  test/cypress/integration/widgets/topology_spec.ts
  webpack.config.js
Labels: internal
