Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-02, with the labels that each got.

#1794 RD-4104: Removed uploadPluginFromCatalog function from the test files
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/plugins.ts
Labels: internal

#1797 RD-4048: Added component which is used to animate menu subitems
  .size-limit
  app/components/sidebar/SideBar.tsx
  app/components/sidebar/SideBarItem.tsx
Labels: feature

#1800 RD-1293 Added support for TS in widget backend
  .eslintignore
  .gitignore
  backend/handler/BackendHandler.ts
  backend/package.json
  backend/test/tsconfig.json
  conf/config.json
  test/cypress/fixtures/widgets/testWidgetBackend.zip
  test/cypress/fixtures/widgets/testWidgetModuleNotAllowed.zip
  test/cypress/fixtures/widgets/testWidgetModuleNotAllowedInService.zip
  test/cypress/integration/edit_mode_spec.ts
  webpack.config.js
  widgets/.eslintrc.json
  widgets/executions/src/backend.ts
  widgets/managers/src/backend.ts
Labels: internal

#1802 RD-3240 Modified CI build to include component tests
  jenkins/Jenkinsfile
  jenkins/build-pod.yaml
Labels: internal

#1803 RD-2946 Add hot reloading
  devServer.ts
  package-lock.json
  package.json
Labels: internal

#1801 RD-4070 Fully migrate GenericDeployModal to TypeScript
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/common/src/DeploymentActionsModals.tsx
  widgets/common/src/DynamicDropdown.tsx
  widgets/common/src/ExecuteDeploymentModal.tsx
  widgets/common/src/FileActions.ts
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/deployModal/DeploymentInputsSection.tsx
  widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
  widgets/common/src/types.ts
Labels: internal

#1804 RD-4194 Added ability to enter non-existing secret to the Terraform modal
  app/translations/en.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/README.md
  widgets/blueprints/src/TerraformVariableValueInput.tsx
Labels: bug-fix

#1806 RD-3222 eslint part 1: Update cloudify-ui-common to v5.1.2
  package-lock.json
  package.json
Labels: internal

#1808 RD-4214: Updated my.json.template - using SSL by default
  conf/me.json.template
Labels: internal

#1810 RD-4186 Made maps route unauthenticated, improved cy test
  backend/app.ts
  test/cypress/integration/widgets/sites_map_spec.ts
Labels: bug-fix

#1811 RD-4186 Made maps route unauthenticated, improved cy test (#1810)
  backend/app.ts
  test/cypress/integration/widgets/sites_map_spec.ts
Labels: bug-fix

#1770 RD-3624 (part 2)Extract shared code
  app/translations/en.json
  widgets/common/src/DeploymentActions.ts
  widgets/common/src/DeploymentActionsModals.tsx
  widgets/common/src/ExecuteDeploymentModal.tsx
  widgets/common/src/GenericDeployModal.tsx
  widgets/common/src/InputsUtils.tsx
  widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/executeWorkflow/common.ts
  widgets/common/src/executeWorkflow/index.ts
  widgets/common/src/executeWorkflow/types.ts
  widgets/common/src/types.ts
  widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
  widgets/deployments/src/DeploymentsList.tsx
  widgets/managers/src/ManagersTable.tsx
Labels: internal

#1799 RD-4049 Update GitHub PR template & Add description about docs synchronization
  .github/pull_request_template.md
  doc/README.md
Labels: internal

#1817 RD-4182 Set catalog view as default for blueprints page
  templates/pages/blueprints-community.json
  templates/pages/blueprints.json
  test/cypress/integration/flows/user_spec.ts
Labels: feature

#1818 RD-2841 Add mock for splash loading screen
  app/components/license/UploadLicense.tsx
  app/utils/SplashLoadingScreen.ts
  app/utils/__mocks__/SplashLoadingScreen.ts
  test/jest/setup.ts
Labels: internal

#1821 RD-2544 Remove unused Jenkinsfile and CircleCI configuration
  .circleci/config.yml
  Jenkinsfile
Labels: internal

#1824 RD-4182 Increased blueprints widget height
  templates/pages/blueprints-community.json
  templates/pages/blueprints.json
Labels: feature

#1826 RD-4102 Added test for getResourceLocation function
  test/jest/setup.ts
  test/jest/widgets/blueprints/TerraformModal.test.ts
  widgets/blueprints/src/TerraformModal.tsx
Labels: internal

#1815 RD-3760 Add test retries in Maintenance Mode Button widget test
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/resource_commons.ts
Labels: bug-fix, internal

#1828 RD-3760 Improve setting admin authorization in `cfyRequest` Cypress command
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/resource_commons.ts
Labels: bug-fix, internal

#1813 RD-3949 Create contact form for submitting the user data
  .size-limit
  app/components/ContactDetailsModal/ContactDetailsModal.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/CheckboxLabel.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  app/components/ContactDetailsModal/ContactDetailsModalContent/index.ts
  app/components/ContactDetailsModal/ContactDetailsModalContent/utils.ts
  app/components/ContactDetailsModal/ContactDetailsModalContent/validationRegexpPatterns.ts
  app/components/ContactDetailsModal/index.ts
  app/components/ContactDetailsModal/useModalOpenState.ts
  app/components/GettingStartedModal/common/fetchHooks.ts
  app/components/GettingStartedModal/common/managerHooks.ts
  app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
  app/components/GettingStartedModal/useModalOpenState.ts
  app/components/Home.tsx
  app/translations/en.json
  app/utils/hooks/useManager.ts
  backend/app.ts
  backend/routes/ContactDetails.ts
  backend/test/routes/ContactDetails.test.ts
  devServer.ts
  test/cypress/integration/community_spec.ts
Labels: feature

#1812 RD-3624 (part 3) Move install section to deploy modal
  app/translations/en.json
  test/cypress/fixtures/blueprints/custom_install_workflow.zip
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/support/commands.ts
  widgets/common/src/InputsUtils.tsx
  widgets/common/src/UpdateDeploymentModal.tsx
  widgets/common/src/deployModal/DeployBlueprintModal.tsx
  widgets/common/src/deployModal/DeployModalActions.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/deploymentsView/header/DeployOnModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/executeWorkflow/common.ts
  widgets/common/src/executeWorkflow/index.ts
Labels: feature

#1835 RD-3609 Fix security audit issues coming from `request` package
  backend/package-lock.json
  backend/package.json
Labels: dependencies, internal

#1839 RD-4304 Downgrade `vm2` package to v3.9.5
  backend/package-lock.json
  backend/package.json
Labels: bug-fix

#1838 RD-4297 Fix security audit issues coming from `ajv` package
  backend/package-lock.json
  package-lock.json
Labels: dependencies, internal

#1836 RD-4286 Add support for new deployment filter rule types - `tenant_name` and `display_name`
  app/translations/en.json
  test/cypress/integration/widgets/filters_spec.ts
  widgets/common/src/filters/RuleValueInput.tsx
  widgets/common/src/filters/inputs/DisplayNameValueInput.tsx
  widgets/common/src/filters/inputs/TenantNameValueInput.tsx
  widgets/common/src/filters/inputs/index.ts
  widgets/common/src/filters/types.ts
  widgets/filters/README.md
Labels: feature

#1842 RD-4320 Fix typo in vSphere Secrets dialog in Getting Started modal
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
Labels: bug-fix

#1837 RD-4296 Added backward compatibility for JS widget backends
  backend/handler/BackendHandler.ts
  conf/README.md
  conf/config.json
  scripts/widgetBackendWatcher.js
  test/cypress/fixtures/widgets/testWidgetBackend.zip
Labels: feature

#1829 RD-4142: DeploymentList table based widget
  test/cypress/integration/widgets/deployment_list_spec.ts
  widgets/deploymentList.zip
  widgets/deploymentList/src/DeploymentList.tsx
  widgets/deploymentList/src/types.ts
  widgets/deploymentList/src/widget.tsx
  widgets/deploymentList/widget.png
  widgets/deploymentListWidgetZip.sh
Labels: feature

#1844 RD-4315 Updated EULA link
  app/translations/en.json
Labels: bug-fix

#1848 RD-4315 Update EULA link in Contact Details modal [6.3.1]
  app/translations/en.json
Labels: bug-fix

#1850 RD-4351: Added blueprints icon for the community version sidebar
  templates/pages/blueprints-community.json
Labels: bug-fix

#1851 RD-4351: Synchronizing the 6.3.1-build version with the changes introduced by the RD-4351 changes
  templates/pages/blueprints-community.json
Labels: bug-fix

#1852 RD-3825: Resolved some of the vulnerabilities detected by SNYK
  package-lock.json
  package.json
Labels: internal

#1845 RD-4317 Add NPM script for building single widget
  README.md
  package.json
  scripts/buildWidget.sh
  webpack.config.js
  widgets/README.md
Labels: feature

#1853 RD-4367: Made all checkboxes required
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  test/cypress/integration/community_spec.ts
Labels: feature

#1855 RD-4367: Cherry picking functionality from RD-4367 to 6.3.1
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  test/cypress/integration/community_spec.ts
Labels: feature

#1854 RD-4368 Reused EULA link
  app/components/ContactDetailsModal/ContactDetailsModalContent/CheckboxLabel.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  app/translations/en.json
  test/cypress/integration/community_spec.ts
Labels: internal

#1847 RD-4052 Improve internal documentation
  jenkins/Jenkinsfile
  package.json
  scripts/checkJsonFiles.sh
  templates/README.md
  templates/schemas/page-group.schema.json
  templates/schemas/page.schema.json
  templates/schemas/template.schema.json
  test/README.md
  widgets/README.md
Labels: internal
