Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-11, with the labels that each got.

#2240 RD-6205 Fix Auth Service presence check in User Management widget
  test/cypress/integration/flows/admin_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
  widgets/userManagement/src/authServiceActions.ts
Labels: bug-fix

#2238 RD-3489: Styled input errors
  semantic-ui/site/collections/form.overrides.less
  semantic-ui/site/collections/form.variables.less
  semantic-ui/site/elements/input.overrides.less
Labels: feature

#2241 RD-6023 Styled Textarea component
  semantic-ui/site/collections/form.overrides.less
  semantic-ui/site/collections/form.variables.less
  semantic-ui/site/elements/input.overrides.less
  semantic-ui/site/elements/input.variables.less
  semantic-ui/site/globals/site.variables.less
Labels: feature

#2243 RD-5755 Fix `test/cypress/integration/cluster_status_spec.ts` test
  app/components/sidebar/HealthIndicator.tsx
Labels: internal

#2244 RD-5280 Deduplicate plugin wagon name creation logic
  app/components/GettingStartedModal/common/managerHooks.ts
  app/utils/Manager.ts
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
Labels: internal

#2248 RD-6206 Remove Cloudify UI Components sync check from Stage CI pipeline
  doc/README.md
  jenkins/Jenkinsfile
  package.json
  scripts/checkDocs.sh
Labels: internal

#2249 RD-6276 Fixed xmldom vulnerability
  backend/package-lock.json
Labels: dependencies

#2226 RD-5717 adjustment after NodesTree & HighlightText TS migration
  .size-limit
  package-lock.json
  package.json
  widgets/blueprintSources/src/BlueprintSources.tsx
Labels: internal

#2252 RD-6294 Resolved nwsapi vulnerability
  package-lock.json
Labels: dependencies

#2251 RD-6114 Update internal documentation
  app/README.md
  doc/README.md
  widgets/README.md
Labels: internal

#2239 RD-6017 Adjust icons in blueprintCatalog
  test/cypress/fixtures/blueprints/blueprintsCatalog.json
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryLinkButton.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
Labels: feature

#2234 RD-6075 Start reusing toolbox related types exported by `cloudify-ui-components`
  app/utils/EventBus.ts
  app/utils/External.ts
  app/utils/StageAPI.ts
  app/utils/Toolbox.ts
  widgets/agents/src/AgentsTable.tsx
  widgets/agents/src/InstallAgentsModal.tsx
  widgets/agents/src/NodeFilter.tsx
  widgets/agents/src/ValidateAgentsModal.tsx
  widgets/common/src/deployModal/DeployBlueprintModal.tsx
  widgets/common/src/deployments/DeploymentActions.ts
  widgets/common/src/deployments/RemoveDeploymentModal.tsx
  widgets/common/src/deployments/SetSiteModal.tsx
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
  widgets/common/src/deploymentsView/map/container.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/common/src/executeWorkflow/common.ts
  widgets/common/src/executions/ExecutionActions.ts
  widgets/common/src/labels/LabelsInput.tsx
  widgets/common/src/labels/LabelsModal.tsx
  widgets/deploymentActionButtons/src/widget.tsx
  widgets/deploymentInfo/src/DeploymentInfo.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/deployments/src/DeploymentsList.tsx
  widgets/deployments/src/widget.tsx
  widgets/executions/src/widget.tsx
  widgets/labels/src/DeleteConfirmModal.tsx
  widgets/labels/src/LabelsTable.tsx
  widgets/labels/src/widget.tsx
  widgets/sitesMap/src/widget.tsx
Labels: internal

#2235 RD-5591 Migrate Redux store to TypeScript - part 3 (template management and widgets)
  app/actions/WidgetData.ts
  app/actions/drilldownPage.ts
  app/actions/initialPageLoad.ts
  app/actions/layoutDefinitions.ts
  app/actions/page.ts
  app/actions/pageMenu.ts
  app/actions/templateManagement/index.ts
  app/actions/templateManagement/pageGroups.ts
  app/actions/templateManagement/pages.ts
  app/actions/templateManagement/templates.ts
  app/actions/templates.ts
  app/actions/types.ts
  app/actions/userApp.ts
  app/actions/widgetData.ts
  app/actions/widgetDefinitions.ts
  app/actions/widgets.ts
  app/components/AddWidgetModal.tsx
  app/components/AuthRoutes.tsx
  app/components/LoginPage.tsx
  app/components/Page.tsx
  app/components/shared/widgets/Widget.tsx
  app/components/templateManagement/pages/PageManagement.tsx
  app/components/templateManagement/templates/Templates.tsx
  app/configureStore.ts
  app/containers/AddWidget.ts
  app/reducers/pageReducer.ts
  app/reducers/templateManagementReducer.ts
  app/reducers/templatesReducer.ts
  app/reducers/widgetDataReducer.ts
  app/reducers/widgetDefinitionsReducer.ts
  app/reducers/widgetsReducer.ts
  app/utils/Toolbox.ts
  app/utils/WidgetParamsHandler.ts
  app/utils/layoutDefinitionsLoader.ts
  app/utils/templatesLoader.ts
  app/utils/widgetDataFetcher.ts
  app/utils/widgetDefinitionsLoader.ts
  backend/handler/templates/types.ts
  package-lock.json
  package.json
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/login_spec.ts
  test/cypress/integration/templateManagement/page_groups_spec.ts
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/templateManagement/pages_preview_spec.ts
  test/cypress/integration/templateManagement/pages_spec.ts
  test/cypress/integration/templateManagement/template_management_spec.ts
  test/cypress/integration/templateManagement/templates_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/templates.ts
  test/jest/actions/templateManagement.test.ts
  test/jest/reducers/managerReducer/managerReducer.test.ts
  test/jest/reducers/managerReducer/tenantsReducer.test.ts
  test/jest/reducers/pagesReducer.test.ts
  test/jest/utils/widgetDefinitionsLoader.test.ts
Labels: bug-fix, internal

#2237 RD-5999 added labels as configuration option for deployment view
  app/translations/en.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/common/src/deploymentsView/DeploymentLabeLConfigurationInput.tsx
  widgets/common/src/deploymentsView/DeploymentsView.tsx
  widgets/common/src/deploymentsView/configuration.ts
  widgets/common/src/deploymentsView/table/DeploymentsTable.tsx
  widgets/common/src/deploymentsView/table/renderDeploymentRow.tsx
  widgets/common/src/deploymentsView/types.ts
  widgets/common/src/labels/KeyDropdown.tsx
  widgets/common/src/labels/LabelsInput.tsx
  widgets/common/src/labels/types.ts
Labels: feature

#2257 RD-6337 Fix `build:widget` NPM script
  jenkins/Jenkinsfile
  scripts/buildWidget.sh
  webpack.config.js
Labels: bug-fix, internal

#2258 RD-5591 Migrate Redux store to TypeScript - part 4 (final alignments)
  app/actions/drilldownContext.ts
  app/actions/drilldownPage.ts
  app/actions/manager/clusterStatus.ts
  app/actions/pageMenu.ts
  app/actions/templateManagement/pages.ts
  app/components/Home.tsx
  app/components/Page.tsx
  app/components/templateManagement/pages/PageManagement.tsx
  app/reducers/drilldownContextReducer.ts
  app/reducers/managerReducer/clusterStatusReducer.ts
  app/reducers/pageReducer.ts
  app/reducers/templatesReducer.ts
  backend/handler/templates/types.ts
  test/jest/reducers/pagesReducer.test.ts
Labels: bug-fix, internal

#2256 RD-6182 PP - System Setup user table adjustment
  widgets/filters/src/FiltersTable.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userManagement/src/UsersTable.tsx
Labels: internal

#2253 RD-6119 add `Open` button to Blueprint Marketplace
  app/translations/en.json
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryList.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/types.ts
Labels: feature

#2259 RD-5918 Unskipped tests
  test/cypress/integration/flows/user_spec.ts
Labels: internal

#2222 RD-5719 RD-1701 RD-2083 Fix types and usage of DataTable component
  app/components/basic/index.ts
  app/components/shared/VerticallyAlignedCell.tsx
  app/components/shared/index.ts
  app/components/templateManagement/pageGroups/PageGroups.tsx
  app/utils/GenericConfig.ts
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/blueprints/src/types.ts
  widgets/executions/src/ExecutionsTable.tsx
  widgets/filters/src/FiltersTable.tsx
  widgets/managers/src/ManagersTable.tsx
  widgets/nodes/src/NodeInstancesTable.tsx
  widgets/nodes/src/NodesTable.tsx
  widgets/plugins/src/PluginsTable.tsx
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/sites/src/SitesTable.tsx
  widgets/snapshots/src/SnapshotsTable.tsx
  widgets/tenants/src/TenantsTable.tsx
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userManagement/src/UsersTable.tsx
Labels: bug-fix, internal

#2260 RD-6020 RD-6021 Theming of the dropdown component
  semantic-ui/site/collections/form.variables.less
  semantic-ui/site/elements/label.variables.less
  semantic-ui/site/globals/site.variables.less
  semantic-ui/site/modules/dropdown.overrides.less
  semantic-ui/site/modules/dropdown.variables.less
Labels: feature

#2261 RD-6393 Unskip system tests
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
  test/cypress/integration/widgets/topology_spec.ts
Labels: internal

#2263 RD-6404 Audit fix for loader-utils
  package-lock.json
Labels: bug-fix

#2262 RD-6119 cypress test
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
Labels: internal

#2264 RD-5423 Fix support for Deploy action in Deploy On modal
  app/translations/en.json
  test/cypress/integration/widgets/deployments_view_spec.ts
  widgets/common/src/deployModal/DeployModalActions.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/deploymentsView/header/DeployOnModal.tsx
Labels: bug-fix

#2265 RD-6399 Fixed presentation of event logs icons
  .size-limit
  app/app.tsx
Labels: bug-fix

#2267 RD-6189 PP sidebar adjustment in editMode
  .size-limit
  app/components/EditModeButton.css
  app/components/sidebar/PagesList.tsx
  app/components/sidebar/SideBarItem.tsx
Labels: bug-fix

#2271 RD-6430 Improve `killRunningExecutions` cypress custom command
  test/cypress/support/executions.ts
Labels: internal

#2273 RD-6022 Message component theming
  semantic-ui/site/collections/message.overrides.less
  semantic-ui/site/collections/message.variables.less
  semantic-ui/site/globals/site.variables.less
Labels: feature

#2266 RD-5759 Migrate app framework - `templateManagement` components to TypeScript
  app/components/templateManagement/TemplateManagement.tsx
  app/components/templateManagement/pageGroups/PageGroups.tsx
  app/components/templateManagement/pages/CreatePageModal.tsx
  app/components/templateManagement/pages/Pages.tsx
  app/components/templateManagement/templates/CreateTemplateModal.tsx
  app/components/templateManagement/templates/RoleList.tsx
  app/components/templateManagement/templates/Templates.tsx
  app/components/templateManagement/templates/TenantList.tsx
  app/components/templateManagement/templates/types.ts
  backend/handler/templates/PagesHandler.ts
  backend/handler/templates/types.ts
  backend/routes/Templates.types.ts
Labels: internal

#2272 RD-6431 Extract `interceptWithoutCaching` custom command
  test/cypress/integration/login_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/support/commands.ts
Labels: internal

#2269 RD-6194 PP change of font-size
  app/components/shared/cluster/ClusterService.tsx
  app/components/shared/cluster/ClusterServicesOverview.tsx
Labels: bug-fix

#2275 RD-6403: Standardize Approve and Cancel buttons order of presentation
  app/components/EditTabModal.tsx
  app/components/EditWidgetModal.tsx
Labels: feature

#2280 RD-6431 Add generic parameter type to `interceptWithoutCaching` custom Cypress command
  test/cypress/integration/login_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/support/commands.ts
Labels: internal

#2282 RD-6455 Skip failing tests
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: internal

#2281 RD-5881 upgrade node/types to v16.11.68
  backend/package-lock.json
  backend/package.json
Labels: internal

#2242 RD-5228 Cypress 10 upgrade
  cypress.config.ts
  package-lock.json
  package.json
  test/cypress/components/utils.tsx
  test/cypress/components/widgets/filters/RulesForm_spec.tsx
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/templateManagement/templates_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprint_num_spec.ts
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/deployment_button_configuration_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/integration/widgets/tokens_spec.ts
  test/cypress/plugins/index.ts
  test/cypress/support/commands.ts
  test/cypress/support/component-index.html
  test/cypress/support/editMode.ts
  test/cypress/tsconfig.json
  test/jest/setupFiles.ts
Labels: internal

#2277 RD-5787 Migrate User Groups Management widget to TS
  app/translations/en.json
  backend/handler/AuthHandler.types.ts
  widgets/userGroups/src/CreateModal.tsx
  widgets/userGroups/src/GroupDetails.tsx
  widgets/userGroups/src/MenuAction.tsx
  widgets/userGroups/src/TenantsModal.tsx
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userGroups/src/UsersModal.tsx
  widgets/userGroups/src/actions.ts
  widgets/userGroups/src/props/GroupPropType.ts
  widgets/userGroups/src/widget.tsx
  widgets/userGroups/src/widget.types.ts
Labels: internal

#2286 RD-6177 Adjusted placement of the ExecutionWorkflowGraph toolbar icons
  widgets/executions/src/widget.css
Labels: feature

#2283 RD-6191 Bumped cloudify-ui-components
  app/components/basic/index.ts
  package-lock.json
  package.json
  test/cypress/integration/edit_mode_spec.ts
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/deployment_button_configuration_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/secrets_spec.ts
  test/cypress/integration/widgets/sites_spec.ts
  test/cypress/integration/widgets/snapshots_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/integration/widgets/tenants_spec.ts
  test/cypress/integration/widgets/user_groups_spec.ts
  test/cypress/integration/widgets/user_management_spec.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprints/src/BlueprintsCatalog.tsx
Labels: feature

#2285 RD-6455 Unskip tests
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: internal

#2287 RD-6176 Align drilldown buttons
  semantic-ui/site/elements/button.overrides.less
Labels: feature

#2290 RD-6078 update Blueprints Catalog documentation
  widgets/blueprintCatalog/README.md
Labels: internal

#2289 RD-5753 Migrating app/utils files to TS - Part 1
  app/utils/External.ts
  app/utils/Manager.ts
  widgets/common/src/actions/SearchActions.ts
  widgets/common/src/deploymentsView/header/DeployOnModal.tsx
  widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
Labels: internal
