Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-09, with the labels that each got.

#2160 RD-5605 Add a description to secrets properties
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/steps/SecretsStep.tsx
Labels: feature

#2154 RD-3483 Change Page Styling
  app/components/Breadcrumbs.tsx
  app/components/Page.tsx
  app/styles/colors.scss
  app/styles/fonts.scss
  app/styles/style.scss
  semantic-ui/site/collections/breadcrumb.overrides
  semantic-ui/site/globals/site.variables
Labels: feature

#2158 RD-5684 Blank screen on Getting Started Modal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalActions.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/steps/EnvironmentsStep/EnvironmentButton.tsx
  app/components/GettingStartedModal/steps/EnvironmentsStep/EnvironmentsStep.tsx
  test/cypress/integration/getting_started_spec.ts
Labels: bug-fix

#2167 RD-5894 Remove Deployment Wizard Buttons widget
  app/translations/en.json
  backend/test/handlers/WidgetHandler.test.ts
  scripts/readmesConfig.json
  test/cypress/fixtures/community/manager.json
  test/cypress/integration/widgets/deployment_wizard_spec.ts
  test/jest/resources/rbac.ts
  widgets/deploymentWizardButtons/README.md
  widgets/deploymentWizardButtons/images/aws_logo.svg
  widgets/deploymentWizardButtons/images/azure_logo.svg
  widgets/deploymentWizardButtons/images/gcp_logo.svg
  widgets/deploymentWizardButtons/images/openstack_logo.svg
  widgets/deploymentWizardButtons/src/WizardButton.tsx
  widgets/deploymentWizardButtons/src/steps/BlueprintStep.tsx
  widgets/deploymentWizardButtons/src/steps/ConfirmationStep.tsx
  widgets/deploymentWizardButtons/src/steps/InfrastructureStep.tsx
  widgets/deploymentWizardButtons/src/steps/InputsStep.tsx
  widgets/deploymentWizardButtons/src/steps/InstallStep.tsx
  widgets/deploymentWizardButtons/src/steps/PluginsStep.tsx
  widgets/deploymentWizardButtons/src/steps/SecretsStep.tsx
  widgets/deploymentWizardButtons/src/steps/StepContentPropTypes.ts
  widgets/deploymentWizardButtons/src/steps/helpers/NoResourceMessage.tsx
  widgets/deploymentWizardButtons/src/steps/helpers/ResourceAction.tsx
  widgets/deploymentWizardButtons/src/steps/helpers/ResourceStatus.tsx
  widgets/deploymentWizardButtons/src/steps/helpers/Task.ts
  widgets/deploymentWizardButtons/src/steps/helpers/TaskList.tsx
  widgets/deploymentWizardButtons/src/steps/helpers/TaskStatus.tsx
  widgets/deploymentWizardButtons/src/widget.css
  widgets/deploymentWizardButtons/src/widget.tsx
  widgets/deploymentWizardButtons/src/wizard/StepActions.tsx
  widgets/deploymentWizardButtons/src/wizard/Wizard.css
  widgets/deploymentWizardButtons/src/wizard/WizardModal.tsx
  widgets/deploymentWizardButtons/src/wizard/index.ts
  widgets/deploymentWizardButtons/src/wizard/wizardUtils.tsx
  widgets/deploymentWizardButtons/widget.png
Labels: breaking-change

#2165 RD-5606 Add a description to secrets modal
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/model.ts
Labels: feature

#2164 RD-3485: Modify styling of the application buttons
  package-lock.json
  semantic-ui/site/elements/button.overrides
  semantic-ui/site/elements/button.variables
  semantic-ui/site/globals/site.variables
  semantic-ui/site/modules/sidebar.overrides
Labels: feature

#2174 RD-1563 remove overriding assertion for ApproveButton
  app/components/basic/index.ts
Labels: internal

#2176 RD-5665 #2173 merge to 6.4.1
  backend/handler/RequestHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/ServerProxy.ts
  conf/README.md
  conf/userConfig.json
  jenkins/build-pod.yaml
Labels: bug-fix

#2178 RD-5965 Bump `follow-redirects` package in cloudify-stage backend
  backend/package-lock.json
Labels: dependencies, bug-fix

#2153 RD-5385 Email in GettingStartedModal
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/ModalContent.tsx
  app/components/GettingStartedModal/model.ts
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
  app/components/GettingStartedModal/steps/SecretsStep.tsx
  app/translations/en.json
  package-lock.json
  test/cypress/integration/getting_started_spec.ts
Labels: feature

#2177 RD-5965 Bump `axios` and `follow-redirects` packages in backend to make Stage DB migration more robust
  backend/package-lock.json
  backend/package.json
Labels: dependencies, bug-fix

#2181 RD-5598 Add UI testing guidelines link to PR template and update main documentation file
  .github/pull_request_template.md
  Makefile
  README.md
  doc/screenshot.png
  docker-compose.yml
  scripts/loadLatestPremiumDockerImage.sh
Labels: internal

#2184 RD-5947 Workaround for version and prerelease parameters fetch
  jenkins/Jenkinsfile
Labels: internal

#2182 RD-5740 Migrate backend to TypeScript - part 2
  app/actions/page.ts
  app/components/LicensePage.tsx
  app/components/license/CurrentLicense.tsx
  app/reducers/managerReducer/licenseReducer.ts
  app/reducers/managerReducer/managerReducer.ts
  app/utils/StageAPI.ts
  app/utils/auth.ts
  app/utils/widgetDefinitionsLoader.ts
  backend/README.md
  backend/db/models/UserAppsModel.types.ts
  backend/handler/ArchiveHelper.ts
  backend/handler/AuthHandler.ts
  backend/handler/AuthHandler.types.ts
  backend/handler/BackendHandler.ts
  backend/handler/FilterHandler.ts
  backend/handler/FilterHandler.types.ts
  backend/handler/GitHubHandler.ts
  backend/handler/SourceHandler.ts
  backend/handler/SourceHandler.types.ts
  backend/handler/TerraformHandler.ts
  backend/handler/TerraformHandler.types.ts
  backend/handler/WidgetsHandler.ts
  backend/handler/WidgetsHandler.types.ts
  backend/handler/templates/PageGroupsHandler.ts
  backend/handler/templates/PagesHandler.ts
  backend/handler/templates/TemplatesHandler.ts
  backend/handler/templates/types.ts
  backend/jest.config.js
  backend/migrations/20201030110539-5_1_1-MigratePageLayouts.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Auth.ts
  backend/routes/Auth.types.ts
  backend/routes/External.ts
  backend/routes/Filters.types.ts
  backend/routes/GitHub.ts
  backend/routes/GitHub.types.ts
  backend/routes/Plugins.ts
  backend/routes/SourceBrowser.types.ts
  backend/routes/Templates.ts
  backend/routes/Templates.types.ts
  backend/routes/Terraform.ts
  backend/routes/Terraform.types.ts
  backend/routes/UserApp.ts
  backend/routes/UserApp.types.ts
  backend/routes/Widgets.ts
  backend/routes/Widgets.types.ts
  backend/test/handlers/templates/PageGroupsHandler.test.ts
  backend/utils.ts
  test/cypress/integration/edit_mode_spec.ts
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/tenants_spec.ts
  test/cypress/integration/widgets/user_defined_widgets_spec.ts
  test/cypress/support/widgets.ts
  test/jest/utils/widgetDefinitionsLoader.test.ts
  widgets/common/src/terraformModal/TerraformActions.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformVariableNameInput.tsx
Labels: bug-fix, internal

#2175 RD-5448 Replace marketplace default table mode to catalog mode
  templates/pages/blueprintMarketplace.json
  widgets/blueprintCatalog/src/widget.tsx
Labels: internal

#2186 RD-5788 Migrate User Management widget to TypeScript
  app/translations/en.json
  app/utils/stageUtils.ts
  app/utils/types.ts
  backend/handler/AuthHandler.types.ts
  widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
  widgets/common/src/deploymentsView/header/index.tsx
  widgets/common/src/deploymentsView/map/common.ts
  widgets/common/src/deploymentsView/map/container.tsx
  widgets/common/src/deploymentsView/map/marker/tooltip.tsx
  widgets/common/src/roles/types.ts
  widgets/common/src/roles/utils.ts
  widgets/common/src/tenants/TenantsDropdown.tsx
  widgets/common/src/tenants/index.ts
  widgets/common/src/tenants/utils.ts
  widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.tsx
  widgets/userGroups/src/CreateModal.tsx
  widgets/userManagement/src/ActionsMenu.tsx
  widgets/userManagement/src/CreateModal.tsx
  widgets/userManagement/src/GroupModal.tsx
  widgets/userManagement/src/IsAdminCheckbox.tsx
  widgets/userManagement/src/MenuAction.tsx
  widgets/userManagement/src/TenantModal.tsx
  widgets/userManagement/src/UserDetails.tsx
  widgets/userManagement/src/UsersTable.tsx
  widgets/userManagement/src/actions.ts
  widgets/userManagement/src/getWidgetT.ts
  widgets/userManagement/src/props/UserPropType.ts
  widgets/userManagement/src/widget.tsx
  widgets/userManagement/src/widget.types.ts
Labels: internal

#2185 RD-4255 Made dynamic dropdown reset search query on focus
  widgets/common/src/components/DynamicDropdown.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
Labels: bug-fix

#2188 RD-3487: Modify checkbox styling
  jenkins/build-pod.yaml
  semantic-ui/site/modules/checkbox.overrides.less
  semantic-ui/site/modules/checkbox.variables.less
Labels: feature

#2189 RD-5448 fix user_spec
  test/cypress/integration/flows/user_spec.ts
Labels: bug-fix

#2187 RD-5449 A github icon to replace the link location to github
  test/cypress/integration/flows/user_spec.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprintCatalog/src/widget.css
Labels: feature

#2190 RD-5752 Reuse backend types in frontend package
  app/actions/pageMenu.ts
  app/actions/userApp.ts
  app/actions/userAppCommon.ts
  app/actions/widgets.ts
  app/components/ContactDetailsModal/useModalOpenState.ts
  app/components/GettingStartedModal/installation/process.ts
  app/components/templateManagement/TemplateManagement.tsx
  app/utils/External.ts
  app/utils/auth.ts
  app/utils/templatesLoader.ts
  app/utils/widgetDefinitionsLoader.ts
  backend/db/models/UserAppsModel.types.ts
  backend/handler/FilterHandler.ts
  backend/routes/GitHub.types.ts
  backend/routes/Plugins.ts
  backend/routes/Plugins.types.ts
  backend/routes/Widgets.ts
  backend/routes/Widgets.types.ts
  widgets/blueprintCatalog/src/actions.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/blueprintSources/src/actions.ts
  widgets/common/src/actions/FileActions.ts
  widgets/common/src/blueprints/BlueprintActions.ts
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/filters/FilterActions.ts
  widgets/common/src/plugins/PluginActions.ts
  widgets/common/src/plugins/UploadPluginForm.tsx
  widgets/common/src/terraformModal/TerraformActions.ts
  widgets/plugins/src/widget.tsx
  widgets/pluginsCatalog/src/Actions.ts
  widgets/topology/src/DataFetcher.ts
  widgets/topology/src/Topology.tsx
  widgets/topology/src/widget.tsx
Labels: bug-fix, internal

#2194 CD-7 Update widget documentation
  widgets/agents/README.md
  widgets/blueprintUploadButton/README.md
  widgets/deployments/README.md
Labels: internal
