Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-12, with the labels that each got.

#2294 RD-6501: Fixed pages_spec system test
  test/cypress/integration/templateManagement/pages_spec.ts
Labels: bug-fix, internal

#2291 RD-5753 Fully migrating `app/utils` directory to typescript
  app/actions/userApp.ts
  app/utils/External.ts
  app/utils/Interceptor.ts
  app/utils/Internal.ts
  app/utils/LoaderUtils.ts
  app/utils/Manager.ts
  app/utils/StatusPoller.ts
  app/utils/StyleLoader.ts
  app/utils/UserAppDataAutoSaver.ts
  app/utils/WidgetBackend.ts
  app/utils/WidgetParamsHandler.ts
  app/utils/encodeTextToBase64.ts
  app/utils/scriptLoader.ts
  app/utils/shared/JsonUtils.ts
Labels: internal

#2297 RD-5756 Migrate `shared` components to TypeScript - part 1
  app/components/layout/GridItem.tsx
  app/components/shared/Link.ts
  app/components/shared/MaintenanceModeActivationButton.tsx
  app/components/shared/PasswordModal.tsx
  app/components/shared/graphs/Graph.tsx
  app/components/shared/graphs/PieGraph.tsx
  app/components/shared/widgets/WidgetsGrid.tsx
  test/cypress/components/app/Graph_spec.tsx
  widgets/executionsStatus/src/widget.tsx
Labels: internal

#2298 RD-6099 Add support for tenant and role selection in Invite modal
  app/translations/en.json
  test/cypress/integration/widgets/user_management_spec.ts
  widgets/userManagement/src/InviteModal.tsx
  widgets/userManagement/src/authServiceActions.ts
Labels: feature

#2299 RD-6497 Skip failing tests
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: internal

#2300 RD-6500 Test fix
  test/cypress/integration/widgets/deployments_view_spec.ts
Labels: internal

#2301 RD-6465: Fixed incorrect parameters passing
  widgets/common/src/actions/SearchActions.ts
Labels: bug-fix

#2268 RD-5773 - Migration of inputs widget
  app/translations/en.json
  widgets/inputs/src/InputsTable.tsx
  widgets/inputs/src/widget.tsx
Labels: internal

#2230 RD-5755 Part 2 improve ClusterServiceStatus
  app/actions/manager/clusterStatus.ts
  app/components/shared/cluster/ClusterServicesOverview.tsx
  app/components/shared/cluster/ClusterStatusIcon.tsx
  app/components/shared/cluster/consts.ts
  app/components/shared/cluster/types.ts
  app/components/sidebar/HealthIndicator.tsx
  app/components/status/SystemServicesStatus.tsx
  app/components/status/SystemStatusIcon.tsx
  app/containers/status/SystemStatusIcon.ts
  app/reducers/managerReducer/clusterStatusReducer.ts
  test/cypress/integration/cluster_status_spec.ts
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/spire_manager_spec.ts
  test/cypress/support/cluster_status_commons.ts
  test/jest/components/SystemStatusIcon.test.tsx
  widgets/managers/src/StatusIcon.tsx
Labels: internal

#2308 RD-6508 Test fix
  test/cypress/integration/edit_mode_spec.ts
Labels: bug-fix, internal

#2306 RD-6523 Test fix
  test/cypress/integration/page_spec.ts
Labels: bug-fix, internal

#2307 RD-5755 PR-3 Migrate components
  app/components/shared/cluster/types.ts
  app/components/status/SystemServicesStatus.tsx
  app/components/status/SystemStatusHeader.tsx
Labels: internal

#2302 RD-6522, RD-6526 Fixed issues appearing in executions and edit_mode specs
  app/utils/Internal.ts
  app/utils/LoaderUtils.ts
  app/utils/WidgetBackend.ts
Labels: bug-fix

#2312 RD-6540 Test fix
  test/cypress/integration/widgets/filter_spec.ts
Labels: bug-fix, internal

#2313 RD-6527 Tests fix
  test/cypress/support/templates.ts
Labels: bug-fix, internal

#2304 RD-6497 Re-enable tests due to fixed manager issue
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: internal

#2305 RD-6525 Move `SERVER_HOST` and `SERVER_PORT` constants to JSON configuration file
  backend/config.ts
  backend/server.ts
  conf/README.md
  conf/app.json
  devServer.ts
  tsconfig.json
Labels: feature, internal

#2310 RD-5755 Part 4 move `app/containers/status` to `app/components/status`
  app/components/maintenance/MaintenanceModePageMessage.tsx
  app/components/sidebar/HealthIndicator.tsx
  app/components/status/SystemServicesStatus.tsx
  app/components/status/SystemStatusHeader.tsx
  app/components/status/SystemStatusIcon.tsx
  app/containers/status/SystemServicesStatus.ts
  app/containers/status/SystemStatusHeader.ts
  app/containers/status/SystemStatusIcon.ts
  test/jest/components/SystemStatusIcon.test.tsx
Labels: internal

#2303 RD-6361 Create basic Secret Providers widget
  app/translations/en.json
  backend/test/handlers/WidgetHandler.test.ts
  templates/pages/resources.json
  templates/pages/secrets.json
  test/cypress/fixtures/community/manager.json
  test/cypress/fixtures/secret_providers/secret_providers.json
  test/cypress/integration/widgets/secretProviders_spec.ts
  test/jest/resources/rbac.ts
  widgets/secretProviders/src/SecretProvidersTable.consts.ts
  widgets/secretProviders/src/SecretProvidersTable.tsx
  widgets/secretProviders/src/widget.tsx
  widgets/secretProviders/src/widget.types.ts
Labels: feature

#2311 RD-6180 Remove passing `bordered` prop from icons
  app/translations/en.json
  package-lock.json
  package.json
  widgets/blueprintCatalog/src/RepositoryLinkButton.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/common/src/deployments/DeploymentActionsMenu.tsx
  widgets/common/src/executeWorkflow/WorkflowsMenu.tsx
  widgets/filters/src/FiltersTable.tsx
  widgets/labels/src/LabelsTable.tsx
  widgets/managers/src/ConsoleIcon.tsx
  widgets/managers/src/RefreshIcon.tsx
  widgets/nodes/src/NodeInstancesTable.tsx
  widgets/nodes/src/NodesTable.tsx
  widgets/plugins/src/PluginsTable.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/sites/src/SitesTable.tsx
  widgets/snapshots/src/SnapshotsTable.tsx
  widgets/tokens/src/RemoveTokenButton.tsx
Labels: feature

#2322 upgraded docs
  widgets/agents/README.md
Labels: bug-fix

#2292 RD-5760 Part 1 - Migrate files from containers directory and related components to TypeScript
  app/components/AddWidgetModal.tsx
  app/components/AuthRoutes.tsx
  app/components/ErrorPage.tsx
  app/components/LicensePage.tsx
  app/components/LinkToLogin.tsx
  app/components/LogoPage.tsx
  app/components/NoTenants.tsx
  app/components/Tabs.tsx
  app/components/shared/widgets/PageContent.tsx
  app/containers/AddWidget.ts
  app/containers/ErrorPage.ts
  app/containers/LicensePage.ts
  app/containers/LinkToLogin.ts
  app/containers/ResourceVisibility.ts
  app/containers/VisibilityField.ts
  app/reducers/managerReducer/authReducer.ts
  app/utils/StageAPI.ts
  app/utils/types.ts
  backend/handler/AuthHandler.types.ts
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/support/commands.ts
  test/jest/components/Banner.test.tsx
  test/jest/components/LicensePage.test.tsx
  test/jest/resources/licenses.ts
  test/jest/resources/versions.ts
Labels: internal

#2245 RD-5758 Migrate app framework - `maintenance` components
  app/actions/manager/maintenance.ts
  app/components/AuthRoutes.tsx
  app/components/maintenance/MaintenanceModePageMessage.tsx
  app/components/shared/MaintenanceModeActivationButton.tsx
  app/components/shared/MaintenanceModeModal.tsx
  app/containers/maintenance/MaintenanceModePageMessage.ts
  app/reducers/managerReducer/managerReducer.ts
  app/utils/StatusPoller.ts
  app/utils/shared/ExecutionUtils.ts
  widgets/maintenanceModeButton/src/MaintenanceModeButton.tsx
Labels: internal

#2327 RD-6222 Fix input default values handling when updating deployment to another blueprint
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/common/src/deployments/UpdateDeploymentModal.tsx
Labels: bug-fix

#2330 RD-6490 Remove built-in widgets border color and border shadow
  app/styles/style.scss
  app/utils/StageAPI.ts
  app/utils/normalizeWidgetDefinition.ts
  app/widgets/common/deploymentsView/configuration.ts
  widgets/agents/src/widget.tsx
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprintInfo/src/widget.tsx
  widgets/blueprintNum/src/widget.tsx
  widgets/blueprintSources/src/widget.tsx
  widgets/blueprints/src/widget.tsx
  widgets/cloudNum/src/widget.tsx
  widgets/deploymentNum/src/widget.tsx
  widgets/deployments/src/widget.tsx
  widgets/events/src/widget.tsx
  widgets/eventsFilter/src/widget.tsx
  widgets/executionNum/src/widget.tsx
  widgets/executions/src/widget.tsx
  widgets/executionsStatus/src/widget.tsx
  widgets/filter/src/widget.tsx
  widgets/filters/src/widget.tsx
  widgets/highAvailability/src/widget.tsx
  widgets/inputs/src/widget.tsx
  widgets/labels/src/widget.tsx
  widgets/managers/src/widget.tsx
  widgets/nodes/src/widget.tsx
  widgets/nodesComputeNum/src/widget.tsx
  widgets/nodesStats/src/widget.tsx
  widgets/onlyMyResources/src/widget.tsx
  widgets/outputs/src/widget.tsx
  widgets/plugins/src/widget.tsx
  widgets/pluginsCatalog/src/widget.tsx
  widgets/pluginsNum/src/widget.tsx
  widgets/secrets/src/widget.tsx
  widgets/serversNum/src/widget.tsx
  widgets/sites/src/widget.tsx
  widgets/sitesMap/src/widget.tsx
  widgets/snapshots/src/widget.tsx
  widgets/tenants/src/widget.tsx
  widgets/topology/src/widget.tsx
  widgets/userGroups/src/widget.tsx
  widgets/userManagement/src/widget.tsx
Labels: feature

#2329 RD-6521 Remove border and header from Blueprints Catalog widget
  .size-limit
  test/cypress/fixtures/pages/page_with_tabs.json
  test/cypress/integration/page_spec.ts
  widgets/blueprintCatalog/src/widget.tsx
  widgets/blueprintCatalog/widget.png
Labels: feature

#2333 RD-6160 Widget rendering error when deploying a blueprint
  app/widgets/common/secrets/MissingSecretsError.tsx
Labels: bug-fix

#2323 RD-6235 Extended /external endpoint to handle relative urls
  backend/routes/External.ts
  backend/test/routes/External.test.ts
  widgets/blueprintCatalog/README.md
Labels: feature

#2315 RD-6363 Add support for deleting Secret Provider
  app/translations/en.json
  test/cypress/fixtures/secret_providers/secret_providers.json
  test/cypress/integration/widgets/secretProviders_spec.ts
  test/cypress/integration/widgets/secret_providers_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/secret_providers.ts
  widgets/secretProviders/src/RemoveSecretProviderButton.tsx
  widgets/secretProviders/src/SecretProvidersTable.tsx
  widgets/secretProviders/src/widget.consts.ts
  widgets/secretProviders/src/widget.tsx
  widgets/secretProviders/src/widget.utils.ts
Labels: feature

#2331 RD-5515 Fix default resource location selection
  app/widgets/common/terraformModal/TerraformModal.tsx
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: bug-fix

#2334 RD-6335 Add support for `operation_name` workflow parameter type
  app/translations/en.json
  app/widgets/common/inputs/InputField.tsx
  app/widgets/common/inputs/fields/OperationNameInputField.tsx
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
Labels: feature

#2336 RD-6162 Fix for empty labels in terraform modal
  app/widgets/common/terraformModal/TerraformModal.tsx
Labels: bug-fix

#2332 RD-6585 Fixed sorting in outputs table
  widgets/outputs/src/OutputsTable.tsx
Labels: bug-fix

#2338 RD-6162 Fix for empty labels in deployments view widget configuration modal
  app/widgets/common/deploymentsView/configuration.ts
  app/widgets/common/deploymentsView/index.ts
  app/widgets/common/deploymentsView/table/DeploymentsTable.tsx
  app/widgets/common/deploymentsView/table/columns.tsx
  app/widgets/common/deploymentsView/table/renderDeploymentRow.tsx
  widgets/deploymentsView/src/widget.tsx
  widgets/deploymentsViewDrilledDown/src/widget.tsx
Labels: bug-fix

#2343 RD-6532 Remove empty input default
  app/widgets/common/terraformModal/TerraformModal.tsx
  backend/templates/terraform/inputs.ejs
  backend/test/routes/fixtures/terraform/1_blueprint.yaml
  backend/test/routes/fixtures/terraform/1_inputs.json
Labels: feature

#2341 RD-6485 Add support for sorting deployment inputs and workflow parameters
  app/translations/en.json
  app/widgets/common/deployModal/DeploymentInputs.tsx
  app/widgets/common/executeWorkflow/ExecuteWorkflowInputs.tsx
  app/widgets/common/inputs/DataTypesButton.tsx
  app/widgets/common/inputs/InputFields.tsx
  app/widgets/common/inputs/SortOrderIcons.tsx
  app/widgets/common/inputs/fields/BlueprintIdInputField.tsx
  app/widgets/common/inputs/fields/CapabilityValueInputField.tsx
  app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
  app/widgets/common/inputs/fields/NodeIdInputField.tsx
  app/widgets/common/inputs/fields/NodeInstanceInputField.tsx
  app/widgets/common/inputs/fields/NodeTypeInputField.tsx
  app/widgets/common/inputs/fields/OperationNameInputField.tsx
  app/widgets/common/inputs/fields/ScalingGroupInputField.tsx
  app/widgets/common/inputs/fields/SecretKeyInputField.tsx
  app/widgets/common/inputs/fields/useFetchUrlWithDeploymentId.ts
  app/widgets/common/inputs/utils/translateInputs.ts
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/support/commands.ts
Labels: feature

#2342 RD-6531 Disable value input when selecting existing secret
  app/widgets/common/components/DynamicDropdown.tsx
  app/widgets/common/terraformModal/TerraformModal.tsx
  app/widgets/common/terraformModal/TerraformVariableNameInput.tsx
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: feature

#2324 RD-6385 Introducing "Deploy On" dropdown to Create Deployment modal
  app/translations/en.json
  app/widgets/common/actions/SearchActions.ts
  app/widgets/common/blueprints/BlueprintActions.ts
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/deployModal/GenericDeployModal.utils.ts
  app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
  test/cypress/fixtures/blueprints/deploy_on.zip
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: bug-fix, feature

#2344 RD-6325 Add support for `get_secrets` used as `valid_values` constraint
  app/translations/en.json
  app/widgets/common/inputs/InputField.tsx
  app/widgets/common/inputs/fields/ValueListInputField.tsx
  app/widgets/common/secrets/SecretActions.ts
  app/widgets/common/secrets/SecretsModal.tsx
  app/widgets/common/terraformModal/TerraformModal.tsx
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/secrets/src/UpdateModal.tsx
Labels: feature

#2347 RD-6627 Modified input selector
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix

#2348 RD-6341 Allow absolute paths for backend type imports
  app/actions/manager/auth.ts
  app/actions/manager/license.ts
  app/actions/manager/maintenance.ts
  app/actions/manager/tenants.ts
  app/actions/manager/version.ts
  app/actions/page.ts
  app/actions/pageMenu.ts
  app/actions/templateManagement/pages.ts
  app/actions/templateManagement/templates.ts
  app/actions/userApp.ts
  app/actions/widgetDefinitions.ts
  app/components/AddWidgetModal.tsx
  app/components/ContactDetailsModal/useModalOpenState.ts
  app/components/GettingStartedModal/installation/process.ts
  app/components/GettingStartedModal/plugins/model.ts
  app/components/LicensePage.tsx
  app/components/LoginPage.tsx
  app/components/license/CurrentLicense.tsx
  app/components/license/CurrentVersion.tsx
  app/components/templateManagement/TemplateManagement.tsx
  app/components/templateManagement/pageGroups/PageGroups.tsx
  app/components/templateManagement/templates/Templates.tsx
  app/configureStore.ts
  app/reducers/configReducer.ts
  app/reducers/managerReducer/licenseReducer.ts
  app/reducers/managerReducer/managerReducer.ts
  app/tsconfig.json
  app/utils/ConfigLoader.ts
  app/utils/Manager.ts
  app/utils/StageAPI.ts
  app/utils/WidgetParamsHandler.ts
  app/utils/auth.ts
  app/utils/layoutDefinitionsLoader.ts
  app/utils/shared/PluginUtils.ts
  app/utils/shared/UrlUtils.ts
  app/utils/widgetDefinitionsLoader.ts
  app/widgets/common/actions/FileActions.ts
  app/widgets/common/blueprints/BlueprintActions.ts
  app/widgets/common/filters/FilterActions.ts
  app/widgets/common/plugins/PluginActions.ts
  app/widgets/common/plugins/UploadPluginForm.tsx
  app/widgets/common/terraformModal/TerraformActions.ts
  app/widgets/common/terraformModal/TerraformModal.tsx
  app/widgets/common/terraformModal/TerraformVariableNameInput.tsx
  test/jest/components/Banner.test.tsx
  test/jest/components/LicensePage.test.tsx
  test/jest/resources/licenses.ts
  test/jest/resources/versions.ts
  test/jest/tsconfig.json
  widgets/blueprintCatalog/src/actions.ts
  widgets/blueprintSources/src/actions.ts
  widgets/pluginsCatalog/src/Actions.ts
  widgets/pluginsCatalog/src/types.ts
  widgets/topology/src/DataFetcher.ts
  widgets/topology/src/Topology.tsx
  widgets/tsconfig.json
  widgets/userGroups/src/widget.types.ts
  widgets/userManagement/src/widget.types.ts
Labels: internal

#2349 RD-6630 Fixed version of the blueprint example link
  app/components/shared/widgets/PageContent.tsx
  test/cypress/support/resource_urls.ts
Labels: bug-fix

#2346 RD-6232 In the detaills of the root node is not shown
  app/translations/en.json
  test/cypress/integration/widgets/blueprint_sources_spec.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
Labels: bug-fix

#2340 RD-6362 add support for creating vault secret provider
  app/translations/en.json
  app/utils/consts.ts
  app/widgets/common/Consts.ts
  app/widgets/common/terraformModal/TerraformModal.tsx
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/secret_providers_spec.ts
  test/cypress/support/secret_providers.ts
  widgets/secretProviders/src/CreateSecretProviderModal.tsx
  widgets/secretProviders/src/RemoveSecretProviderButton.tsx
  widgets/secretProviders/src/SecretProvidersTable.tsx
  widgets/secretProviders/src/widget.types.ts
Labels: feature

#2350 RD-6660: Modify input selector
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix

#2353 RD-4791 Add endpoint for getting/restoring ua snapshots
  backend/app.ts
  backend/routes/Snapshots.ts
  backend/test/routes/Snapshots.test.ts
Labels: internal

#2354 RD-4793 RD-4794 Add snapshot support for templates and pages
  app/components/templateManagement/TemplateManagement.tsx
  backend/handler/templates/PagesHandler.ts
  backend/handler/templates/TemplatesHandler.ts
  backend/handler/templates/types.ts
  backend/routes/Snapshots.ts
  backend/routes/Templates.ts
  backend/routes/Templates.types.ts
  backend/test/routes/Snapshots.test.ts
  backend/test/routes/Templates.test.ts
Labels: internal
