Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-03, with the labels that each got.

#1859 RD-3825: Resolved most of packages prone to ansi-regex vulnerability
  package-lock.json
Labels: dependencies

#1858 Rd 3825 Upgrade webpack dev server
  devServer.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies

#1860 RD-1962: Migrate npm to the 8th version
  backend/package-lock.json
  package-lock.json
Labels: dependencies, internal

#1633 RD-3119 Migrate backend DB models and migration scripts to TS
  app/actions/page.ts
  app/tsconfig.json
  app/utils/StageAPI.ts
  backend/consts.ts
  backend/db/Connection.ts
  backend/db/models/ApplicationsModel.js
  backend/db/models/ApplicationsModel.ts
  backend/db/models/BlueprintAdditionsModel.js
  backend/db/models/BlueprintAdditionsModel.ts
  backend/db/models/BlueprintUserDataModel.js
  backend/db/models/BlueprintUserDataModel.ts
  backend/db/models/ClientConfigsModel.js
  backend/db/models/ClientConfigsModel.ts
  backend/db/models/ResourcesModel.js
  backend/db/models/ResourcesModel.ts
  backend/db/models/UserAppsModel.js
  backend/db/models/UserAppsModel.ts
  backend/db/models/WidgetBackendsModel.js
  backend/db/models/WidgetBackendsModel.ts
  backend/db/models/types.ts
  backend/db/types/ResourceTypes.js
  backend/db/types/ResourceTypes.ts
  backend/handler/ArchiveHelper.ts
  backend/handler/BackendHandler.ts
  backend/handler/FilterHandler.ts
  backend/handler/SourceHandler.ts
  backend/handler/WidgetsHandler.ts
  backend/migrations/20170425132017-4_0-init.ts
  backend/migrations/20170523102924-4_1.ts
  backend/migrations/20170808104541-4_2-ResourceModelPageEnum.ts
  backend/migrations/20170808104541-4_2-UserAppsTenantColumn.ts
  backend/migrations/20170810122415-4_2-UserAppsModeCommunityValue.ts
  backend/migrations/20170821121958-4_2-ResourceModelJsonField.ts
  backend/migrations/20171011082922-4_2-UserAppsRoleColumnRemoval.ts
  backend/migrations/20190401111659-5_0-MovePageResourcesToFiles.ts
  backend/migrations/20190401130022-5_0-MoveTemplatesResourcesToFiles.ts
  backend/migrations/20190401130043-5_0-RemoveResourcesTable.ts
  backend/migrations/20190423064931-5_0-CreateWidgetBackendTable.ts
  backend/migrations/20200123095213-5_1-CreateBlueprintUserData.ts
  backend/migrations/20201030110539-5_1_1-MigratePageLayouts.js
  backend/migrations/20201030110539-5_1_1-MigratePageLayouts.ts
  backend/migrations/20201230113319-5_1_1-UpdateManagerIp.js
  backend/migrations/20201230113319-5_1_1-UpdateManagerIp.ts
  backend/migrations/20210519093609-6_0-UserAppsManagerIpColumnRemoval.ts
  backend/migrations/20210929110911-6_3-UserAppsPageGroups.ts
  backend/migrations/common/types.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Applications.ts
  backend/routes/BlueprintAdditions.ts
  backend/routes/BlueprintUserData.ts
  backend/routes/ClientConfig.ts
  backend/routes/Templates.types.ts
  backend/routes/UserApp.ts
  backend/server.ts
  backend/serverSettings.ts
  backend/test/handlers/ArchiveHelper.test.ts
  backend/test/server.test.ts
  templates/schemas/page.schema.json
Labels: internal

#1865 RD-4253: Display Form.TextArea on textarea type + refactoring
  test/jest/widgets/common/InputUtils.test.tsx
  widgets/common/src/InputsUtils.tsx
Labels: feature

#1867 RD-4030: Introduce downloading blueprint button
  .gitignore
  app/translations/en.json
  templates/pages/blueprint.json
  test/cypress/integration/widgets/blueprint_actions_spec.ts
  test/cypress/support/asserts.ts
  widgets/blueprintActionButtons/README.md
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
Labels: feature

#1868 RD-4422 Update token endpoint
  backend/handler/AuthHandler.ts
  backend/package-lock.json
  backend/package.json
Labels: internal

#1869 RD-4258: Provided additional terraform versions
  widgets/blueprints/src/terraformVersions.ts
Labels: feature

#1872 RD-3975: Implemented retrying mechanism for the flaky tests
  test/cypress/integration/login_spec.ts
Labels: bug-fix

#1871 RD-3672: Implemented retrying mechanism for the flaky tests
  test/cypress/integration/edit_mode_spec.ts
Labels: bug-fix

#1862 RD-382 Migrate from `request` to `axios` in stage backend
  app/utils/External.ts
  backend/handler/ArchiveHelper.ts
  backend/handler/AuthHandler.ts
  backend/handler/ManagerHandler.ts
  backend/handler/RequestHandler.ts
  backend/handler/services/RequestService.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/External.ts
  backend/routes/GitHub.ts
  backend/routes/Maps.ts
  backend/routes/Plugins.ts
  backend/routes/ServerProxy.ts
  backend/routes/Terraform.ts
  backend/test/handlers/ArchiveHelper.test.ts
  backend/test/handlers/RequestHandler.test.ts
  backend/test/handlers/services/RequestService.test.ts
  backend/test/routes/GitHub.test.ts
  backend/test/routes/Maps.test.ts
  backend/test/routes/Plugins.test.ts
  backend/test/routes/ServerProxy.test.ts
  package-lock.json
  test/cypress/support/commands.ts
Labels: dependencies, internal

#1870 RD-382 Migrate from `request` to `axios` in stage scripts
  package-lock.json
  package.json
  scripts/updateReadmes.js
Labels: dependencies, internal

#1874 RD-4450 Update version of `cloudify-ui-common` package in backend
  backend/package-lock.json
  backend/package.json
Labels: bug-fix

#1876 RD-4454 Fix audit failure
  package-lock.json
Labels: dependencies, internal

#1864 RD-4287 Use button icons in Install section in Create Deployment modal
  widgets/common/src/InputsHeader.tsx
  widgets/common/src/InputsHelpDescription.tsx
  widgets/common/src/InputsHelpIcon.tsx
  widgets/common/src/deployModal/DeploymentInputs.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
Labels: feature

#1805 RD-4051: Running project with one command
  Makefile
  README.md
  conf/me.json.template
  docker-compose.yml
  scripts/loadLatestPremiumDockerImage.sh
Labels: internal

#1878 RD-4492 Update cloudify-ui-common to use proper getAdminToken cy command implementation
  .size-limit
  package-lock.json
  package.json
Labels: bug-fix, internal

#1846 RD-2792: StageAPI - making type field ENUM type
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/EditWidgetModal.tsx
  app/components/shared/DynamicTable.tsx
  app/utils/StageAPI.ts
  package-lock.json
  package.json
  widgets/blueprints/src/TerraformModal.tsx
  widgets/blueprints/src/TerraformVariableValueInput.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/filters/FilterIdDropdown.tsx
Labels: dependencies, internal

#1863 RD-4376 Blueprint tile improvement
  app/translations/en.json
  templates/pages/blueprints.json
  test/cypress/integration/flows/user_spec.ts
  test/cypress/integration/widgets/blueprint_catalog_spec.ts
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
Labels: feature

#1881 RD-4364: Removed Ansible and Terraform from GettingStartedModal options
  app/components/GettingStartedModal/schema/cloudSetup.schema.json
Labels: feature

#1877 RD-4279 RD-4496 Introduce FirstUserJourneyButtons to the deployments widget
  .size-limit
  app/translations/en.json
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/jest/widgets/common/TerraformModal.test.ts
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/common/src/filters/RuleValueInput.tsx
  widgets/common/src/filters/inputs/InstallationStatusValueInput.tsx
  widgets/common/src/filters/inputs/index.ts
  widgets/common/src/filters/inputs/types.ts
  widgets/common/src/filters/types.ts
  widgets/common/src/terraformModal/TerraformActions.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformModalTableAccordion.tsx
  widgets/common/src/terraformModal/TerraformVariableValueInput.tsx
  widgets/common/src/terraformModal/images/terraform-icon.png
  widgets/common/src/terraformModal/index.ts
  widgets/common/src/terraformModal/terraformVersions.ts
  widgets/deployments/src/DeploymentUpdatedIcon.tsx
  widgets/deployments/src/DeploymentsList.tsx
  widgets/deployments/src/DeploymentsTable.tsx
  widgets/deployments/src/FirstUserJourneyButtons/ButtonIcon.tsx
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButton.tsx
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButtons.tsx
  widgets/deployments/src/FirstUserJourneyButtons/images/terraform_logo.png
  widgets/deployments/src/FirstUserJourneyButtons/index.ts
  widgets/deployments/src/FirstUserJourneyButtons/styles.tsx
  widgets/deployments/src/widget.tsx
Labels: feature

#1880 RD-4396 Update dashboard page to show Deployments widget with first user journey buttons
  templates/pages/adminDash.json
Labels: feature

#1879 RD-4118 RD-4125 RD-4528 Added deployment_id and blueprint_id to inputs and workflow parameters. Bug fix - lack of support for .yml files
  app/translations/en.json
  backend/handler/SourceHandler.ts
  test/jest/widgets/common/InputUtils.test.tsx
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/common/src/BlueprintActions.ts
  widgets/common/src/DynamicDropdown.tsx
  widgets/common/src/InputsUtils.tsx
  widgets/common/src/UpdateDeploymentModal.tsx
  widgets/common/src/deployModal/DeploymentInputs.tsx
  widgets/common/src/deployModal/GenericDeployModal.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
  widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
  widgets/deploymentWizardButtons/src/steps/InputsStep.tsx
Labels: bug-fix, feature

#1883 RD-4559: Provided Terraform logo for the FirstUserJourneyButtons
  app/images/terraform_logo-dark.png
  app/images/terraform_logo.png
  templates/pages/adminDash.json
  templates/pages/blueprints.json
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/images/terraform-icon.png
  widgets/deployments/README.md
  widgets/deployments/src/FirstUserJourneyButtons/ButtonIcon.tsx
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButtons.tsx
  widgets/deployments/src/FirstUserJourneyButtons/images/terraform_logo.png
Labels: bug-fix, internal

#1887 RD-4114 Show display_name instead of id only (deployment_id input and workflow parameter improvement)
  widgets/common/src/InputsUtils.tsx
Labels: bug-fix, feature

#1888 RD-4415: Introduced Blueprint Marketplace page
  templates/pages/blueprintMarketplace.json
Labels: feature

#1891 RD-4526 Fix security vulnerabilities issues (`minimist`, `node-forge` packages)
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: internal

#1892 RD-4583 Fix `clickToDrillDown option` test in Deployments widget test
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix

#1893 RD-4118, RD-4253, RD-4121, RD-4114 Tests for new input parameters deployment_id, blueprint_id, textarea
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/integration/widgets/blueprints_spec.ts
  test/cypress/integration/widgets/button_link_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
  test/cypress/integration/widgets/deployment_wizard_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/support/editMode.ts
Labels: internal

#1896 RD-4114: Tests deployment_id, blueprint_id input fields and worflow parameters
  test/cypress/integration/widgets/deployment_button_spec.ts
Labels: bug-fix

#1889 RD-3827 Add cookie-based authentication for some UI backend endpoints
  app/tsconfig.json
  app/utils/Internal.ts
  backend/app.ts
  backend/auth/AuthMiddlewares.ts
  backend/auth/CookieStrategy.ts
  backend/auth/SamlStrategy.ts
  backend/auth/TokenStrategy.ts
  backend/handler/ArchiveHelper.ts
  backend/handler/AuthHandler.ts
  backend/handler/services/ManagerService.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Auth.ts
  backend/routes/Auth.types.ts
  backend/routes/BlueprintAdditions.ts
  backend/routes/ContactDetails.ts
  backend/routes/Plugins.ts
  backend/routes/ServerProxy.ts
  backend/routes/Templates.ts
  backend/routes/Widgets.ts
  backend/test/auth/CookieStrategy.test.ts
  backend/test/auth/SamlStrategy.test.ts
  backend/test/handlers/AuthHandler.test.ts
  backend/test/routes/Plugins.test.ts
  backend/utils.ts
  test/cypress/support/commands.ts
  widgets/executions/src/backend.ts
  widgets/managers/src/backend.ts
Labels: bug-fix

#1894 RD-4416: Provided ability to drilldown to the blueprintMarketplace page
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/deployments/README.md
  widgets/deployments/src/FirstUserJourneyButtons/FirstUserJourneyButtons.tsx
  widgets/deployments/src/widget.tsx
Labels: feature

#1899 RD-4558: Provided additional test scenarios
  test/cypress/integration/widgets/filters_spec.ts
  widgets/common/src/filters/inputs/InstallationStatusValueInput.tsx
Labels: internal

#1902 RD-4589 Add test retries to one test in Templates spec
  test/cypress/integration/templateManagement/templates_spec.ts
Labels: internal
