Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2022-06, with the labels that each got.

#1983 RD-4909 Add migration for `BlueprintAdditions` table removal
  backend/db/Connection.ts
  backend/jest.config.js
  backend/migrations/20170425132017-4_0-init.ts
  backend/migrations/20220527182401-6_4-RemoveBlueprintAdditionsTable.ts
  backend/package-lock.json
  backend/package.json
  backend/test/migration.test.ts
  backend/test/snapshots/6.3.sql
  doc/diagrams/architecture-backend.txt
Labels: breaking-change

#1993 RD-4327 Show tasks graph even when its name does not match workflow name
  widgets/executions/src/backend.ts
  widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.tsx
Labels: bug-fix

#1978 RD-4493 follow up PR
  .gitignore
  test/cypress/integration/widgets/deployment_button_configuration_spec.ts
  test/cypress/integration/widgets/deployment_button_spec.ts
Labels: feature

#1990 RD-4844: Update all marketplaces to 6.4
  app/components/Tabs.tsx
  app/translations/en.json
  templates/pages/adminDash.json
  templates/pages/blueprintMarketplace.json
  templates/pages/blueprints.json
  widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts
Labels: internal

#1996 RD-5090: Delayed check for the url after having certainty about page redirection
  test/cypress/integration/widgets/deployment_button_spec.ts
Labels: bug-fix

#1994 RD-4630 - Ensure displaying contact details form
  .eslintignore
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/utils.ts
  app/translations/en.json
  backend/routes/ContactDetails.ts
  backend/test/routes/ContactDetails.test.ts
Labels: feature, internal

#1992 RD-1877: extract allowedSettingsTo
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/common/src/Consts.ts
  widgets/common/src/deployments/DeploymentDetails.tsx
  widgets/plugins/src/PluginsTable.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/sites/src/SitesTable.tsx
Labels: feature

#1999 RD-2608 RD-2537 Upgrade typescript eslint plugin and prettier to support TS 4.3
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/installation/tasks.ts
  app/components/Home.tsx
  app/components/basic/index.ts
  app/components/shared/DynamicTable.tsx
  app/components/shared/graphs/Graph.tsx
  app/components/shared/widgets/Widget.tsx
  app/components/templateManagement/templates/CreateTemplateModal.tsx
  app/utils/Toolbox.ts
  backend/routes/ContactDetails.ts
  package-lock.json
  package.json
  test/cypress/integration/widgets/cluster_status_spec.ts
  test/cypress/integration/widgets/filters_spec.ts
  test/cypress/integration/widgets/maintenance_mode_button_spec.ts
  widgets/common/src/deployments/UpdateDetailsModal.tsx
  widgets/common/src/deploymentsView/map/DeploymentsMap.tsx
  widgets/common/src/deploymentsView/map/marker/cluster.tsx
  widgets/common/src/deploymentsView/map/marker/single-deployment-site.tsx
  widgets/common/src/deploymentsView/table/columns.tsx
  widgets/common/src/deploymentsView/table/renderDeploymentRow.tsx
  widgets/common/src/filters/inputs/MultipleStringValuesInput.tsx
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/deploymentWizardButtons/src/steps/PluginsStep.tsx
  widgets/nodes/src/widget.tsx
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
Labels: internal

#1991 RD-2853: Upgrade webpack to the 5th version
  app/utils/consts.ts
  package-lock.json
  package.json
  webpack.config.js
Labels: internal

#2000 RD-5108: Omit HTTP status check
  backend/routes/ContactDetails.ts
  test/cypress/integration/community_spec.ts
Labels: bug-fix

#2001 RD-5028: Updated multer package
  backend/package-lock.json
  backend/package.json
Labels: bug-fix

#1989 RD-4404: Generating ZIP archive based on terraform file - tests
  backend/routes/Terraform.ts
  backend/test/routes/Terraform.test.ts
  backend/test/routes/fixtures/terraform/archive_inputs.json
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: feature, internal

#2005 RD-1836 Rename `lastExecution` code occurrences
  test/cypress/integration/widgets/deployments_spec.ts
  widgets/common/src/executions/LatestExecutionStatusIcon.tsx
  widgets/common/src/executions/index.ts
  widgets/deployments/src/DeploymentsSegment.tsx
  widgets/deployments/src/DeploymentsTable.tsx
  widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.tsx
  widgets/executions/src/widget.tsx
  widgets/managers/src/ManagersTable.tsx
Labels: internal

#2002 RD-1255 Solve uneven whitespace in ID popup
  app/components/shared/IdPopup.tsx
Labels: bug-fix

#2003 RD-1253 Add margin for vertical icons
  widgets/plugins/src/PluginsTable.tsx
Labels: bug-fix

#1997 RD-4405, RD-5003: Terraform Wrapper - autofilling variables and outputs based on terraform module content + bug fix
  app/translations/en.json
  backend/package-lock.json
  backend/package.json
  backend/routes/Terraform.ts
  backend/routes/Terraform.types.ts
  backend/test/routes/Terraform.test.ts
  backend/test/routes/fixtures/terraform/fetch-data-file_inputs.json
  backend/test/routes/fixtures/terraform/fetch-data_inputs.json
  backend/test/routes/fixtures/terraform/template_fetch-data.zip
  package-lock.json
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/common/src/terraformModal/TerraformActions.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#2004 RD-4629: Realignment of the form fields
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsFormField.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
  app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
  app/translations/en.json
  test/cypress/integration/community_spec.ts
Labels: feature

#2007 RD-4924: Terraform Wrapper - Dealing with duplicated secrets and inputs
  backend/routes/Terraform.types.ts
  backend/templates/terraform/inputs.ejs
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: feature

#2010 RD-4405: filling inputs and outputs based on data from terraform file
  widgets/common/src/terraformModal/TerraformModal.tsx
Labels: bug-fix

#2008 RD-4405: Tests - outputs and inputs/variables autoimport
  test/cypress/fixtures/terraform/variables-and-outputs.zip
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: internal

#2016 RD-5226: Fixed test - selecting source module optional
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: bug-fix

#2014 RD-5066 Use new Marketplace API for plugins catalog
  app/components/GettingStartedModal/installation/tasks.ts
  app/components/GettingStartedModal/plugins/model.ts
  app/translations/en.json
  app/utils/shared/PluginUtils.ts
  app/utils/stageUtils.ts
  backend/routes/Plugins.types.ts
  test/cypress/fixtures/widgets/splitViewWidget.tsx
  test/cypress/integration/getting_started_spec.ts
  test/cypress/integration/widgets/deployment_wizard_spec.ts
  test/cypress/integration/widgets/plugins_catalog_spec.ts
  widgets/deploymentWizardButtons/src/steps/PluginsStep.tsx
  widgets/pluginsCatalog/src/PluginsCatalogList.tsx
  widgets/pluginsCatalog/src/types.ts
  widgets/pluginsCatalog/src/widget.tsx
Labels: bug-fix, feature

#1998 RD-4339: Add tenants assignment to user group creation modal
  app/reducers/managerReducer/managerReducer.ts
  app/translations/en.json
  test/jest/utils/Manager.test.ts
  widgets/common/src/index.ts
  widgets/common/src/roles/RolesPicker.tsx
  widgets/common/src/tenants/TenantsDropdown.tsx
  widgets/common/src/tenants/index.ts
  widgets/common/src/tenants/utils.ts
  widgets/userGroups/README.md
  widgets/userGroups/src/CreateModal.tsx
  widgets/userManagement/src/CreateModal.tsx
Labels: feature

#2011 RD-2363 Remove unused pages
  package-lock.json
  templates/pages/ha.json
  templates/pages/systemResources.json
  templates/pages/tmm.json
  test/cypress/integration/templateManagement/templates_spec.ts
Labels: internal

#2017 RD-4339-fix: fix error on admin_spec.ts
  widgets/userManagement/src/CreateModal.tsx
Labels: bug-fix

#2018 RD-5127 Fix test `deployment_button_configuration_spec.ts`
  test/cypress/integration/widgets/deployment_button_configuration_spec.ts
Labels: internal

#2012 RD-4442: Add a link to get premium license from the License page
  app/components/LicensePage.tsx
  app/translations/en.json
  test/cypress/integration/license_spec.ts
Labels: feature

#2015 RD-3666, RD-5188: Use context based error messages
  app/actions/formErrors.ts
  app/actions/types.ts
  app/components/shared/DynamicTable.tsx
  app/reducers/formErrorsReducer.ts
  app/reducers/index.ts
  app/translations/en.json
  app/utils/StageAPI.ts
  app/utils/hooks/index.ts
  app/utils/hooks/useFormErrors.ts
  package-lock.json
  package.json
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/common/src/terraformModal/TerraformModal.css
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/common/src/terraformModal/TerraformModalTableAccordion.tsx
  widgets/common/src/terraformModal/TerraformVariableNameInput.tsx
Labels: dependencies, feature

#2020 RD-5281 Kill running executions before deleting deployments
  test/cypress/integration/flows/user_spec.ts
Labels: bug-fix, internal

#2024 RD-4625: Introduced singleline and multiline inputs for entering secret values
  test/jest/setup.ts
  widgets/common/src/deployments/DeploymentActionsMenu.tsx
  widgets/common/src/index.ts
  widgets/common/src/secrets/InputMaskIcon.tsx
  widgets/common/src/secrets/MultilineInput.tsx
  widgets/common/src/secrets/SecretsModal.tsx
  widgets/common/src/secrets/SinglelineInput.tsx
  widgets/common/src/secrets/index.ts
  widgets/common/src/terraformModal/TerraformModal.tsx
  widgets/deploymentWizardButtons/src/steps/ConfirmationStep.tsx
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/secrets/src/UpdateModal.tsx
Labels: feature

#2026 RD-5071 Use filename from Content-Disposition header when downloading blueprint archives
  app/utils/External.ts
  package-lock.json
  package.json
  test/cypress/fixtures/blueprints/empty.tar
  test/cypress/integration/widgets/blueprint_actions_spec.ts
  test/cypress/support/asserts.ts
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
Labels: bug-fix

#2028 RD-1312: Updated browserslist and babel configuration
  .browserslistrc
  .size-limit
  babel.config.js
  package-lock.json
  package.json
Labels: internal
