Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2023-01, with the labels that each got.

#2345 RD-6158 Empty setup your cloud form
  app/components/GettingStartedModal/GettingStartedModal.tsx
  test/cypress/integration/getting_started_spec.ts
Labels: bug-fix

#2357 RD-5781 migrate Secret widget
  .size-limit
  app/translations/en.json
  app/widgets/common/deploymentsView/table/DeploymentsTable.tsx
  app/widgets/common/secrets/SecretActions.ts
  app/widgets/common/types.ts
  widgets/blueprints/src/types.ts
  widgets/secretProviders/src/SecretProvidersTable.tsx
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/SecretValue.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/secrets/src/UpdateModal.tsx
  widgets/secrets/src/props/SecretPropType.ts
  widgets/secrets/src/types.ts
  widgets/secrets/src/widget.tsx
  widgets/secrets/src/widget.types.ts
  widgets/secrets/src/widget.utils.ts
  widgets/userGroups/src/UserGroupsTable.tsx
  widgets/userManagement/src/UsersTable.tsx
Labels: internal

#2359 RD-6372 create Secret Provider column in Secret widget
  app/translations/en.json
  app/widgets/common/secrets/SecretActions.ts
  widgets/secrets/src/SecretsTable.tsx
Labels: feature

#2355 RD-4792 RD-4793 Add snapshot support for page groups and widgets
  backend/handler/templates/PageGroupsHandler.ts
  backend/handler/widgets/WidgetsHandler.ts
  backend/handler/widgets/installFiles.ts
  backend/handler/widgets/validateUniqueness.ts
  backend/routes/Snapshots.ts
  backend/routes/Templates.ts
  backend/routes/Widgets.ts
  backend/server.ts
  backend/test/handlers/templates/PageGroupsHandler.test.ts
  backend/test/handlers/widgets/WidgetHandler.test.ts
  backend/test/handlers/widgets/installFiles.test.ts
  backend/test/handlers/widgets/validateUniqueness.test.ts
  backend/test/routes/Snapshots.test.ts
  backend/test/routes/fixtures/snapshots/widgets.zip
Labels: internal

#2365 RD-6714 Bump `flat` package
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#2367 RD-6660 Use `setSearchableDropdownValue` custom command for setting blueprint ID value
  test/cypress/integration/widgets/deployments_spec.ts
Labels: internal

#2369 RD-6718: Updated logic behind deployOn feature testing
  test/cypress/fixtures/blueprints/deploy_on.zip
  test/cypress/fixtures/blueprints/deploy_on_environment.zip
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: bug-fix

#2358 RD-4899 Introduce Deploy On functionality on environments page
  .size-limit
  app/translations/en.json
  app/widgets/common/deployModal/DeployBlueprintModal.tsx
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/deployments/DeploymentActions.ts
  app/widgets/common/deployments/DeploymentActionsMenu.consts.ts
  app/widgets/common/deployments/DeploymentActionsMenu.tsx
  app/widgets/common/deployments/DeploymentActionsMenu.utils.ts
  app/widgets/common/deployments/DeploymentActionsModals.tsx
  app/widgets/common/executeWorkflow/ExecuteWorkflowModal.tsx
  test/cypress/integration/widgets/deployment_actions_spec.ts
  widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
  widgets/deploymentActionButtons/src/widget.consts.ts
  widgets/deploymentActionButtons/src/widget.tsx
  widgets/deploymentActionButtons/src/widget.utils.ts
Labels: feature

#2371 RD-6690 Add `useLoginPage` parameter to user configuration
  app/components/Routes.tsx
  backend/config.ts
  backend/routes/Config.types.ts
  backend/test/routes/Config.test.ts
  conf/README.md
  conf/config.json
  conf/userConfig.json
  test/cypress/integration/login_spec.ts
Labels: feature

#2374 RD-6798 align deploymentsAction method from put to post
  app/widgets/common/deployments/DeploymentActions.ts
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix

#2362 RD-5177 Move Getting Started schemas to S3
  app/components/GettingStartedModal/GettingStartedErrorModal.tsx
  app/components/GettingStartedModal/GettingStartedModal.tsx
  app/components/GettingStartedModal/useFetchSchemas.ts
  app/translations/en.json
  test/cypress/components/app/GettingStartedModal_spec.tsx
Labels: feature

#2375 RD-6533 Adjusted buttons appearance
  app/widgets/common/deployModal/DeployModalActions.tsx
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/deploymentButton/src/widget.tsx
Labels: feature

#2376 RD-4790 Add blueprint layouts snapshot endpoints
  backend/routes/Snapshots.ts
  backend/test/routes/Snapshots.test.ts
Labels: internal

#2373 RD-6761 Use `force` parameter when killing an execution
  test/cypress/support/executions.ts
Labels: internal

#2378 RD-6804 Hiding DeployOn dropdown while deploying a blueprint on environments page
  app/widgets/common/deployModal/GenericDeployModal.tsx
  test/cypress/integration/widgets/deployment_actions_spec.ts
Labels: bug-fix

#2370 RD-6370 Add secret from a secret provider UI
  app/translations/en.json
  app/widgets/common/secrets/SecretActions.ts
  test/cypress/integration/widgets/secrets_spec.ts
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/SecretsTable.tsx
Labels: feature

#2381 RD-4796 Add user configuration files snapshot endpoints
  backend/routes/Snapshots.ts
  backend/test/routes/Snapshots.test.ts
  backend/test/routes/snapshots/blueprint-layouts.test.ts
  backend/test/routes/snapshots/configuration.test.ts
  backend/test/routes/snapshots/page-groups.test.ts
  backend/test/routes/snapshots/pages.test.ts
  backend/test/routes/snapshots/templates.test.ts
  backend/test/routes/snapshots/ua.test.ts
  backend/test/routes/snapshots/widgets.test.ts
Labels: internal

#2385 RD-6833 Visit test page explicitly instead of refreshing current page
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
Labels: bug-fix, internal

#2384 RD-6371 - fix issues on system test after change provider to provider_name
  app/widgets/common/secrets/SecretActions.ts
  widgets/secretProviders/src/CreateSecretProviderModal.tsx
  widgets/secretProviders/src/UpdateSecretProviderModal.tsx
  widgets/secretProviders/src/widget.types.ts
  widgets/secrets/src/SecretValue.tsx
Labels: bug-fix

#2386 RD-5761 Migrate application framework components to TypeScript
  app/components/page/content/EmptyContainerMessage.tsx
  app/components/page/editMode/AddWidgetModal.tsx
  app/components/page/editMode/EditModeBubble.tsx
  app/components/page/editMode/EditModeButton.tsx
  app/components/page/editMode/EditTabModal.tsx
  app/components/page/editMode/InstallWidgetModal.tsx
  app/components/routes/ExternalRedirect.tsx
  app/components/routes/LogoPage.tsx
  app/components/routes/NotFoundPage.tsx
Labels: internal

#2387 RD-6709 Add proper authentication and authorization to snapshot endpoints
  backend/app.ts
  backend/auth/AuthMiddlewares.ts
  backend/auth/TokenStrategy.ts
  backend/handler/__mocks__/AuthHandler.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Snapshots.ts
  backend/test/routes/Widgets.test.ts
  backend/test/routes/snapshots/blueprint-layouts.test.ts
  backend/test/routes/snapshots/configuration.test.ts
  backend/test/routes/snapshots/page-groups.test.ts
  backend/test/routes/snapshots/pages.test.ts
  backend/test/routes/snapshots/templates.test.ts
  backend/test/routes/snapshots/ua.test.ts
  backend/test/routes/snapshots/widgets.test.ts
  backend/utils.ts
Labels: internal

#2397 RD-6872 Update `cookiejar` to vulnerability-free patch version
  backend/package-lock.json
Labels: dependencies

#2398 RD-6631 System test fix?
  test/cypress/integration/user_configuration_spec.ts
Labels: bug-fix

#2389 RD-5783 Snapshots widget TS migration
  app/translations/en.json
  widgets/snapshots/src/CreateSnapshotModal.tsx
  widgets/snapshots/src/RestoreSnapshotModal.tsx
  widgets/snapshots/src/SnapshotsTable.tsx
  widgets/snapshots/src/UploadSnapshotModal.tsx
  widgets/snapshots/src/actions.ts
  widgets/snapshots/src/props/SnapshotPropType.ts
  widgets/snapshots/src/widget.common.ts
  widgets/snapshots/src/widget.tsx
  widgets/snapshots/src/widget.types.ts
  widgets/tsconfig.json
Labels: internal

#2394 RD-5784 Tenants widget TS migration
  app/translations/en.json
  app/utils/hooks/useOpenProp.ts
  widgets/tenants/src/GroupsModal.tsx
  widgets/tenants/src/MenuAction.tsx
  widgets/tenants/src/TenantDetails.tsx
  widgets/tenants/src/TenantsTable.tsx
  widgets/tenants/src/UserRoles.tsx
  widgets/tenants/src/UsersModal.tsx
  widgets/tenants/src/actions.ts
  widgets/tenants/src/props/TenantPropType.ts
  widgets/tenants/src/widget.tsx
  widgets/tenants/src/widget.types.ts
Labels: internal

#2392 RD-6409 part 2: BlueprintActionButtons showEditCopyInComposerButton
  widgets/blueprintActionButtons/src/widget.tsx
Labels: feature

#2390 RD-6861 Major refactoring around login/logout procedures
  app/actions/app.ts
  app/actions/manager/auth.ts
  app/actions/userApp.ts
  app/components/page/Page.tsx
  app/components/routes/ApplicationRoutes.tsx
  app/components/routes/AuthRoutes.tsx
  app/components/routes/ErrorPage.tsx
  app/components/routes/ExternalLogin.tsx
  app/components/routes/ExternalRedirect.tsx
  app/components/routes/LinkToLogin.tsx
  app/components/routes/LoginPage.tsx
  app/components/routes/LogoPage.tsx
  app/components/routes/LogoutPage.tsx
  app/components/routes/NoTenantsPage.tsx
  app/components/routes/NotFoundPage.tsx
  app/components/routes/Routes.tsx
  app/components/routes/SmartRedirect.tsx
  app/components/sidebar/UserMenu.tsx
  app/reducers/appReducer.ts
  app/translations/en.json
  app/utils/Interceptor.ts
  app/utils/consts.ts
  app/utils/shared/UrlUtils.ts
  backend/app.ts
  backend/auth/SamlStrategy.ts
  backend/config.ts
  backend/routes/Config.types.ts
  backend/samlSetup.ts
  backend/test/app.test.ts
  backend/test/auth/SamlStrategy.test.ts
  backend/test/routes/Auth.test.ts
  backend/test/routes/Config.test.ts
  backend/test/samlSetup.test.ts
  backend/test/validateAuthConfig.test.ts
  backend/validateAuthConfig.ts
  conf/README.md
  conf/userConfig.json
  test/cypress/components/app/sidebar/UserMenu_spec.tsx
  test/cypress/integration/auth_spec.ts
  test/cypress/integration/login_spec.ts
  test/jest/reducers/managerReducer/managerReducer.test.ts
Labels: bug-fix, feature

#2402 RD-6637 Replace sorting buttons with a dropdown
  app/translations/en.json
  app/widgets/common/inputs/SortOrderIcons.tsx
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: feature

#2396 RD-6386 Introduced functionality of displaying suggested environments
  app/translations/en.json
  app/widgets/common/blueprints/BlueprintActions.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.consts.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.tsx
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.types.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.utils.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdownItemList.tsx
  app/widgets/common/deployModal/EnvironmentDropdown/index.ts
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/deployModal/GenericDeployModal.utils.ts
  app/widgets/common/deploymentsView/DeploymentsView.tsx
  app/widgets/common/deploymentsView/detailsPane/drilldownButtons/SubdeploymentDrilldownButton.consts.ts
  app/widgets/common/deploymentsView/detailsPane/drilldownButtons/SubdeploymentDrilldownButton.tsx
  app/widgets/common/deploymentsView/types.ts
  package-lock.json
  test/cypress/fixtures/blueprints/deploy_on.zip
  test/cypress/fixtures/blueprints/deploy_on_environment.zip
  test/cypress/fixtures/blueprints/deploy_on_with_suggestion.zip
  test/cypress/fixtures/blueprints/deploy_on_without_suggestion.zip
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: feature

#2406 RD-5266 RD-6798 RD-6431 backports
  test/cypress/integration/login_spec.ts
  test/cypress/integration/user_configuration_spec.ts
  test/cypress/integration/widgets/blueprints_terraform_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/support/commands.ts
  test/cypress/support/resource_urls.ts
  widgets/agents/README.md
  widgets/common/src/deployments/DeploymentActions.ts
Labels: internal

#2404 RD-6212 Remove no longer needed prop types interfaces import paths
  app/components/page/content/widgets/dynamicContent/WidgetDynamicContent.tsx
  app/components/page/content/widgets/dynamicContent/WidgetErrorMessage.tsx
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/deployments/DeploymentActionsMenu.tsx
  app/widgets/common/executeWorkflow/ExecuteWorkflowInputs.tsx
  app/widgets/common/executeWorkflow/ExecuteWorkflowModal.tsx
  package-lock.json
  package.json
  test/jest/components/Banner.test.tsx
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/executions/src/ExecutionsTable.tsx
  widgets/secrets/src/CreateModal.tsx
  widgets/tenants/src/TenantsTable.tsx
Labels: internal

#2391 RD-6371 Update secret with secret provider in Secrets widget
  app/translations/en.json
  app/widgets/common/secrets/SecretActions.ts
  test/cypress/integration/widgets/secret_providers_spec.ts
  widgets/secretProviders/src/CreateSecretProviderModal.tsx
  widgets/secretProviders/src/UpdateSecretProviderModal.tsx
  widgets/secretProviders/src/widget.utils.ts
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/UpdateModal.tsx
  widgets/secrets/src/widget.utils.ts
Labels: feature

#2410 RD-6430 Improve killRunningExecutions cypress custom command (#2271)
  test/cypress/support/executions.ts
Labels: internal

#2412 RD-6282 Update links to user documentation
  widgets/README.md
Labels: internal

#2416 RD-6899 Hardened blueprint test
  test/cypress/integration/widgets/blueprint_sources_spec.ts
Labels: internal

#2408 RD-6387: Add documentation for Secret Providers widget
  scripts/readmesConfig.json
  widgets/secretProviders/README.md
  widgets/secretProviders/widget.png
  widgets/secrets/README.md
Labels: feature

#2417 RD-5762 Translation support and lodash explicit imports in Agents widget
  app/translations/en.json
  widgets/agents/src/AgentsTable.tsx
  widgets/agents/src/InstallAgentsModal.tsx
  widgets/agents/src/NodeFilter.tsx
  widgets/agents/src/ValidateAgentsModal.tsx
  widgets/agents/src/utils.tsx
  widgets/agents/src/widget.tsx
Labels: internal

#2418 RD-6911 Fix alignment of "No inputs" message
  app/widgets/common/deployModal/DeploymentInputs.tsx
Labels: bug-fix
