Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2023-03, with the labels that each got.

#2442 RD-6799 - Add custom styling for Tables components
  app/components/common/status/cluster/ClusterService.tsx
  app/components/common/status/cluster/ClusterServicesOverview.tsx
  app/components/common/status/cluster/NodeServices.tsx
  app/components/license/CurrentLicense.tsx
  app/components/license/CurrentVersion.tsx
  app/components/license/LicensePage.tsx
  app/components/sidebar/UserInitialsIcon.tsx
  app/styles/colors.scss
  app/styles/style.scss
  app/widgets/common/components/parameter/ParameterValue.tsx
  app/widgets/common/deployments/UpdateDetailsModal.tsx
  app/widgets/common/executions/LatestExecutionStatusIcon.tsx
  app/widgets/common/inputs/DataTypesButton.tsx
  package-lock.json
  package.json
  semantic-ui/site/collections/menu.overrides.less
  semantic-ui/site/collections/menu.variables.less
  semantic-ui/site/collections/table.overrides.less
  semantic-ui/site/collections/table.variables.less
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprintCatalog/src/RepositoryTable.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/deployments/src/DeploymentsTable.tsx
  widgets/deployments/src/FirstUserJourneyButtons/styles.tsx
  widgets/events/src/EventsTable.tsx
  widgets/executions/src/ExecutionsTable.tsx
  widgets/filters/src/FiltersTable.tsx
  widgets/plugins/src/PluginsTable.tsx
  widgets/secrets/src/SecretValue.tsx
  widgets/secrets/src/SecretsTable.tsx
Labels: feature, internal

#2461 RD-7081 Remove `widgets/common/common.js` reference
  app/utils/widgetDefinitionsLoader.ts
Labels: bug-fix

#2458 RD-6319 - hotfix - adjusted tests for new validation
  test/cypress/integration/widgets/deployment_actions_spec.ts
Labels: bug-fix

#2426 RD-5766 Migration of Deployments widget
  app/widgets/common/actions/SearchActions.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.types.ts
  app/widgets/common/deployments/DeploymentActions.ts
  app/widgets/common/deployments/DeploymentDetails.tsx
  app/widgets/common/deployments/DeploymentDetails.types.ts
  app/widgets/common/deployments/UpdateDeploymentModal.tsx
  app/widgets/common/deploymentsView/DeploymentsView.tsx
  app/widgets/common/deploymentsView/types.ts
  app/widgets/common/executions/ExecutionActions.ts
  app/widgets/common/nodes/NodeInstancesConsts.ts
  widgets/blueprintInfo/src/actions.ts
  widgets/deploymentInfo/src/DeploymentInfo.tsx
  widgets/deploymentInfo/src/widget.tsx
  widgets/deploymentInfo/src/widget.types.ts
  widgets/deployments/src/ActionsMenus.tsx
  widgets/deployments/src/DeploymentsList.tsx
  widgets/deployments/src/DeploymentsSegment.tsx
  widgets/deployments/src/DeploymentsTable.tsx
  widgets/deployments/src/ExecutionProgress.tsx
  widgets/deployments/src/props/DeploymentsViewDefaultProps.ts
  widgets/deployments/src/props/DeploymentsViewPropTypes.ts
  widgets/deployments/src/types.ts
  widgets/deployments/src/widget.tsx
  widgets/nodes/src/widget.tsx
Labels: internal

#2459 RD-6920 Add Create New Environment modal
  .size-limit
  app/translations/en.json
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/labels/LabelsInput.tsx
  app/widgets/common/labels/types.ts
  devServer.ts
  package-lock.json
  package.json
  test/cypress/integration/widgets/environment_button_spec.ts
  test/cypress/support/labels.ts
  widgets/environmentButton/src/BlueprintDefaultFormField.tsx
  widgets/environmentButton/src/CapabilityBlueprintDefaultInput.tsx
  widgets/environmentButton/src/CapabilityValueInput.tsx
  widgets/environmentButton/src/CreateEnvironmentModal.tsx
  widgets/environmentButton/src/EnvironmentButton.tsx
  widgets/environmentButton/src/widget.consts.ts
  widgets/environmentButton/src/widget.types.ts
Labels: feature

#2462 RD-2842: Migrated away from using field placeholders
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/UpdateModal.tsx
  widgets/userManagement/src/GroupModal.tsx
  widgets/userManagement/src/TenantModal.tsx
Labels: bug-fix

#2468 RD-7092 Fix Cloudify Manager REST API port
  backend/test/config.test.ts
  conf/manager.json
Labels: bug-fix

#2470 RD-6920 Updated template
  templates/pages/environments.json
Labels: feature

#2465 RD-6968 styling local blueprints tiles
  app/widgets/common/components/GridWrapper.tsx
  app/widgets/common/components/index.ts
  widgets/blueprintCatalog/src/RepositoryCatalog.tsx
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/widget.css
Labels: internal

#2469 RD-6920 Terraform modal refactoring
  app/actions/formErrors.ts
  app/components/common/DynamicTable.tsx
  app/reducers/formErrorsReducer.ts
  app/reducers/index.ts
  app/utils/hooks/index.ts
  app/utils/hooks/useFormErrors.ts
  app/widgets/common/terraformModal/TerraformModal.tsx
  app/widgets/common/terraformModal/TerraformModalTableAccordion.tsx
  app/widgets/common/terraformModal/TerraformVariableNameInput.tsx
Labels: internal

#2471 RND-96 Add helm wrapper endpoint
  backend/app.ts
  backend/handler/HelmHandler.ts
  backend/handler/HelmHandler.types.ts
  backend/handler/services/BlueprintBuilder.ts
  backend/routes/Helm.ts
  backend/routes/Helm.types.ts
  backend/test/routes/blueprints/Environment.test.ts
  backend/test/routes/blueprints/Helm.test.ts
  backend/test/routes/blueprints/Terraform.test.ts
  backend/test/routes/blueprints/common.ts
  backend/test/routes/blueprints/fixtures/terraform/archive_inputs.json
  backend/test/routes/blueprints/fixtures/terraform/inputs_fetch-data-file.json
  backend/test/routes/blueprints/fixtures/terraform/inputs_fetch-data.json
  backend/test/routes/blueprints/fixtures/terraform/inputs_full.json
  backend/test/routes/blueprints/fixtures/terraform/inputs_minimal.json
  backend/test/routes/blueprints/fixtures/terraform/template.zip
  backend/test/routes/blueprints/fixtures/terraform/template_fetch-data.zip
Labels: feature

#2473 RD-7122: Increased timeout for redirection after blueprint deployment
  test/cypress/integration/widgets/filter_spec.ts
Labels: internal

#2464 RD-7088: Migrated away from using @ts-expect-error annotation
  test/cypress/support/index.ts
  test/jest/utils/External.test.ts
Labels: internal

#2474 RND-96 Add validations and error handling
  .size-limit
  app/translations/en.json
  app/utils/hooks/useErrors.ts
  app/widgets/common/helmModal/ClusterCredentialInput.tsx
  app/widgets/common/helmModal/HelmModal.tsx
  backend/handler/HelmHandler.types.ts
  test/cypress/integration/widgets/blueprints_helm_spec.ts
  widgets/environmentButton/src/CreateEnvironmentModal.tsx
Labels: feature

#2478 RND-96 Disable helm wrapper modal
  test/cypress/integration/widgets/blueprints_helm_spec.ts
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
Labels: feature

#2481 RND-217: Upgraded jest related packages to the newest version
  package-lock.json
  package.json
Labels: dependencies, internal

#2479 RD-6711, RND-209 Seperate environments from services in Blueprints page
  app/components/page/content/PageContent.tsx
  templates/pages/blueprints.json
Labels: bug-fix, feature

#2484 RD-4797 Bypass maintenance when getting user data
  backend/handler/AuthHandler.ts
Labels: feature

#2487 RND-209 fix edit mode spec
  app/components/page/content/PageContent.tsx
Labels: bug-fix

#2477 RD 5758 Migration of Events and Logs Widget
  app/widgets/common/utils/EventUtils.ts
  widgets/events/src/DetailsModal.tsx
  widgets/events/src/EventsTable.tsx
  widgets/events/src/props/ErrorCausesPropType.ts
  widgets/events/src/types.ts
  widgets/events/src/widget.tsx
Labels: internal

#2488 RD-6967: Align blueprint catalog action buttons
  test/cypress/integration/widgets/blueprints_spec.ts
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsCatalogActionButtons.tsx
Labels: feature

#2467 RD-5765 Migrate Blueprint Sources widget
  backend/handler/SourceHandler.ts
  backend/handler/SourceHandler.types.ts
  backend/routes/BlueprintUserData.ts
  backend/routes/SourceBrowser.types.ts
  backend/test/handlers/SourceHandler.test.ts
  widgets/blueprintSources/src/BlueprintSources.tsx
  widgets/blueprintSources/src/widget.tsx
Labels: internal

#2493 RD-6967: Fixed buttons allignment
  widgets/blueprints/src/BlueprintsCatalogActionButtons.tsx
Labels: bug-fix

#2492 RND-96 Remove HELM modal implementation
  app/translations/en.json
  app/widgets/common/helmModal/ClusterCredentialInput.tsx
  app/widgets/common/helmModal/HelmModal.tsx
  app/widgets/common/helmModal/index.ts
  app/widgets/common/index.ts
  backend/app.ts
  backend/handler/HelmHandler.ts
  backend/handler/HelmHandler.types.ts
  backend/routes/blueprints/Helm.ts
  backend/routes/blueprints/Helm.types.ts
  backend/test/routes/blueprints/Helm.test.ts
  devServer.ts
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
Labels: internal

#2485 RND-218 Fix workflow parameters required indicator
  app/widgets/common/executeWorkflow/ExecuteWorkflowInputs.tsx
  app/widgets/common/executeWorkflow/common.ts
  app/widgets/common/inputs/InputFields.tsx
  app/widgets/common/inputs/types.ts
  app/widgets/common/inputs/utils/getInputsWithoutValues.ts
  test/cypress/fixtures/blueprints/workflow_parameters.zip
  test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
Labels: bug-fix

#2496 RD-7117 Stage system tests failed on deployments_spec
  app/widgets/common/deployments/DeploymentActionsMenu.utils.ts
Labels: bug-fix

#2500 RD-7116 Refactor Deployments View widget spec to use Cypress custom commands for setting widget configuration fields
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/support/editMode.ts
Labels: internal

#2503 RD-6316 Update Deployments View widget documentation
  widgets/deploymentsView/README.md
Labels: internal

#2505 RD-6316 RD-7116 RD-7117 RND-220 Cherry pick from master branch [7.0]
  app/widgets/common/deployments/DeploymentActions.ts
  app/widgets/common/deploymentsView/map/DeploymentsMap.tsx
  test/cypress/integration/widgets/deployments_spec.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
  test/cypress/integration/widgets/environment_button_spec.ts
  test/cypress/support/editMode.ts
  widgets/deployments/src/types.ts
  widgets/deploymentsView/README.md
Labels: internal

#2511 RND-278 Sync widget README.md files with user documentation
  widgets/blueprintActionButtons/README.md
  widgets/blueprints/README.md
Labels: internal

#2510 RD-7133 Create Environment Adjustments
  app/translations/en.json
  package-lock.json
  package.json
  test/cypress/integration/widgets/environment_button_spec.ts
  test/cypress/support/labels.ts
  widgets/environmentButton/src/CreateEnvironmentModal.tsx
Labels: internal

#2508 RND-102 Reuse git logic extracted to common-backend
  backend/handler/TerraformHandler.ts
  backend/package-lock.json
  backend/package.json
Labels: internal

#2513 RD-7133 fix system test and refactor
  test/cypress/integration/widgets/deployment_actions_spec.ts
  test/cypress/integration/widgets/deployments_spec.ts
Labels: bug-fix
