Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2023-02, with the labels that each got.

#2413 RD-5764: Blueprints TS migration
  app/translations/en.json
  app/widgets/common/actions/SearchActions.ts
  app/widgets/common/blueprints/BlueprintActions.ts
  widgets/blueprints/src/BlueprintState.tsx
  widgets/blueprints/src/BlueprintUploadActionsMenu.tsx
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsList.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
  widgets/blueprints/src/types.ts
  widgets/blueprints/src/widget.tsx
  widgets/blueprints/src/widget.utils.ts
Labels: internal

#2420 RD-6929 Resolved http-cache-semantics vulnerability
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#2403 RD-5774 Migration of Labels widget
  app/widgets/common/labels/LabelsModal.tsx
  widgets/labels/src/AddLabelsModal.tsx
  widgets/labels/src/LabelsTable.tsx
  widgets/labels/src/widget.tsx
Labels: internal

#2422 RD-6931 Migrated away from cypress-get-table package
  package-lock.json
  package.json
  test/cypress/support/commands.ts
Labels: dependencies, internal

#2424 RD-6932 Bump babel-jest package version to fix security issue
  package-lock.json
  package.json
Labels: dependencies, internal

#2383 RD-6838 Fix for failing system test
  test/cypress/integration/widgets/filter_spec.ts
Labels: bug-fix, internal

#2423 RD-5789 Migrate all outstanding non-widget files to TypeScript
  .eslintrc.json
  README.md
  app/app.tsx
  app/widgets/common/blueprints/BlueprintActions.ts
  app/widgets/common/inputs/DataTypesButton.tsx
  devServer.ts
  package-lock.json
  package.json
  scripts/tsconfig.json
  scripts/updateReadmes.ts
  scripts/widgetBackendWatcher.ts
  test/jest/setupAfterEnv.ts
  test/jest/utils/Toolbox.test.ts
  test/jest/widgets/topology/DataProcessor.test.ts
  test/jest/widgets/topology/NodeStatusService.test.ts
  test/jest/widgets/topology/data/ExampleData.json
  webpack.config.ts
Labels: bug-fix, internal

#2428 RD-5731 Append blueprint_id parameter to the query
  app/widgets/common/deployModal/DeploymentInputs.tsx
  app/widgets/common/inputs/fields/NodeIdInputField.tsx
  app/widgets/common/inputs/fields/NodeInstanceInputField.tsx
  app/widgets/common/inputs/fields/NodeTypeInputField.tsx
  app/widgets/common/inputs/fields/OperationNameInputField.tsx
  app/widgets/common/inputs/fields/ScalingGroupInputField.tsx
  app/widgets/common/inputs/fields/useFetchUrlWithDeploymentId.ts
  app/widgets/common/inputs/fields/useFetchUrlWithIdFromContext.ts
  app/widgets/common/inputs/utils/blueprintIdContext.ts
  test/cypress/fixtures/blueprints/input_types.zip
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: feature

#2431 RD-6452 Used 'required' property to determine if deployment inputs are required
  app/widgets/common/inputs/InputFields.tsx
  app/widgets/common/inputs/types.ts
  app/widgets/common/inputs/utils/getInputsWithoutValues.ts
  test/cypress/fixtures/blueprints/without_required_inputs.zip
  test/cypress/integration/widgets/blueprints_spec.ts
Labels: feature

#2425 RD-6888 and RD-6871: Fix system test in getting started modal
  app/components/overlays/gettingStarted/GettingStartedModal.tsx
  app/components/overlays/gettingStarted/ModalActions.tsx
  app/translations/en.json
Labels: internal

#2433 RD-5782 Migrated sites widget
  widgets/sites/src/CreateModal.tsx
  widgets/sites/src/SiteActions.ts
  widgets/sites/src/SiteLocationInput.tsx
  widgets/sites/src/SiteLocationMap.tsx
  widgets/sites/src/SitesTable.tsx
  widgets/sites/src/UpdateModal.tsx
  widgets/sites/src/props/SitePropType.ts
  widgets/sites/src/widget.tsx
  widgets/sites/src/widget.types.ts
Labels: internal

#2435 RD-6920 Add environment blueprint generation endpoint
  backend/app.ts
  backend/handler/EnvironmentHandler.ts
  backend/handler/EnvironmentHandler.types.ts
  backend/handler/TerraformHandler.ts
  backend/routes/Environment.ts
  backend/routes/Environment.types.ts
  backend/templates/blueprints/environment.ejs
  backend/templates/blueprints/terraform/blueprint.ejs
  backend/templates/blueprints/terraform/inputs.ejs
  backend/templates/blueprints/terraform/outputs.ejs
  backend/templates/blueprints/terraform/variables.ejs
  backend/test/routes/Environment.test.ts
  backend/test/routes/fixtures/environment/blueprint_full.yaml
  backend/test/routes/fixtures/environment/blueprint_minimal.yaml
Labels: feature

#2427 RD-6876 Update secret with secret provider in Secrets widget when provider connection is broken
  app/translations/en.json
  app/widgets/common/inputs/fields/ValueListInputField.tsx
  app/widgets/common/secrets/SecretActions.ts
  test/cypress/integration/widgets/secrets_spec.ts
  widgets/secrets/src/CreateModal.tsx
  widgets/secrets/src/SecretsTable.tsx
  widgets/secrets/src/UpdateModal.tsx
Labels: feature

#2439 RD-5779 Migrated plugins widget
  app/translations/en.json
  widgets/plugins/src/MarketplaceModal.tsx
  widgets/plugins/src/PluginsTable.tsx
  widgets/plugins/src/widget.tsx
  widgets/plugins/src/widget.types.ts
Labels: internal

#2434 RD-5782 Translated sites widget
  app/translations/en.json
  widgets/sites/src/CreateModal.tsx
  widgets/sites/src/SiteLocationInput.tsx
  widgets/sites/src/SiteLocationMap.tsx
  widgets/sites/src/SitesTable.tsx
  widgets/sites/src/UpdateModal.tsx
  widgets/sites/src/widget.consts.ts
  widgets/sites/src/widget.tsx
  widgets/sites/src/widget.utils.ts
Labels: internal

#2438 RD-5780 Migrated pluginsNum widget
  app/translations/en.json
  widgets/pluginsNum/src/widget.tsx
Labels: internal

#2415 RD-6159 Disable Set Site if there are no sites
  app/widgets/common/deployments/DeploymentActionsMenu.tsx
  app/widgets/common/deployments/DeploymentActionsMenu.utils.ts
  app/widgets/common/deployments/useSitesExist.ts
  test/cypress/integration/widgets/deployment_actions_spec.ts
Labels: bug-fix

#2441 RD-6922 Removed info about version from sidebar
  app/components/basic.ts
  app/components/sidebar/SideBarHeader.tsx
  test/cypress/components/app/sidebar/SideBar_spec.tsx
Labels: feature

#2440 RD-6890 Modified error messages on login page
  app/components/routes/LoginPage.tsx
  app/translations/en.json
  test/cypress/integration/login_spec.ts
Labels: bug-fix

#2437 RD-6900 Create basic compatibility layer for custom user configuration
  backend/config.ts
  backend/routes/Config.types.ts
  backend/test/config.test.ts
  backend/test/fixtures/userConfig.json
Labels: feature

#2445 RD-6444 Synchronized widgets documentation
  widgets/blueprints/README.md
  widgets/deploymentButton/README.md
  widgets/deployments/README.md
Labels: internal

#2444 RD-7055 bump sequelize to `6.28.1` version to fix Snyk vulnerability
  backend/package-lock.json
  backend/package.json
Labels: internal

#2443 RD-6920 Use YAML serialization for blueprint generation
  backend/handler/EnvironmentHandler.ts
  backend/handler/EnvironmentHandler.types.ts
  backend/handler/TerraformHandler.ts
  backend/handler/TerraformHandler.types.ts
  backend/handler/services/BlueprintBuilder.ts
  backend/package-lock.json
  backend/package.json
  backend/routes/Environment.ts
  backend/routes/Environment.types.ts
  backend/routes/Terraform.ts
  backend/templates/blueprints/environment.ejs
  backend/templates/blueprints/terraform/blueprint.ejs
  backend/templates/blueprints/terraform/inputs.ejs
  backend/templates/blueprints/terraform/outputs.ejs
  backend/templates/blueprints/terraform/variables.ejs
  backend/test/routes/Environment.test.ts
  backend/test/routes/File.test.ts
  backend/test/routes/Terraform.test.ts
  backend/test/routes/fixtures/blueprint.yaml
  backend/test/routes/fixtures/environment/blueprint_full.yaml
  backend/test/routes/fixtures/environment/blueprint_minimal.yaml
  backend/test/routes/fixtures/terraform/2_blueprint.yaml
  backend/test/routes/fixtures/terraform/inputs_fetch-data-file.json
  backend/test/routes/fixtures/terraform/inputs_fetch-data.json
  backend/test/routes/fixtures/terraform/inputs_full.json
  backend/test/routes/fixtures/terraform/inputs_minimal.json
Labels: internal

#2448 RD-5763 Migrate Blueprint Info widget to TypeScript
  app/styles/style.scss
  app/translations/en.json
  app/widgets/common/actions/SummaryActions.ts
  test/cypress/integration/widgets/blueprint_info_spec.ts
  widgets/blueprintInfo/src/BlueprintInfo.tsx
  widgets/blueprintInfo/src/actions.ts
  widgets/blueprintInfo/src/types.ts
  widgets/blueprintInfo/src/widget.tsx
  widgets/deploymentInfo/src/widget.tsx
  widgets/deployments/src/widget.tsx
  widgets/sitesMap/src/widget.tsx
Labels: internal

#2452 RD-5776 Migrate Nodes widget to TypeScript
  app/translations/en.json
  app/widgets/common/deploymentsView/types.ts
  widgets/nodes/src/NodeInstanceModal.tsx
  widgets/nodes/src/NodeInstancesTable.tsx
  widgets/nodes/src/NodeType.tsx
  widgets/nodes/src/NodesTable.tsx
  widgets/nodes/src/TypeHierarchyTree.tsx
  widgets/nodes/src/props/NodeInstancePropType.ts
  widgets/nodes/src/types.ts
  widgets/nodes/src/widget.tsx
Labels: internal

#2453 RD-5776 Nodes widget refactoring
  app/translations/en.json
  widgets/nodes/src/NodeInstanceModal.tsx
  widgets/nodes/src/NodeInstancesTable.tsx
  widgets/nodes/src/NodeType.tsx
  widgets/nodes/src/NodesTable.tsx
  widgets/nodes/src/TypeHierarchyTree.tsx
  widgets/nodes/src/common.ts
  widgets/nodes/src/types.ts
  widgets/nodes/src/widget.tsx
Labels: internal

#2456 RD-6838 System test fix attempt
  test/cypress/integration/widgets/filter_spec.ts
Labels: bug-fix, internal

#2446 RD-5769 Migrate Events Filter widget
  app/translations/en.json
  app/widgets/common/utils/EventUtils.ts
  widgets/eventsFilter/src/EventFilter.tsx
  widgets/eventsFilter/src/widget.tsx
Labels: internal

#2436 RD-6319 implemented special validation on csys-location-lat and long
  app/translations/en.json
  app/widgets/common/labels/LabelsInput.tsx
  test/cypress/integration/widgets/labels_spec.ts
  test/cypress/support/labels.ts
Labels: feature

#2457 RD-5078 Refactor use of `FullDeployment` type and reduce number of `Deployment*` types
  app/widgets/common/actions/SearchActions.ts
  app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.types.ts
  app/widgets/common/deployments/DeploymentActions.ts
  app/widgets/common/deployments/DeploymentDetails.tsx
  app/widgets/common/deployments/UpdateDeploymentModal.tsx
  app/widgets/common/deploymentsView/types.ts
  widgets/blueprintInfo/src/actions.ts
  widgets/deploymentInfo/src/widget.tsx
  widgets/deploymentInfo/src/widget.types.ts
  widgets/deployments/src/DeploymentsSegment.tsx
  widgets/deployments/src/types.ts
  widgets/nodes/src/widget.tsx
Labels: internal
