Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2023-06, with the labels that each got.

#2565 RND-583 Improve redirects handling [7.0]
  app/actions/manager/auth.ts
  backend/handler/RequestHandler.ts
  backend/routes/External.ts
  backend/test/handlers/RequestHandler.test.ts
  backend/test/routes/External.test.ts
Labels: bug-fix

#2570 RND-887 Update Jest and types/Jest to 29.5.0
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: dependencies, internal

#2572 RND-887 Bump Jest and dottie [7.0.1]
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: dependencies

#2573 CYBL-2046 Fix data source in Deployment ID input field
  app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: bug-fix

#2574 CYBL-2046 Fix data source in Deployment ID input field [7.0.1]
  app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
  test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
Labels: bug-fix
