Repository cloudify-cosmo/cloudify-stage, pull requests merged in 2023-04, with the labels that each got.

#2515 RND-104 Reuse `DynamicTable` from ui-common
  app/components/common/DynamicTable.tsx
  app/components/page/editMode/EditWidgetModal.tsx
  app/components/shared.ts
  app/widgets/common/terraformModal/TerraformModalTableAccordion.tsx
  package-lock.json
  package.json
Labels: internal

#2514 RND-145: Disable selecting not common workflows in RunWorkflowModal
  app/widgets/common/actions/SearchActions.ts
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/deploymentsView/header/RunWorkflowModal.tsx
  app/widgets/common/executeWorkflow/types.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
Labels: feature

#2520 RD-6944 adjust HighlightText props
  app/widgets/common/components/parameter/ParameterValue.tsx
  app/widgets/common/executions/LatestExecutionStatusIcon.tsx
  widgets/topology/src/TerraformDetailsModal.tsx
Labels: internal

#2522 RND-311 Reuse features moved to `cloudify-ui-components`
  app/widgets/common/components/accordion/AccordionSection.tsx
  app/widgets/common/components/accordion/AccordionSectionWithDivider.tsx
  app/widgets/common/components/accordion/index.ts
  app/widgets/common/components/index.ts
  app/widgets/common/deployModal/GenericDeployModal.tsx
  app/widgets/common/secrets/InputMaskIcon.tsx
  app/widgets/common/secrets/SinglelineInput.tsx
  app/widgets/common/secrets/TogglableSecretsInput.tsx
  app/widgets/common/secrets/index.ts
  app/widgets/common/terraformModal/TerraformModal.tsx
  app/widgets/common/terraformModal/TerraformModalTableAccordion.tsx
  package-lock.json
  package.json
Labels: internal

#2523 RND-359 System test fix
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/support/commands.ts
Labels: bug-fix, internal

#2524 RND-359 System test fix backport (#2523)
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/support/commands.ts
Labels: bug-fix, internal

#2525 RND-145: Mocked data for testing purposes
  test/cypress/integration/widgets/deployments_view_spec.ts
Labels: bug-fix, internal

#2529 RND-422 Update `vm2` to fix audit failure
  backend/package-lock.json
Labels: dependencies, internal

#2530 RD-4589 Fix click event propagation prevention
  app/components/templateManagement/templates/Templates.tsx
  test/cypress/integration/templateManagement/templates_spec.ts
Labels: bug-fix, internal

#2531 RD-5771 Migrate Resource Filter widget to TypeScript
  app/translations/en.json
  app/utils/StageAPI.ts
  widgets/filter/src/Filter.tsx
  widgets/filter/src/FilterDropdown.tsx
  widgets/filter/src/types.ts
  widgets/filter/src/widget.tsx
Labels: internal

#2535 RD-4589 Fix click event propagation prevention (#2530)
  app/components/templateManagement/templates/Templates.tsx
  test/cypress/integration/templateManagement/templates_spec.ts
Labels: internal

#2537 RD-6901 Improve dropdown option click [7.0]
  test/cypress/integration/widgets/deployment_button_configuration_spec.ts
Labels: internal

#2538 RND-359 Extend fix for widgets adding
  test/cypress/integration/templateManagement/pages_edit_spec.ts
  test/cypress/integration/widgets/blueprint_num_spec.ts
  test/cypress/integration/widgets/plugins_num_spec.ts
  test/cypress/integration/widgets/sites_map_spec.ts
  test/cypress/support/editMode.ts
Labels: bug-fix, internal

#2521 RND-146: Given ability to modify workflow parameters while running workflow
  app/translations/en.json
  app/widgets/common/deploymentsView/DeploymentsView.tsx
  app/widgets/common/deploymentsView/header/RunWorkflowModal.consts.ts
  app/widgets/common/deploymentsView/header/RunWorkflowModal.tsx
  app/widgets/common/deploymentsView/header/RunWorkflowModal.types.ts
  app/widgets/common/deploymentsView/header/RunWorkflowModal.utils.ts
  app/widgets/common/deploymentsView/header/index.tsx
  app/widgets/common/deploymentsView/header/useParametersInputs.ts
  app/widgets/common/executeWorkflow/types.ts
  test/cypress/integration/widgets/deployments_view_spec.ts
Labels: feature

#2541 RND-107 Create Execution Logs widget - part 2
  app/translations/en.json
  app/utils/GenericConfig.ts
  test/cypress/integration/widgets/execution_logs_spec.ts
  test/cypress/support/commands.ts
  widgets/executionLogs/src/LogMessage.tsx
  widgets/executionLogs/src/LogsTable.tsx
  widgets/executionLogs/src/consts.ts
  widgets/executionLogs/src/widget.tsx
Labels: feature

#2544 RND-57: Adjusted way of filtering blueprints
  widgets/environmentButton/src/widget.tsx
Labels: bug-fix

#2545 RND-146: Synchronized documentation
  widgets/deploymentsView/README.md
Labels: internal

#2489 RD-6965 hidden open in composer buttons when user doesnt have bluepri…
  app/translations/en.json
  app/utils/consts.ts
  app/utils/stageUtils.ts
  test/cypress/integration/widgets/blueprint_actions_spec.ts
  test/cypress/support/commands.ts
  widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
  widgets/blueprints/src/BlueprintsCatalog.tsx
  widgets/blueprints/src/BlueprintsCatalogActionButtons.tsx
  widgets/blueprints/src/BlueprintsTable.tsx
Labels: bug-fix

#2548 RD-4589: Added test retries
  test/cypress/integration/templateManagement/templates_spec.ts
Labels: internal

#2551 RD-7152 Add support for Resource Filter widget configuration in Cypress tests
  test/cypress/integration/widgets/execution_logs_spec.ts
  test/cypress/support/commands.ts
Labels: bug-fix, internal

#2546 RND-313 Reuse login page component extracted to cloudify-ui-components
  app/components/overlays/gettingStarted/steps/WelcomeStep.tsx
  app/components/routes/ExternalRedirect.tsx
  app/components/routes/LoginPage.tsx
  app/components/routes/LogoPage.tsx
  app/components/routes/LogoutPage.tsx
  app/components/routes/SmartRedirect.tsx
  app/components/sidebar/banner/LargeLogo.tsx
  app/components/sidebar/banner/LogoLabel.tsx
  app/styles/style.scss
  package-lock.json
  package.json
  test/cypress/integration/user_configuration_spec.ts
Labels: internal

#2552 RND-163, RND-527 fix deployments_view_spec
  test/cypress/integration/widgets/deployments_view_spec.ts
Labels: bug-fix
